OHF-Voice/intents

.github/workflows/ci.yaml, script/intentfest/__init__.py, script/intentfest/__main__.py, script/intentfest/add_language.py, script/intentfest/error.py, script/intentfest/util.py, script/lint, tests/__init__.py, tests/conftest.py, tests/test_language_intents.py, tests/test_language_sentences.py
Create a generic helper script base for Python scripts.
Add CI for add language task
Allow running tests for a single language
=> Update add language script

.github/workflows/ci.yaml, script/format, script/intentfest/__init__.py, script/intentfest/add_language.py, script/intentfest/const.py, script/intentfest/util.py, script/intentfest/validate.py, script/lint
- Test that all sentence files have a test file
- Test that all test files have a sentence file
- Test that for HassTurnOn/Off/Toggle there is a domain slot in a domain specific file
- Test that each file only specifies the intent from the filename
- Test that each file references the correct language
=> Add validate script

responses/fr/HassClimateGetTemperature.yaml, sentences/fr/_common.yaml, sentences/fr/climate_HassClimateGetTemperature.yaml, sentences/fr/climate_HassClimateSetTemperature.yaml, sentences/fr/cover_HassCloseCover.yaml, sentences/fr/cover_HassOpenCover.yaml, sentences/fr/fan_HassTurnOff.yaml, sentences/fr/fan_HassTurnOn.yaml, sentences/fr/homeassistant_HassToggle.yaml, sentences/fr/homeassistant_HassTurnOff.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/_common.yaml, tests/fr/climate_HassClimateGetTemperature.yaml, tests/fr/climate_HassClimateSetTemperature.yaml, tests/fr/cover_HassCloseCover.yaml, tests/fr/cover_HassOpenCover.yaml, tests/fr/fan_HassTurnOff.yaml, tests/fr/fan_HassTurnOn.yaml, tests/fr/homeassistant_HassToggle.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Add 3 first french intents.
Note: toggle test is commented, we need to handle space before `{name}`
=> Init french

script/intentfest/validate.py, sentences/nl/cover_HassCloseCover.yaml, sentences/nl/cover_HassOpenCover.yaml, tests/nl/_common.yaml, tests/nl/cover_HassCloseCover.yaml, tests/nl/cover_HassOpenCover.yaml
Update Dutch coverage to help unblock #14
=> Update Dutch test coverage

tests/fr/homeassistant_HassToggle.yaml, tests/fr/homeassistant_HassTurnOff.yaml
=> Complete French test coverage

sentences/en/fan_HassTurnOff.yaml, sentences/en/light_HassTurnOff.yaml, tests/en/_common.yaml, tests/en/cover_HassCloseCover.yaml, tests/en/cover_HassOpenCover.yaml, tests/en/homeassistant_HassTurnOff.yaml, tests/en/homeassistant_HassTurnOn.yaml, tests/en/light_HassLightSet.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
=> Fix English test coverage

responses/dk/HassClimateGetTemperature.yaml, sentences/dk/_common.yaml, sentences/dk/climate_HassClimateGetTemperature.yaml, sentences/dk/climate_HassClimateSetTemperature.yaml, sentences/dk/cover_HassCloseCover.yaml, sentences/dk/cover_HassOpenCover.yaml, sentences/dk/fan_HassTurnOff.yaml, sentences/dk/fan_HassTurnOn.yaml, sentences/dk/homeassistant_HassTurnOff.yaml, sentences/dk/homeassistant_HassTurnOn.yaml, sentences/dk/light_HassLightSet.yaml, sentences/dk/light_HassTurnOff.yaml, sentences/dk/light_HassTurnOn.yaml, tests/dk/_common.yaml, tests/dk/climate_HassClimateGetTemperature.yaml, tests/dk/climate_HassClimateSetTemperature.yaml, tests/dk/cover_HassCloseCover.yaml, tests/dk/cover_HassOpenCover.yaml, tests/dk/fan_HassTurnOff.yaml, tests/dk/fan_HassTurnOn.yaml, tests/dk/homeassistant_HassTurnOff.yaml, tests/dk/homeassistant_HassTurnOn.yaml, tests/dk/light_HassLightSet.yaml, tests/dk/light_HassTurnOff.yaml, tests/dk/light_HassTurnOn.yaml
This adds basic support for Danish, with the features implemented that `python3 -m script.intentfest add_language dk` suggested for the initial commit.
=> Initial Danish language support

sentences/fr/_common.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/_common.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Add french sentences for turn on lights and turn off lights.
=> Add french turn on/off lights sentences

responses/pl/HassClimateGetTemperature.yaml, sentences/pl/_common.yaml, sentences/pl/climate_HassClimateGetTemperature.yaml, sentences/pl/climate_HassClimateSetTemperature.yaml, sentences/pl/cover_HassCloseCover.yaml, sentences/pl/cover_HassOpenCover.yaml, sentences/pl/fan_HassTurnOff.yaml, sentences/pl/fan_HassTurnOn.yaml, sentences/pl/homeassistant_HassTurnOff.yaml, sentences/pl/homeassistant_HassTurnOn.yaml, sentences/pl/light_HassLightSet.yaml, sentences/pl/light_HassTurnOff.yaml, sentences/pl/light_HassTurnOn.yaml, tests/pl/_common.yaml, tests/pl/climate_HassClimateGetTemperature.yaml, tests/pl/climate_HassClimateSetTemperature.yaml, tests/pl/cover_HassCloseCover.yaml, tests/pl/cover_HassOpenCover.yaml, tests/pl/fan_HassTurnOff.yaml, tests/pl/fan_HassTurnOn.yaml, tests/pl/homeassistant_HassTurnOff.yaml, tests/pl/homeassistant_HassTurnOn.yaml, tests/pl/light_HassLightSet.yaml, tests/pl/light_HassTurnOff.yaml, tests/pl/light_HassTurnOn.yaml
```sh
(venv) $ python3 -m script.intentfest validate
All good!
(venv) $ pytest tests --language pl
============================================================================================================== test session starts ==============================================================================================================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/oskar/
collected 2 items                                                                                                                                                                                                                               
tests/test_language_intents.py . …
```
=> Add Polish response, sentences and tests

responses/vi/HassClimateGetTemperature.yaml, sentences/vi/_common.yaml, sentences/vi/climate_HassClimateGetTemperature.yaml, sentences/vi/climate_HassClimateSetTemperature.yaml, sentences/vi/cover_HassCloseCover.yaml, sentences/vi/cover_HassOpenCover.yaml, sentences/vi/fan_HassTurnOff.yaml, sentences/vi/fan_HassTurnOn.yaml, sentences/vi/homeassistant_HassTurnOff.yaml, sentences/vi/homeassistant_HassTurnOn.yaml, sentences/vi/light_HassLightSet.yaml, sentences/vi/light_HassTurnOff.yaml, sentences/vi/light_HassTurnOn.yaml, tests/vi/_fixtures.yaml, tests/vi/climate_HassClimateGetTemperature.yaml, tests/vi/climate_HassClimateSetTemperature.yaml, tests/vi/cover_HassCloseCover.yaml, tests/vi/cover_HassOpenCover.yaml, tests/vi/fan_HassTurnOff.yaml, tests/vi/fan_HassTurnOn.yaml, tests/vi/homeassistant_HassTurnOff.yaml, tests/vi/homeassistant_HassTurnOn.yaml, tests/vi/light_HassLightSet.yaml, tests/vi/light_HassTurnOff.yaml, tests/vi/light_HassTurnOn.yaml
Add empty Vietnamese (`vi`) sentences so collaborators can work on it.
=> Add empty Vietnamese sentences

responses/pt/HassClimateGetTemperature.yaml, sentences/pt/_common.yaml, sentences/pt/climate_HassClimateGetTemperature.yaml, sentences/pt/climate_HassClimateSetTemperature.yaml, sentences/pt/cover_HassCloseCover.yaml, sentences/pt/cover_HassOpenCover.yaml, sentences/pt/fan_HassTurnOff.yaml, sentences/pt/fan_HassTurnOn.yaml, sentences/pt/homeassistant_HassTurnOff.yaml, sentences/pt/homeassistant_HassTurnOn.yaml, sentences/pt/light_HassLightSet.yaml, sentences/pt/light_HassTurnOff.yaml, sentences/pt/light_HassTurnOn.yaml, tests/pt/_fixtures.yaml, tests/pt/climate_HassClimateGetTemperature.yaml, tests/pt/climate_HassClimateSetTemperature.yaml, tests/pt/cover_HassCloseCover.yaml, tests/pt/cover_HassOpenCover.yaml, tests/pt/fan_HassTurnOff.yaml, tests/pt/fan_HassTurnOn.yaml, tests/pt/homeassistant_HassTurnOff.yaml, tests/pt/homeassistant_HassTurnOn.yaml, tests/pt/light_HassLightSet.yaml, tests/pt/light_HassTurnOff.yaml, tests/pt/light_HassTurnOn.yaml
Add empty Portugese sentences.
=> Add empty Portugese sentences

sentences/nb/_common.yaml
Color names need to be outputted in English as per #119. This fixes it for NB.
=> Make sure NB outputs English color names

CODEOWNERS, README.md, languages.yaml
=> Add Russian language leader

intents.yaml, script/intentfest/validate.py, script/test_file
=> Add domain to intents

sentences/nl/cover_HassCloseCover.yaml, sentences/nl/cover_HassOpenCover.yaml, tests/nl/cover_HassCloseCover.yaml, tests/nl/cover_HassOpenCover.yaml, tests/nl/homeassistant_HassTurnOff.yaml
Several changes for sentences for covers. Added "screen/screens" as cover description (I use this myself)
Also added sentences with a change in the order of words, and added some cover types to the sentences which only had "gordijn/gordijnen"
=> [NL] Update cover sentences

tests/sv/_fixtures.yaml, tests/sv/fan_HassTurnOn.yaml
Fixed PR #145 and the respective build errors.
=> Fixed PR #145

CODEOWNERS, README.md, languages.yaml, sentences/uk/_common.yaml, sentences/uk/climate_HassClimateGetTemperature.yaml, sentences/uk/climate_HassClimateSetTemperature.yaml, tests/uk/climate_HassClimateGetTemperature.yaml, tests/uk/climate_HassClimateSetTemperature.yaml
Also added myself as Lang leader if you have no objections)
=> [uk]Added climate intents

sentences/ro/_common.yaml
Added initial translations based on the en initial file and the es one which had more data.
=> Added initial translations

sentences/ro/_common.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml, tests/ro/_fixtures.yaml, tests/ro/homeassistant_HassTurnOff.yaml, tests/ro/homeassistant_HassTurnOn.yaml
Added homeassistant domain and basic tests for the Romanian language
=> Ro intents basic

sentences/nl/_common.yaml, sentences/nl/climate_HassClimateGetTemperature.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/nl/_fixtures.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
I tried adding `<doe> [het] <area>licht [<naar>] aan` to the `light_HassTurnOn`. But  decided against including it, since this will lead to clashes with the `HomeAssistant_HassTurnOn`  sentences
=> [NL] add variations for light toggling

sentences/en/climate_HassClimateGetTemperature.yaml
This just adds a few alternatives to cover more cases for temperature requests.
=> Add additional sentences for temperature requests

sentences/da/_common.yaml
This makes the Danish error responses sound more natural.
=> Improve Danish error responses

sentences/da/_common.yaml, sentences/da/homeassistant_HassTurnOff.yaml, sentences/da/homeassistant_HassTurnOn.yaml, tests/da/_fixtures.yaml, tests/da/homeassistant_HassTurnOff.yaml, tests/da/homeassistant_HassTurnOn.yaml
This also introduces some useful expansion rules.
=> Improve Danish homeassistant sentences

sentences/it/_common.yaml
Reverts home-assistant/intents#251 as it breaks CI.
=> Revert "Update _common.yaml"

tests/he/climate_HassClimateSetTemperature.yaml, tests/he/cover_HassCloseCover.yaml, tests/he/cover_HassOpenCover.yaml, tests/he/fan_HassTurnOff.yaml, tests/he/fan_HassTurnOn.yaml, tests/he/light_HassLightSet.yaml, tests/he/light_HassTurnOn.yaml
=> Fix expected slots for Hebrew tests

tests/es/cover_HassCloseCover.yaml, tests/es/homeassistant_HassTurnOff.yaml, tests/es/light_HassTurnOff.yaml, tests/es/light_HassTurnOn.yaml
=> Fix expected slots for Spanish tests

tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
=> Fix expected slots for French tests

tests/en/light_HassLightSet.yaml, tests/en/light_HassTurnOn.yaml
Fixes tests for https://github.com/home-assistant/intents/pull/277
=> Fix expected slots for English tests

tests/hu/cover_HassCloseCover.yaml, tests/hu/cover_HassOpenCover.yaml, tests/hu/light_HassLightSet.yaml, tests/hu/light_HassTurnOff.yaml, tests/hu/light_HassTurnOn.yaml
=> Fix expected slots for Hungarian tests

tests/de/climate_HassClimateSetTemperature.yaml
=> Fix German expected slots for German tests

tests/pl/light_HassLightSet.yaml
=> Fix expected slots for Polish tests

tests/nl/cover_HassCloseCover.yaml, tests/nl/light_HassLightSet.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
=> Fix expected slots for Dutch tests

tests/lt/homeassistant_HassTurnOff.yaml, tests/lt/homeassistant_HassTurnOn.yaml
=> Fix expected slots for Lithuanian tests

tests/sk/light_HassLightSet.yaml, tests/sk/light_HassTurnOn.yaml
=> Fix expected slots for Slovakian tests

tests/ru/light_HassLightSet.yaml, tests/ru/light_HassTurnOn.yaml
=> Fix expected slots for Russian tests

tests/ro/light_HassLightSet.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
=> Fix expected slots for Romanian tests

tests/pt/light_HassLightSet.yaml, tests/pt/light_HassTurnOff.yaml, tests/pt/light_HassTurnOn.yaml
=> Fix expected slots for Portugese tests

tests/uk/light_HassLightSet.yaml
=> Fix expected slots for Ukranian tests

tests/ur/climate_HassClimateSetTemperature.yaml, tests/ur/light_HassLightSet.yaml, tests/ur/light_HassTurnOn.yaml
=> Fix expected slots for Urdu tests

tests/it/cover_HassCloseCover.yaml, tests/it/cover_HassOpenCover.yaml, tests/it/light_HassLightSet.yaml
=> Fix expected slots for Italian tests

languages.yaml, responses/sw/HassClimateGetTemperature.yaml, sentences/sw/_common.yaml, sentences/sw/climate_HassClimateGetTemperature.yaml, sentences/sw/climate_HassClimateSetTemperature.yaml, sentences/sw/cover_HassCloseCover.yaml, sentences/sw/cover_HassOpenCover.yaml, sentences/sw/fan_HassTurnOff.yaml, sentences/sw/fan_HassTurnOn.yaml, sentences/sw/homeassistant_HassTurnOff.yaml, sentences/sw/homeassistant_HassTurnOn.yaml, sentences/sw/light_HassLightSet.yaml, sentences/sw/light_HassTurnOff.yaml, sentences/sw/light_HassTurnOn.yaml, tests/sw/_fixtures.yaml, tests/sw/climate_HassClimateGetTemperature.yaml, tests/sw/climate_HassClimateSetTemperature.yaml, tests/sw/cover_HassCloseCover.yaml, tests/sw/cover_HassOpenCover.yaml, tests/sw/fan_HassTurnOff.yaml, tests/sw/fan_HassTurnOn.yaml, tests/sw/homeassistant_HassTurnOff.yaml, tests/sw/homeassistant_HassTurnOn.yaml, tests/sw/light_HassLightSet.yaml, tests/sw/light_HassTurnOff.yaml, tests/sw/light_HassTurnOn.yaml
=> Add Swahilli

sentences/cs/_common.yaml
This seems to be needed for PRs #220 and #221 .
=> Add turn_on/off(_light) expansion rules for czech

README.md
Correcting the link, since all such issues were migrated to discussions.
=> fix isuues > discussions link

languages.yaml, responses/ml/HassClimateGetTemperature.yaml, sentences/ml/_common.yaml, sentences/ml/climate_HassClimateGetTemperature.yaml, sentences/ml/climate_HassClimateSetTemperature.yaml, sentences/ml/cover_HassCloseCover.yaml, sentences/ml/cover_HassOpenCover.yaml, sentences/ml/fan_HassTurnOff.yaml, sentences/ml/fan_HassTurnOn.yaml, sentences/ml/homeassistant_HassTurnOff.yaml, sentences/ml/homeassistant_HassTurnOn.yaml, sentences/ml/light_HassLightSet.yaml, sentences/ml/light_HassTurnOff.yaml, sentences/ml/light_HassTurnOn.yaml, tests/ml/_fixtures.yaml, tests/ml/climate_HassClimateGetTemperature.yaml, tests/ml/climate_HassClimateSetTemperature.yaml, tests/ml/cover_HassCloseCover.yaml, tests/ml/cover_HassOpenCover.yaml, tests/ml/fan_HassTurnOff.yaml, tests/ml/fan_HassTurnOn.yaml, tests/ml/homeassistant_HassTurnOff.yaml, tests/ml/homeassistant_HassTurnOn.yaml, tests/ml/light_HassLightSet.yaml, tests/ml/light_HassTurnOff.yaml, tests/ml/light_HassTurnOn.yaml
- add language entry
- add sentence template for homeassistant_HassTurnOn and homeassistant_HassTurnOff intents
- add tests files for homeassistant_HassTurnOn and homeassistant_HassTurnOff
=> [ML] Add Malayalam language

languages.yaml, sentences/ms/_common.yaml
Updated common yaml and change ms nativeName to Bahasa Melayu for consideration
=> Initial changes for ms (Malay Language/Bahasa Melayu)

sentences/cs/fan_HassTurnOff.yaml, sentences/cs/fan_HassTurnOn.yaml, tests/cs/fan_HassTurnOff.yaml, tests/cs/fan_HassTurnOn.yaml
Updated some intents variations
=> Czech fan update

sentences/cs/_common.yaml, sentences/cs/light_HassLightSet.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/_fixtures.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
sentences in:
light_HassTurnOff
light_HassTurnOn
light_HassLightSet
=> czech - light domain

CODEOWNERS, languages.yaml
=> Add sk language leader

sentences/cs/light_HassLightSet.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml
=> czech - light domian - purging code

sentences/cs/climate_HassClimateSetTemperature.yaml, tests/cs/climate_HassClimateSetTemperature.yaml
=> czech - climate domain add senteses

CODEOWNERS, languages.yaml
As per the suggestion in https://github.com/home-assistant/intents/pull/505#issuecomment-1374679742
=> Add lv language leader

.github/workflows/ci.yaml, .github/workflows/matchers/intentfest.json, .vscode/tasks.json, script/intentfest/validate.py, script/test, sentences/nl/fan_HassTurnOn.yaml
This will help people see the validation errors as comments on their PR
=> Add problem matcher for intentfest

responses/ms/HassClimateGetTemperature.yaml, sentences/ms/_common.yaml, sentences/ms/climate_HassClimateGetTemperature.yaml, tests/ms/_fixtures.yaml, tests/ms/climate_HassClimateGetTemperature.yaml
Added fixtures, HassClimateGetTemperature.
Updated common
=> [MS] added HassClimateGetTemperature

sentences/sv/_common.yaml, sentences/sv/light_HassLightSet.yaml, tests/sv/light_HassLightSet.yaml
Adds simple match for colors and variatns of color names
=> [SV] Add set color and color variants for swedish

sentences/ro/_common.yaml
I made some changes to responses/errors
I added some additions to the preposition ”din”
=> [RO] Update common.yaml

sentences/ur/_common.yaml, tests/ur/climate_HassClimateSetTemperature.yaml
Added Fahrenheit unit and test cases
=> UR - Add fahrenheit unit

sentences/it/_common.yaml, tests/it/climate_HassClimateGetTemperature.yaml, tests/it/homeassistant_HassTurnOff.yaml, tests/it/homeassistant_HassTurnOn.yaml
=> [IT] Test `skip_words`

sentences/ro/_common.yaml, sentences/ro/cover_HassCloseCover.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, tests/ro/_fixtures.yaml, tests/ro/cover_HassCloseCover.yaml
Added cover_HassCloseCover intent translations for Romanian
=> [RO] HassCloseCover

sentences/vi/_common.yaml, sentences/vi/homeassistant_HassTurnOff.yaml, sentences/vi/homeassistant_HassTurnOn.yaml, tests/vi/_fixtures.yaml, tests/vi/homeassistant_HassTurnOff.yaml, tests/vi/homeassistant_HassTurnOn.yaml
HASS Turn on/ off and tests script
=> Vietnamese First Settings

.github/workflows/nightly.yaml
Upload the wheels as artifact instead of source package
=> Upload wheels

languages.yaml, responses/lb/HassClimateGetTemperature.yaml, sentences/lb/_common.yaml, sentences/lb/climate_HassClimateGetTemperature.yaml, sentences/lb/climate_HassClimateSetTemperature.yaml, sentences/lb/cover_HassCloseCover.yaml, sentences/lb/cover_HassOpenCover.yaml, sentences/lb/fan_HassTurnOff.yaml, sentences/lb/fan_HassTurnOn.yaml, sentences/lb/homeassistant_HassTurnOff.yaml, sentences/lb/homeassistant_HassTurnOn.yaml, sentences/lb/light_HassLightSet.yaml, sentences/lb/light_HassTurnOff.yaml, sentences/lb/light_HassTurnOn.yaml, tests/lb/_fixtures.yaml, tests/lb/climate_HassClimateGetTemperature.yaml, tests/lb/climate_HassClimateSetTemperature.yaml, tests/lb/cover_HassCloseCover.yaml, tests/lb/cover_HassOpenCover.yaml, tests/lb/fan_HassTurnOff.yaml, tests/lb/fan_HassTurnOn.yaml, tests/lb/homeassistant_HassTurnOff.yaml, tests/lb/homeassistant_HassTurnOn.yaml, tests/lb/light_HassLightSet.yaml, tests/lb/light_HassTurnOff.yaml, tests/lb/light_HassTurnOn.yaml
First contributions to homeassistant_HassTurnOff
and homeassistant_HassTurnOn files.
=> Added Lëtzbuergesch (luxembourgish) as language.

sentences/en/light_HassLightSet.yaml, tests/en/light_HassLightSet.yaml
Add sentences that look for max/min commands instead of a percentage number for set light.
=> [EN] add max/min brightness sentences

sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
Added a couple of sentences that I felt were missing as an English native speaker.
=> [en] Add sentence variant for lights on/off

requirements.txt, script/intentfest/validate.py
Include combining marks in valid sentence characters.
This addresses the issue discussed here: https://github.com/home-assistant/intents/discussions/507#discussioncomment-4647403
=> Use regex package to support Unicode properties.

sentences/bn/_common.yaml
=> Only common-yaml 

sentences/ms/climate_HassClimateSetTemperature.yaml, sentences/ms/cover_HassCloseCover.yaml, sentences/ms/cover_HassOpenCover.yaml, tests/ms/_fixtures.yaml, tests/ms/climate_HassClimateSetTemperature.yaml, tests/ms/cover_HassCloseCover.yaml, tests/ms/cover_HassOpenCover.yaml
Adding the remaining sentences.
=> [MS] Added the remaining sentences and tests

script/intentfest/validate.py
Fix for https://github.com/home-assistant/intents/issues/670
=> Allow : in sentences for {list:slot} syntax

sentences/it/cover_HassCloseCover.yaml, sentences/it/cover_HassOpenCover.yaml, sentences/it/light_HassLightSet.yaml, sentences/it/light_HassTurnOff.yaml, sentences/it/light_HassTurnOn.yaml
=> [IT] Minor update

sentences/cs/light_HassLightSet.yaml, tests/cs/light_HassLightSet.yaml
Add Min/Max sentenses to HassLightSet
=> czech HassLightSet - Min/Max sentenses

sentences/ml/cover_HassOpenCover.yaml, tests/ml/cover_HassOpenCover.yaml
* Add `cover_HassOpenCover` intent sentences
* Add `cover_HassOpenCover` intent tests
=> [ml] Add `cover_HassOpenCover` intents

sentences/sv/_common.yaml, sentences/sv/light_HassLightSet.yaml
Updates set light to use the cleaner syntax suggested here: https://github.com/home-assistant/intents/pull/487#discussion_r1071547128
=> [SV] Use new max/min syntax

sentences/cs/_common.yaml, sentences/cs/light_HassLightSet.yaml
Changed sentenses to newer - cleaner - min/max list.
=> czech - LightSet - new clean min_max def

sentences/hr/_common.yaml, sentences/hr/climate_HassClimateGetTemperature.yaml, sentences/hr/climate_HassClimateSetTemperature.yaml, tests/hr/_fixtures.yaml, tests/hr/climate_HassClimateGetTemperature.yaml, tests/hr/climate_HassClimateSetTemperature.yaml
Added climate sentences and tests
=> [hr] Added climate

sentences/hr/_common.yaml, sentences/hr/light_HassLightSet.yaml, tests/hr/_fixtures.yaml, tests/hr/light_HassLightSet.yaml
Added brightens min/max sentences
=> [hr] brightens min/max

intents.yaml, script/intentfest/website_summary.py, website/src-11ty/index.html
- Remove Open/Close Cover intents from `intents.yaml`
- Fix website build
- Add used response count to the website
=> Fixes after response migration

responses/cs/HassClimateGetTemperature.yaml, responses/cs/HassClimateSetTemperature.yaml, responses/cs/HassLightSet.yaml, responses/cs/HassTurnOff.yaml, responses/cs/HassTurnOn.yaml, sentences/cs/climate_HassClimateGetTemperature.yaml, sentences/cs/climate_HassClimateSetTemperature.yaml, sentences/cs/fan_HassTurnOff.yaml, sentences/cs/fan_HassTurnOn.yaml, sentences/cs/homeassistant_HassTurnOff.yaml, sentences/cs/homeassistant_HassTurnOn.yaml, sentences/cs/light_HassLightSet.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassLightSet.yaml
Reflects new changes to sentenses and responses.
=> [CS] Czech files updated after migration.

responses/ro/HassClimateGetTemperature.yaml, responses/ro/HassClimateSetTemperature.yaml, responses/ro/HassLightSet.yaml, responses/ro/HassTurnOff.yaml, responses/ro/HassTurnOn.yaml, sentences/ro/fan_HassTurnOff.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml, sentences/ro/light_HassLightSet.yaml, sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, tests/ro/_fixtures.yaml, tests/ro/fan_HassTurnOff.yaml, tests/ro/fan_HassTurnOn.yaml, tests/ro/homeassistant_HassTurnOff.yaml, tests/ro/homeassistant_HassTurnOn.yaml, tests/ro/light_HassLightSet.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
Major overhaul after recent changes and some formatting normalization
=> [RO] Added responses

responses/cs/HassClimateGetTemperature.yaml, responses/cs/HassClimateSetTemperature.yaml
Fixing responses to negative temp values
=> [CS] Czech - temperature responses fix

sentences/lv/homeassistant_HassTurnOn.yaml, sentences/lv/light_HassLightSet.yaml, sentences/lv/light_HassTurnOff.yaml, sentences/lv/light_HassTurnOn.yaml
@makstech Please see some synonyms and inflections for different sentence variations.
=> Adding latvian (lv) synonyms and inflections

responses/nl/HassClimateGetTemperature.yaml, responses/nl/HassClimateSetTemperature.yaml, responses/nl/HassLightSet.yaml, responses/nl/HassTurnOff.yaml, responses/nl/HassTurnOn.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml
Translated the responses to Dutch.
While I was reviewing the combined homeassistant_HassTurnOn and Off files, I also added some additional sentences (and tests) for covers.
=> [NL] Translate responses

responses/es/HassClimateGetTemperature.yaml, responses/es/HassClimateSetTemperature.yaml, responses/es/HassLightSet.yaml, responses/es/HassTurnOff.yaml, responses/es/HassTurnOn.yaml
Translating new sentences. I've avoided the problem of having non-matching item and adjective grammatical genders by changing the phrases a little bit. Maybe they sound now a little "robotic"... I accept comments and suggestions about this!
=> Translating new sentences

responses/ml/HassClimateSetTemperature.yaml, responses/ml/HassLightSet.yaml, responses/ml/HassTurnOff.yaml, responses/ml/HassTurnOn.yaml
* Add `HassClimateSetTemperature` responses translation
* Add `HassLightSet` responses translation
* Add `HassTurnOff` responses translation
* Add `HassTurnOn` responses translation
=> [ml] Add `responses` translations

script/intentfest/website_summary.py, website/public/style.css, website/src-11ty/index.html
Add a new column that shows if all responses are translated. Checks by checking if any response matches an English response.
=> Track if errors are translated on progress website

responses/bg/HassClimateSetTemperature.yaml, responses/bg/HassLightSet.yaml, responses/bg/HassTurnOff.yaml, responses/bg/HassTurnOn.yaml
Translate the new response sentences
=> [BG]Translate the new response

responses/he/HassClimateSetTemperature.yaml, responses/he/HassLightSet.yaml, responses/he/HassTurnOff.yaml, responses/he/HassTurnOn.yaml
=> [HE] Translate responses

responses/ms/HassClimateSetTemperature.yaml, responses/ms/HassLightSet.yaml, responses/ms/HassTurnOff.yaml, responses/ms/HassTurnOn.yaml
=> [MS] Added responses

package/home_assistant_intents/__init__.py, script/intentfest/util.py
Merges sentences in sorted order when loading.
=> Sort files during testing

responses/ro/HassTurnOff.yaml
https://github.com/home-assistant/intents/pull/723
=> [RO] Upstream fix area responses

responses/cs/HassTurnOff.yaml
fix slots.name to slots.area in HassTurnOff
=> [CS] Czech - fix name/area

sentences/ml/homeassistant_HassTurnOff.yaml
* Remove PR #698 post-merge artefacts
=> [ml] Cleanup `homeassistant_HassTurnOff.yaml`

responses/ml/HassTurnOff.yaml
=> [ml] Fix area responses

sentences/lb/_common.yaml, sentences/lb/climate_HassClimateGetTemperature.yaml, sentences/lb/climate_HassClimateSetTemperature.yaml, tests/lb/climate_HassClimateGetTemperature.yaml, tests/lb/climate_HassClimateSetTemperature.yaml
Implemented Luxembourgish translations for HassClimatGetTemperature and HassClimateSetTemperature
=> Added Lëtzebuergesch (lb) translations for climate_HassClimateGetTemperature and climate_HassClimateSetTemperature

sentences/de/_common.yaml
Spelling References:
- https://www.duden.de/rechtschreibung/Markise
- https://de.wikipedia.org/wiki/Raffstore
=> Added some synonymous terms for `covers` and `skip_words`

responses/vi/HassClimateGetTemperature.yaml, responses/vi/HassClimateSetTemperature.yaml, responses/vi/HassLightSet.yaml, responses/vi/HassTurnOff.yaml, responses/vi/HassTurnOn.yaml, tests/vi/climate_HassClimateSetTemperature.yaml
- Add VI responses
- Update some tests
=> [VI] Add Vietnamese responses

sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml
Adds jaloezie and jaloezieën to sentences.
=> Add jaloezie/jaloezieën

languages.yaml, responses/de-CH/HassClimateGetTemperature.yaml, responses/de-CH/HassClimateSetTemperature.yaml, responses/de-CH/HassLightSet.yaml, responses/de-CH/HassTurnOff.yaml, responses/de-CH/HassTurnOn.yaml, sentences/de-CH/_common.yaml, sentences/de-CH/climate_HassClimateGetTemperature.yaml, sentences/de-CH/climate_HassClimateSetTemperature.yaml, sentences/de-CH/fan_HassTurnOff.yaml, sentences/de-CH/fan_HassTurnOn.yaml, sentences/de-CH/homeassistant_HassTurnOff.yaml, sentences/de-CH/homeassistant_HassTurnOn.yaml, sentences/de-CH/light_HassLightSet.yaml, sentences/de-CH/light_HassTurnOff.yaml, sentences/de-CH/light_HassTurnOn.yaml, tests/de-CH/_fixtures.yaml, tests/de-CH/climate_HassClimateGetTemperature.yaml, tests/de-CH/climate_HassClimateSetTemperature.yaml, tests/de-CH/fan_HassTurnOff.yaml, tests/de-CH/fan_HassTurnOn.yaml, tests/de-CH/homeassistant_HassTurnOff.yaml, tests/de-CH/homeassistant_HassTurnOn.yaml, tests/de-CH/light_HassLightSet.yaml, tests/de-CH/light_HassTurnOff.yaml, tests/de-CH/light_HassTurnOn.yaml
This adds a minimal set of sentences in Swiss German.
The variant in this set does not correspond to a particular dialect, but is a blend of different influences.
- Swiss German has vast variety of dialects that differ significantly from German.
- There is no standardized way to write Swiss German. There is no prescriptive, written grammar, and there are little rules on how to spell Swiss German.
- Swiss German is spoken in many dialects, but written mostly in informal context.
- In most cases, German is used for writing. 
- -------------------------------------
-  Because there are so many different dialects and there is very little standardization in writing, using Swiss German as an input option will be challenging.
- The transcriber engines I know of transcribe Swiss German into …
=> Initial commit to add Swiss German.

sentences/es/homeassistant_HassTurnOn.yaml
Updated to add "blinds" in Spanish.
=> [es] update homeassistant_HassTurnOn.yaml

sentences/tr/homeassistant_HassTurnOff.yaml, sentences/tr/homeassistant_HassTurnOn.yaml, tests/tr/homeassistant_HassTurnOff.yaml, tests/tr/homeassistant_HassTurnOn.yaml
Added normal hassturnon/off sentences and test sentences
=> [TR] Fixes after Convering from CoverTurnOn/Off to HassTurnOn/Off

sentences/cs/_common.yaml
Fix temperature units
add some dialect
=> [CS] _commons fixture

responses/bg/HassClimateGetTemperature.yaml, responses/bg/HassClimateSetTemperature.yaml, responses/bg/HassLightSet.yaml, responses/bg/HassTurnOff.yaml, responses/bg/HassTurnOn.yaml, sentences/bg/fan_HassTurnOn.yaml, sentences/bg/homeassistant_HassTurnOff.yaml, sentences/bg/homeassistant_HassTurnOn.yaml, sentences/bg/light_HassLightSet.yaml, sentences/bg/light_HassTurnOff.yaml, sentences/bg/light_HassTurnOn.yaml, tests/bg/_fixtures.yaml, tests/bg/homeassistant_HassTurnOff.yaml, tests/bg/homeassistant_HassTurnOn.yaml, tests/bg/light_HassLightSet.yaml, tests/bg/light_HassTurnOff.yaml, tests/bg/light_HassTurnOn.yaml
Also put double quotes to all strings in order to equalize them across the Bulgarian translation.
=> Remove extra spaces to conform the new parser

sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
I've seen this sentence come across the community (lamp [entity] aan), so I've added it to the list.
=> [NL] Add a an extra sentences for light_HassTurn(On | Off)

responses/ro/HassClimateGetTemperature.yaml, responses/ro/HassClimateSetTemperature.yaml, responses/ro/HassLightSet.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, sentences/ro/climate_HassClimateSetTemperature.yaml, sentences/ro/fan_HassTurnOff.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml, sentences/ro/light_HassLightSet.yaml, sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, tests/ro/_fixtures.yaml, tests/ro/climate_HassClimateGetTemperature.yaml, tests/ro/climate_HassClimateSetTemperature.yaml, tests/ro/fan_HassTurnOff.yaml, tests/ro/fan_HassTurnOn.yaml, tests/ro/homeassistant_HassTurnOff.yaml, tests/ro/homeassistant_HassTurnOn.yaml, tests/ro/light_HassLightSet.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
- area-ClimateGetTemperature respones
- area ClimateSetTemperature
- Min/Max/Half for LightSet brightness - specific respones
- fan_TurnOn/Off for areas, with specific respones
- dedicated answers for turning lights on/off
- area LightTurnOn/Off responses
- fixture name changes to comply with recommendations
- implied area context for most intents
- response tests
=> [RO] Context fixes and refactorings

responses/is/HassClimateGetTemperature.yaml, responses/is/HassClimateSetTemperature.yaml, responses/is/HassLightSet.yaml, responses/is/HassTurnOff.yaml, responses/is/HassTurnOn.yaml
=> Updated responses for Icelandic language.

responses/sv/HassLightSet.yaml, responses/sv/HassTurnOff.yaml, responses/sv/HassTurnOn.yaml
A little more nuanced language regarding responses.
=> [SV] Tuned nuances of responses

responses/cs/HassLightSet.yaml, responses/cs/HassTurnOff.yaml, sentences/cs/_common.yaml, sentences/cs/light_HassLightSet.yaml, tests/cs/_fixtures.yaml, tests/cs/climate_HassClimateGetTemperature.yaml, tests/cs/fan_HassTurnOff.yaml, tests/cs/fan_HassTurnOn.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
* Add response tests
* New min/max responses for better answers
* minor fixes
=> [CS] Reponses fix

sentences/cs/light_HassLightSet.yaml
Fix sentences for min/max brightness
=> [CS] Fixing mix/min sentences for brightness (#938)

sentences/nb/homeassistant_HassTurnOff.yaml, sentences/nb/homeassistant_HassTurnOn.yaml
Fixing two sentences to match the updated parser introduced in #830
=> [NB] Fix sentences (updated parser rule)

sentences/de/_common.yaml
Just fixing a small typo, which I added the last time.
=> [de] Fix typo

sentences/lb/_common.yaml, sentences/lb/homeassistant_HassTurnOff.yaml, sentences/lb/homeassistant_HassTurnOn.yaml, tests/lb/_fixtures.yaml, tests/lb/homeassistant_HassTurnOff.yaml, tests/lb/homeassistant_HassTurnOn.yaml
restructured test sentences to reflect recent changes in language model
=> Modified fixtures, brightness expansion rule

responses/lb/HassLightSet.yaml, responses/lb/HassTurnOff.yaml, responses/lb/HassTurnOn.yaml, sentences/lb/_common.yaml, sentences/lb/homeassistant_HassTurnOff.yaml, sentences/lb/light_HassTurnOff.yaml, sentences/lb/light_HassTurnOn.yaml, tests/lb/homeassistant_HassTurnOff.yaml, tests/lb/light_HassTurnOff.yaml, tests/lb/light_HassTurnOn.yaml
Added first sentences for light areas turn on/off
adapted fixtures and responses
=> lb translations light_HassTurnOff / On

responses/lb/HassLightSet.yaml, sentences/lb/_common.yaml, sentences/lb/light_HassLightSet.yaml, tests/lb/light_HassLightSet.yaml
Added luxembourgish sentences and tests for HassLightSet
=> Added lb light_HassLightSet sentences & responses

responses/nl/HassLightSet.yaml, responses/nl/HassTurnOff.yaml, responses/nl/HassTurnOn.yaml, sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, sentences/nl/light_HassLightSet.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml
Capitalize the first character of the responses in case a template is used as the first word(s)
also changed the optional spaces `[' ']` to `[ ]`
=> [NL]  Capitalize first character of responses

sentences/nb/_common.yaml, sentences/nb/light_HassLightSet.yaml, tests/nb/light_HassLightSet.yaml
Adding min/max brightness with tests. A few clean-ups along the way.
=> [NB] Min / max light brightness

sentences/nb/_common.yaml, sentences/nb/homeassistant_HassTurnOff.yaml, sentences/nb/homeassistant_HassTurnOn.yaml, tests/nb/_fixtures.yaml, tests/nb/homeassistant_HassTurnOff.yaml, tests/nb/homeassistant_HassTurnOn.yaml
Adding covers to HassTurnOn/off with tests.
This PR replaces #965, which has now been closed.
=> [NB] Adding covers

sentences/fr/homeassistant_HassTurnOff.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml
Add "volets" as cover name
Add "monte" as cover verb
Add "close/open all" sentences (Should we allow that ?)
=> Add more cover sentences for French

shared/__init__.py
For issue: https://github.com/home-assistant/intents/issues/1004
=> Use hass state for comparsion

sentences/nb/_common.yaml, sentences/nb/cover_HassGetState.yaml, tests/nb/_fixtures.yaml, tests/nb/cover_HassGetState.yaml
Adding HassGetState for covers. It passes all tests, but we will need to follow up with expanded testing. 
Norwegian is getting pretty confusing with "er vinduene åpne oppe" and so on, or in some dialects "er vinduene oppe oppe"
=> [NB] Adding HassGetState for covers

responses/nl/HassGetState.yaml, tests/nl/_fixtures.yaml
Use in/out states instead of translation mapping in the responses
=> [NL] Use in/out states for fixtures

responses/nl/HassGetState.yaml
Remove concatenation with `~` in response template
=> [NL] Avoid concatenation in response template

responses/nl/HassGetState.yaml, tests/nl/homeassistant_HassGetState.yaml
The template to limit the results should be applied on more places than I initially did.
=> [NL] Apply template on all relevant responses

responses/nl/HassTurnOff.yaml
align with turn on response and avoid plurality issues
=> [NL] Small change in response to turn off lights

responses/nl/HassTurnOff.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, tests/nl/cover_HassTurnOff.yaml, tests/nl/cover_HassTurnOn.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml
change the way the intents are split to the separate file
=> [NL] Change split covers

responses/cs/HassTurnOn.yaml, sentences/cs/homeassistant_HassTurnOff.yaml, sentences/cs/homeassistant_HassTurnOn.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
Fix intents to turn on one light entity.
Update response to turn on light.
=> [CS] Fixing lights intents

responses/zh-tw/HassClimateGetTemperature.yaml, responses/zh-tw/HassClimateSetTemperature.yaml, responses/zh-tw/HassGetState.yaml, responses/zh-tw/HassLightSet.yaml, responses/zh-tw/HassTurnOff.yaml, responses/zh-tw/HassTurnOn.yaml, sentences/zh-tw/_common.yaml, sentences/zh-tw/homeassistant_HassTurnOff.yaml, sentences/zh-tw/homeassistant_HassTurnOn.yaml, sentences/zh-tw/light_HassLightSet.yaml, tests/zh-tw/_fixtures.yaml, tests/zh-tw/fan_HassTurnOff.yaml, tests/zh-tw/fan_HassTurnOn.yaml, tests/zh-tw/homeassistant_HassTurnOff.yaml, tests/zh-tw/homeassistant_HassTurnOn.yaml, tests/zh-tw/light_HassLightSet.yaml, tests/zh-tw/light_HassTurnOff.yaml, tests/zh-tw/light_HassTurnOn.yaml
[zh-tw] Update Responses for T.Chinese
=> [zh-tw] Update Responses for T.Chinese

responses/he/HassClimateSetTemperature.yaml, responses/he/HassGetState.yaml, responses/he/HassLightSet.yaml, responses/he/HassTurnOff.yaml, responses/he/HassTurnOn.yaml
Performed some improvements in the responses and added more
=> Working on Hebrew

package/pyproject.toml, responses/en/HassTurnOn.yaml, script/intentfest/validate.py, sentences/en/_common.yaml, sentences/en/homeassistant_HassGetState.yaml, sentences/en/homeassistant_HassTurnOff.yaml, sentences/en/homeassistant_HassTurnOn.yaml, sentences/en/lock_HassGetState.yaml, sentences/en/scene_HassTurnOn.yaml, sentences/en/script_HassTurnOn.yaml, tests/__init__.py, tests/en/_fixtures.yaml, tests/en/fan_HassTurnOn.yaml, tests/en/lock_HassGetState.yaml, tests/en/scene_HassTurnOn.yaml, tests/en/script_HassTurnOn.yaml, tests/test_language_intents.py, tests/test_language_sentences.py
Coverage of  lock and script domains (in default exposed domains for Assist).
=> More HassGetSentences for English

script/intentfest/add_language.py, script/intentfest/validate.py, sentences/en/_common.yaml, sentences/en/binary_sensor_HassGetState.yaml, sentences/en/homeassistant_HassTurnOff.yaml, sentences/en/homeassistant_HassTurnOn.yaml, shared/__init__.py, tests/bg/cover_HassTurnOff.yaml, tests/bg/cover_HassTurnOn.yaml, tests/en/_fixtures.yaml, tests/en/binary_sensor_HassGetState.yaml, tests/en/cover_HassTurnOff.yaml, tests/en/cover_HassTurnOn.yaml, tests/hr/cover_HassTurnOff.yaml, tests/hr/cover_HassTurnOn.yaml, tests/ro/cover_HassGetState.yaml, tests/ro/cover_HassTurnOff.yaml, tests/ro/cover_HassTurnOn.yaml, tests/test_language_intents.py, tests/test_language_sentences.py, tests/zh-cn/cover_HassTurnOff.yaml, tests/zh-cn/cover_HassTurnOn.yaml, tests/zh-tw/cover_HassTurnOff.yaml, tests/zh-tw/cover_HassTurnOn.yaml
Very basic sentences for [binary sensor device classes](https://www.home-assistant.io/integrations/binary_sensor/#device-class)
Included is an update to include fixture attributes in entity context (with a few fixes to YAML files).
=> Binary sensor sentences for English

sentences/en/_common.yaml, tests/en/light_HassLightSet.yaml
Add turn to <set> expansion rule
=> [EN] Add "turn" to <set>

responses/sr/HassClimateGetTemperature.yaml, responses/sr/HassClimateSetTemperature.yaml, responses/sr/HassLightSet.yaml, responses/sr/HassTurnOff.yaml, responses/sr/HassTurnOn.yaml
Serbian declension rules:
- When the value is the unit or ends with the unit (21, 31, 41, etc.), the noun is set in nominative singular (ie _1 степен_)
- When the value is between 11 and 19 (inclusive) the noun is set in the genitive plural, giving it the -и ending for masculine, and the -a ending for feminine (ie since _степен_ is masculine, it becomes _11 степени_)
- When the value is a digit between two and four the noun is set in the genitive singular, giving it the -a ending for masculine, and the -e ending for feminine (ie since _степен_ is masculine, it becomes _4 степена_)
- Otherwise, when the digit is one of 0, 5, 6, 7, 8, 9 the noun is set in the genitive plural, giving it the -и ending for masculine, and the -a ending for feminine (ie since _степен_ is masculine, it becomes …
=> [SR] Serbian intents

sentences/es/cover_HassGetState.yaml
Add accents to some interrogative words.
=> Minor typos

responses/zh-tw/HassGetState.yaml, responses/zh-tw/HassTurnOn.yaml, sentences/zh-tw/_common.yaml, sentences/zh-tw/homeassistant_HassGetState.yaml, sentences/zh-tw/homeassistant_HassTurnOff.yaml, sentences/zh-tw/homeassistant_HassTurnOn.yaml, sentences/zh-tw/lock_HassGetState.yaml, sentences/zh-tw/scene_HassTurnOn.yaml, sentences/zh-tw/script_HassTurnOn.yaml, tests/zh-tw/_fixtures.yaml, tests/zh-tw/homeassistant_HassGetState.yaml, tests/zh-tw/lock_HassGetState.yaml, tests/zh-tw/scene_HassTurnOn.yaml, tests/zh-tw/script_HassTurnOn.yaml
More hassget sentences for T.Chinese follow by English.
=> [zh-tw] more hassget sentences for T.Chinese

sentences/he/_common.yaml, sentences/he/cover_HassGetState.yaml, sentences/he/homeassistant_HassGetState.yaml, tests/he/_fixtures.yaml, tests/he/cover_HassGetState.yaml, tests/he/homeassistant_HassGetState.yaml
=> [HE] Update common.yaml

responses/hr/HassGetState.yaml, sentences/hr/_common.yaml, sentences/hr/homeassistant_HassGetState.yaml, tests/hr/_fixtures.yaml, tests/hr/homeassistant_HassGetState.yaml
=> [hr] GetState intents

sentences/ca/_common.yaml, sentences/ca/climate_HassClimateSetTemperature.yaml, sentences/ca/homeassistant_HassTurnOn.yaml, sentences/ca/light_HassTurnOff.yaml, sentences/ca/light_HassTurnOn.yaml
=> [ca] Update to new space parsing syntax

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, tests/nl/binary_sensor_HassGetState.yaml
Added a couple of expansion rules as well
=> [NL] Add any/where/all for binary sensor

responses/de/HassGetState.yaml, sentences/de/_common.yaml, sentences/de/cover_HassGetState.yaml, sentences/de/homeassistant_HassGetState.yaml, sentences/de/lock_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/cover_HassGetState.yaml, tests/de/homeassistant_HassGetState.yaml, tests/de/lock_HassGetState.yaml
~still work in progress ... but any early review is welcome~ :slightly_smiling_face:
=> [DE] Add HassGetState sentences

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, sentences/nl/cover_HassGetState.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, sentences/nl/homeassistant_HassGetState.yaml, sentences/nl/light_HassLightSet.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, sentences/nl/lock_HassGetState.yaml, tests/nl/binary_sensor_HassGetState.yaml, tests/nl/homeassistant_HassGetState.yaml, tests/nl/lock_HassGetState.yaml
Apply newly created expansion rules on all existing sentences.
=> [NL] Apply newly created expansion rules

sentences/tr/cover_HassTurnOff.yaml, sentences/tr/homeassistant_HassTurnOff.yaml
Fixing some minor inconveniences.
=> TR - Fixing some minor issues

sentences/cs/_common.yaml
=> [CS] bs-commons

responses/nb/HassClimateGetTemperature.yaml, responses/nb/HassClimateSetTemperature.yaml, tests/nb/_fixtures.yaml, tests/nb/climate_HassClimateGetTemperature.yaml, tests/nb/climate_HassClimateSetTemperature.yaml
This PR will fix an issue with getting temperature (`HassClimateGetTemperature`) for Norwegian Bokmål `nb`.
When I ran this command:
```bash
python3 -m script.intentfest parse --language nb --sentence "hvor varmt er det i stuen"
```
I got this error:
```bash
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/stale/private_projects/home-assistant/intents/script/intentfest/__main__.py", line 29, in <module>
sys.exit(main())
File "/Users/stale/private_projects/home-assistant/intents/script/intentfest/__main__.py" …
```
=> [NB] Fix get temperature

responses/pt-br/HassTurnOn.yaml, sentences/pt-br/_common.yaml, sentences/pt-br/homeassistant_HassTurnOn.yaml, tests/pt-br/_fixtures.yaml, tests/pt-br/homeassistant_HassTurnOn.yaml
Added turn on sentences to pt-br, with their responses and tests. Also translated the fixtures to make more sense in pt-br
=> Add hass turn on sentences to pt br

sentences/pt-br/_common.yaml
added a couple skipwords that can be used in pt-br
=> added skipwords to PT-BR

responses/pt-br/HassTurnOff.yaml, sentences/pt-br/_common.yaml, sentences/pt-br/homeassistant_HassTurnOff.yaml, tests/pt-br/homeassistant_HassTurnOff.yaml
Added sentences and responses for HASS Turn Off intention on pt-BR, Corrected some grammar
=> [pt-BR] Added sentences and responses for Turn Off Intention

responses/hr/HassGetState.yaml, sentences/hr/_common.yaml, sentences/hr/cover_HassGetState.yaml, tests/hr/_fixtures.yaml, tests/hr/cover_HassGetState.yaml
=> [hr] covers get state

responses/zh-tw/HassTurnOff.yaml, sentences/zh-tw/_common.yaml, sentences/zh-tw/binary_sensor_HassGetState.yaml, sentences/zh-tw/fan_HassTurnOff.yaml, sentences/zh-tw/homeassistant_HassTurnOff.yaml, sentences/zh-tw/homeassistant_HassTurnOn.yaml, sentences/zh-tw/light_HassTurnOff.yaml, sentences/zh-tw/lock_HassTurnOff.yaml, sentences/zh-tw/lock_HassTurnOn.yaml, tests/zh-tw/_fixtures.yaml, tests/zh-tw/binary_sensor_HassGetState.yaml, tests/zh-tw/fan_HassTurnOff.yaml, tests/zh-tw/homeassistant_HassGetState.yaml, tests/zh-tw/homeassistant_HassTurnOff.yaml, tests/zh-tw/homeassistant_HassTurnOn.yaml, tests/zh-tw/light_HassTurnOff.yaml, tests/zh-tw/lock_HassTurnOff.yaml, tests/zh-tw/lock_HassTurnOn.yaml
Follow EN, Add binary sensor sentences/Tests and other minor updates.
=> [zh-tw] Binary sensor sentences and other minor update

sentences/hr/_common.yaml, tests/hr/cover_HassGetState.yaml
Added variations for covers sentences
=> [hr] Added some variations for cover sentences

responses/hr/HassClimateGetTemperature.yaml, responses/hr/HassClimateSetTemperature.yaml, responses/hr/HassLightSet.yaml, responses/hr/HassTurnOff.yaml, responses/hr/HassTurnOn.yaml, sentences/hr/climate_HassClimateGetTemperature.yaml, sentences/hr/light_HassLightSet.yaml, tests/hr/_fixtures.yaml, tests/hr/climate_HassClimateGetTemperature.yaml, tests/hr/climate_HassClimateSetTemperature.yaml, tests/hr/light_HassLightSet.yaml, tests/hr/light_HassTurnOff.yaml, tests/hr/light_HassTurnOn.yaml
- added missing responses
- tests cleanup
- some changes on climate
=> [hr] Added missing responses

responses/hr/HassTurnOff.yaml, responses/hr/HassTurnOn.yaml, sentences/hr/fan_HassTurnOff.yaml, sentences/hr/fan_HassTurnOn.yaml, tests/hr/_fixtures.yaml, tests/hr/fan_HassTurnOff.yaml, tests/hr/fan_HassTurnOn.yaml, tests/hr/homeassistant_HassTurnOff.yaml
=> [hr] Added fan intents

sentences/he/_common.yaml, sentences/he/climate_HassClimateGetTemperature.yaml, tests/he/climate_HassClimateGetTemperature.yaml
Common update + one new sentence & test
=> [HE] Common update + one new sentence & test

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, tests/nl/binary_sensor_HassGetState.yaml
Add any/all/which/how many sentences for all binary sensor device classes which do not have conflicts with other domains
device classes which will not be included now are:
* door
* garage_door
* lock
* window
=> [NL] any/all/which/how many for binary sensor

shared/__init__.py
In responses, we should have a handy `query.total_results`
See this Discord discussion https://discord.com/channels/330944238910963714/1054846248374505572/1078695288463704126
=> Add total_results property to query

responses/de/HassTurnOff.yaml, responses/de/HassTurnOn.yaml, sentences/de/_common.yaml, sentences/de/lock_HassTurnOff.yaml, sentences/de/lock_HassTurnOn.yaml, tests/de/lock_HassTurnOff.yaml, tests/de/lock_HassTurnOn.yaml
Add locking and unlocking in German
=> [DE] Add lock intents

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, sentences/nl/climate_HassClimateSetTemperature.yaml, tests/nl/binary_sensor_HassGetState.yaml
Reverts home-assistant/intents#1236
Accidentally included binary sensor changes
=> Revert "Nl_climate_set"

sentences/nl/climate_HassClimateSetTemperature.yaml
* merge area and name intents
* make either graden or temperature optional
=> [NL] Small change to climate set

sentences/en/_common.yaml, sentences/en/climate_HassClimateSetTemperature.yaml, sentences/en/light_HassLightSet.yaml
In regards to setting the brightness of a lamp, we can say `increase the brightness to 75%`
=> [EN] Added increase and decrease to set

responses/hr/HassTurnOff.yaml, responses/hr/HassTurnOn.yaml, sentences/hr/_common.yaml, sentences/hr/lock_HassGetState.yaml, sentences/hr/lock_HassTurnOff.yaml, sentences/hr/lock_HassTurnOn.yaml, tests/hr/_fixtures.yaml, tests/hr/lock_HassGetState.yaml, tests/hr/lock_HassTurnOff.yaml, tests/hr/lock_HassTurnOn.yaml
=> [hr] lock intents

tests/fi/_fixtures.yaml, tests/fi/cover_HassGetState.yaml, tests/fi/homeassistant_HassGetState.yaml
I added Finnish states to fixtures and fixed Finnish-English mismatch on test responses.
=> [FI] Add Finnish fixture words for states based on lokalise content

sentences/de/light_HassLightSet.yaml, tests/de/_fixtures.yaml, tests/de/homeassistant_HassGetState.yaml, tests/de/light_HassLightSet.yaml
fixes https://github.com/home-assistant/core/issues/87166
=> [De] Fix set light acts on all

sentences/da/_common.yaml
Hoping to be able to contribute with Danish translations of sentences, but first time user of Code Spaces so not quite sure if everything went to plan.
=> [DA] Aligned Danish version of _common.yaml with English version

sentences/de/_common.yaml, tests/de/lock_HassGetState.yaml
added the following phrases for unlocked
"versperrt", "abgesperrt" or "zugesperrt"
added the following phrases for unlocked:
"nicht verriegelt","nicht verperrt","nicht abgesperrt", "nicht zugesperrt","entsperrt","offen"
Added tests for the new phrases
=> [DE] added new phrases for lock_states

responses/ar/HassTurnOn.yaml, sentences/ar/cover_HassTurnOn.yaml, tests/ar/_fixtures.yaml, tests/ar/cover_HassTurnOn.yaml
- open cover in area
- open cover
- open garage door
=> [ar] cover_HassTurnOn

responses/ar/HassTurnOff.yaml, sentences/ar/_common.yaml, sentences/ar/cover_HassTurnOff.yaml, tests/ar/cover_HassTurnOff.yaml
* close garage door
* close cover by cover_class
* close cover in area
* close cover by name
=> [ar] cover_HassTurnOff

sentences/de/_common.yaml, tests/de/lock_HassGetState.yaml
As #1243 seems to be not active anymore I created a new PR with some more phrases added.
=> [DE] Add new variations to lock_HassGetState

sentences/ar/homeassistant_HassTurnOff.yaml, tests/ar/homeassistant_HassTurnOff.yaml
* Turn off general device or entity
=> [ar] homeassistant_HassTurnOff

sentences/ar/homeassistant_HassTurnOff.yaml, tests/ar/cover_HassTurnOn.yaml, tests/ar/homeassistant_HassTurnOff.yaml
add the missing response for open the garage door.
=> [ar] cover_HassTurnOn missing response

sentences/ar/light_HassTurnOff.yaml, sentences/ar/light_HassTurnOn.yaml, tests/ar/light_HassTurnOff.yaml, tests/ar/light_HassTurnOn.yaml
=> [ar] light_HassTurnOn && light_HassTurnOff

sentences/ar/_common.yaml
=> add missing word for some items (light,window,etc)

responses/fr/HassGetState.yaml, sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, sentences/fr/climate_HassClimateGetTemperature.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml, tests/fr/cover_HassGetState.yaml, tests/fr/lock_HassGetState.yaml
- Simplify response "All": all cases were not covered. Simplified by translating "not" by "pas" -Add binary_sensors.py in French (battery binary sensors as a starting point)
=> [Fr] Simplify response "All" and add binary_sensors.py with tests

sentences/de/scene_HassTurnOn.yaml, tests/de/scene_HassTurnOn.yaml
Makes commands like "Good night" possible.
=> [DE] Update to scene_HassTurnOn

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
Also add also an expansion rule "y a t-il / Il y a" as "il y a" can be use in an interrogative form in common language.
I added a lot of variations with or without dashes.Perhaps it's not required: I don't know of we have to handle dash and apostrophe in sentences.
=> [Fr] Add intents and test for CO2 binary sensors

sentences/nl/_common.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, sentences/nl/lock_HassTurnOff.yaml, sentences/nl/lock_HassTurnOn.yaml, sentences/nl/scene_HassTurnOn.yaml, sentences/nl/script_HassTurnOn.yaml, tests/nl/cover_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml, tests/nl/lock_HassTurnOff.yaml, tests/nl/lock_HassTurnOn.yaml, tests/nl/scene_HassTurnOn.yaml, tests/nl/script_HassTurnOn.yaml
Add optional space to allow recognition where STT will not add it, eg `kan je het bedlampje uitdoen`
=> Add optional space

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
=> [Fr] Add cold and connectivity binary sensors

responses/de/HassTurnOff.yaml, responses/de/HassTurnOn.yaml, sentences/de/fan_HassTurnOff.yaml, sentences/de/fan_HassTurnOn.yaml, tests/de/fan_HassTurnOff.yaml, tests/de/fan_HassTurnOn.yaml
Response checks for fans have been missing.
=> [DE] Fix fan responses

responses/fr/HassLightSet.yaml, sentences/fr/_common.yaml, sentences/fr/light_HassLightSet.yaml, tests/fr/light_HassLightSet.yaml
Allow setting brightness by name, area or name + area.
I also simplified the response to be consistent with english responses and improve response time.
Tests have been updated for responses
=> [FR] Add more sentences for HassLightSet

responses/fr/HassTurnOff.yaml, responses/fr/HassTurnOn.yaml, sentences/fr/_common.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Allow turning on and off all lights or per area.
Tests has been simplified to avoid test duplicate.
I also simplified the response to be consistent with english responses and improve response time.
Tests have been updated for responses
=> [FR] Add more sentences for HassLightTurnOn and HassLightTurnOff

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml
Might be discussed:
There are multiple interrogative forms of "être" according to singular/plural and gender.
For the time being, I added it only in binary_sensors_HassGetState.
Note:  I also split a few sentences in binary_sensors_HassGetState for more clarity
=> [fr] add a new expansion rule <sontils>

sentences/pl/climate_HassClimateGetTemperature.yaml, sentences/pl/climate_HassClimateSetTemperature.yaml, sentences/pl/homeassistant_HassTurnOff.yaml, sentences/pl/homeassistant_HassTurnOn.yaml, sentences/pl/script_HassTurnOn.yaml, tests/pl/climate_HassClimateGetTemperature.yaml, tests/pl/script_HassTurnOn.yaml
[PL] Added some missing sentences with tests and removed redundant default response keys
=> [PL] Added some missing sentences with tests and removed redundant default response keys

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
- door
- garage door
- gas
- heat
- light
- lock
All with validated tests
+ A few adjustments in previous binary sensors
=> [fr] add new intents in binary_sensors_HassGetState

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
- binary sensor moisture
- binary sensor motion
+ a few adjustments on existing binary sensors intents
with tests
Improves and adds expansion rules - see [[#1330]](https://github.com/home-assistant/intents/pull/1330)
=> [fr] adds intents for binary senors moisture ans motion + expansion rule changes

sentences/pl/_common.yaml, sentences/pl/scene_HassTurnOn.yaml, sentences/pl/script_HassTurnOn.yaml, tests/pl/scene_HassTurnOn.yaml, tests/pl/script_HassTurnOn.yaml
[PL] Simplified scene/script intent sentences, added missing activation variants and tests
=> [PL] Simplified scene/script intent sentences, added missing activation variants and tests

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, sentences/fr/light_HassLightSet.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml, tests/fr/light_HassLightSet.yaml
binary sensor device classes:
- occupancy
- opening
- window
New intents in HassLightSet with words ("augmente / baisse")
=> [fr] adds intents for binary sensors and HassLightSet

sentences/zh-tw/_common.yaml
=> [zh-tw] Update respond on _common.yaml

sentences/zh-tw/_common.yaml
Add more option words may use.
=> [zh-tw] Update _common.yaml

sentences/en/homeassistant_HassGetState.yaml, tests/en/homeassistant_HassGetState.yaml
And optional switched|turned|set language
=> [EN] Add (switched|turned|set) to `all` question on `on_off_domains`

sentences/el/homeassistant_HassGetState.yaml
=> [el] fix typo in homeassistant_HassGetState

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
- plug
- power
- presence
- problem
- running
- safety
- smoke
- sound
- tamper
- update
- vibration
=> [fr] add last intents and tests for binary_sensors

sentences/de/_common.yaml, sentences/de/light_HassTurnOff.yaml, sentences/de/light_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml
Use more expansion rules for the lights and add some more commands including tests.
=> [DE] small improvements to lights

sentences/en/homeassistant_HassGetState.yaml, tests/en/homeassistant_HassGetState.yaml
"What is the value of X?"
"What is the current state of X?"
=> Add more flexible wording to generic HassGetState

sentences/fr/homeassistant_HassGetState.yaml, tests/fr/homeassistant_HassGetState.yaml
Add new sentences
Fix "donne moi" by adding a match on "donne-moi"
Implement existing expansion rules
=> [Fr] A few adjustments in homeassistant_hassgetState

sentences/ko/_common.yaml
Add a list of commonly used words.
=> [KO] Update _common.yaml

responses/ko/HassTurnOff.yaml, responses/ko/HassTurnOn.yaml, sentences/ko/_common.yaml, sentences/ko/lock_HassTurnOff.yaml, sentences/ko/lock_HassTurnOn.yaml, tests/ko/_fixtures.yaml, tests/ko/cover_HassTurnOn.yaml, tests/ko/lock_HassTurnOff.yaml, tests/ko/lock_HassTurnOn.yaml
=> [KO] Add lock entities

responses/ko/HassGetState.yaml, sentences/ko/_common.yaml, sentences/ko/cover_HassGetState.yaml, sentences/ko/homeassistant_HassGetState.yaml, sentences/ko/lock_HassGetState.yaml, tests/ko/_fixtures.yaml, tests/ko/cover_HassGetState.yaml, tests/ko/homeassistant_HassGetState.yaml, tests/ko/lock_HassGetState.yaml
Add HassGetState sentence and response
=> [KO] Add HassGetState sentence and response

responses/ko/HassGetState.yaml, tests/ko/binary_sensor_HassGetState.yaml, tests/ko/cover_HassGetState.yaml, tests/ko/lock_HassGetState.yaml
=> [KO] Updated missing spaces

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml
There was no reference to areas in the generic homeassistant_turn_on and homeassistant_turn_off intents.
This has been fixed now.
Fixes https://github.com/home-assistant/intents/issues/1430
=> [NL] Add area to generic turn on and off

sentences/te/light_HassTurnOff.yaml, sentences/te/light_HassTurnOn.yaml, tests/te/light_HassTurnOff.yaml, tests/te/light_HassTurnOn.yaml
Added sentence to Turn on/off Light
=> [te] Light on/Off for Telugu language

responses/nb/HassLightSet.yaml, responses/nb/HassTurnOff.yaml, responses/nb/HassTurnOn.yaml, sentences/nb/_common.yaml, sentences/nb/binary_sensor_HassGetState.yaml, sentences/nb/fan_HassTurnOff.yaml, sentences/nb/fan_HassTurnOn.yaml, sentences/nb/homeassistant_HassTurnOff.yaml, sentences/nb/homeassistant_HassTurnOn.yaml, sentences/nb/light_HassLightSet.yaml, sentences/nb/light_HassTurnOff.yaml, sentences/nb/light_HassTurnOn.yaml, sentences/nb/lock_HassTurnOff.yaml, sentences/nb/lock_HassTurnOn.yaml, tests/nb/_fixtures.yaml, tests/nb/binary_sensor_HassGetState.yaml, tests/nb/fan_HassTurnOff.yaml, tests/nb/fan_HassTurnOn.yaml, tests/nb/light_HassLightSet.yaml, tests/nb/light_HassTurnOff.yaml, tests/nb/light_HassTurnOn.yaml, tests/nb/lock_HassTurnOff.yaml, tests/nb/lock_HassTurnOn.yaml
Sorry for a _very_ large PR. But this PR is using `en` as a template and I added all the missing pieces. Probably cases this PR doesn't cover, but that can be fixed later. What's important now is to get `nb` (Norwegian Bokmål) up to date.
Also did a cleanup to remove some `unused` warnings.
=> [NB] Add binary sensors and locks

responses/is/HassGetState.yaml, responses/is/HassLightSet.yaml, responses/is/HassTurnOff.yaml, responses/is/HassTurnOn.yaml, sentences/is/_common.yaml, sentences/is/cover_HassGetState.yaml, sentences/is/cover_HassTurnOff.yaml, sentences/is/cover_HassTurnOn.yaml, sentences/is/light_HassLightSet.yaml, tests/is/_fixtures.yaml, tests/is/cover_HassGetState.yaml, tests/is/cover_HassTurnOff.yaml, tests/is/cover_HassTurnOn.yaml, tests/is/light_HassLightSet.yaml
- Added ways to turn light on and off
- Added ways to change color and brightness
- Added on/off and get state for covers
=> [IS] Improve lights add setters and add covers

sentences/ro/_common.yaml, sentences/ro/binary_sensor_HassGetState.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, sentences/ro/cover_HassGetState.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/homeassistant_HassGetState.yaml, sentences/ro/light_HassGetState.yaml, sentences/ro/lock_HassGetState.yaml, tests/ro/binary_sensor_HassGetState.yaml
After local expansion rules and permutations, the `binary_sensor` domain was made easier to maintain.
Also, some minor optimizations of expansion rules
=> [RO] Binary sensors refactoring

responses/fr/HassShoppingListAddItem.yaml, sentences/fr/_common.yaml, sentences/fr/shopping_list_HassShoppingListAddItem.yaml, tests/fr/shopping_list_HassShoppingListAddItem.yaml
add french translation for  the shopping list handling (Sentences, response, tests)
=> [Fr] Add shopping list translation

responses/de-CH/HassShoppingListAddItem.yaml, sentences/de-CH/_common.yaml, sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml, tests/de-CH/shopping_list_HassShoppingListAddItem.yaml
=> [de-CH] Add HassShoppingListAddItem

responses/ro/HassShoppingListAddItem.yaml, sentences/ro/_common.yaml, sentences/ro/shopping_list_HassShoppingListAddItem.yaml, tests/ro/shopping_list_HassShoppingListAddItem.yaml
Added HassShoppingListAddItem to the list of supported intents
=> [RO] Added HassShoppingListAddItem

responses/nl/HassShoppingListAddItem.yaml, sentences/nl/_common.yaml, sentences/nl/shopping_list_HassShoppingListAddItem.yaml, tests/nl/shopping_list_HassShoppingListAddItem.yaml
Add new shopping list intent to Dutch
=> [NL] Add shopping list intent

responses/ko/HassGetState.yaml, responses/ko/HassShoppingListAddItem.yaml, sentences/ko/_common.yaml, sentences/ko/shopping_list_HassShoppingListAddItem.yaml, tests/ko/shopping_list_HassShoppingListAddItem.yaml
=> [KO] Add shopping list sentences

responses/ro/HassGetState.yaml, sentences/ro/_common.yaml, sentences/ro/binary_sensor_HassGetState.yaml, tests/ro/binary_sensor_HassGetState.yaml, tests/ro/light_HassGetState.yaml, tests/ro/lock_HassGetState.yaml
Added sentences for various `device_class`es to answer:
- is there any _class_ with _state_
- do all devices _class_ have _state_
- which _class_ devices have _state_
- how many _class_ devices have _state_
=> [RO] Binary sensors extra

responses/sv/HassShoppingListAddItem.yaml, sentences/sv/_common.yaml, sentences/sv/shopping_list_HassShoppingListAddItem.yaml, tests/sv/shopping_list_HassShoppingListAddItem.yaml
Added support for adding items to the shopping list in Swedish.
=> Added shopping list sentences in Swedish

responses/ca/HassShoppingListAddItem.yaml, responses/ca/HassTurnOn.yaml, sentences/ca/_common.yaml, sentences/ca/scene_HassTurnOn.yaml, sentences/ca/script_HassTurnOn.yaml, sentences/ca/shopping_list_HassShoppingListAddItem.yaml, tests/ca/_fixtures.yaml, tests/ca/scene_HassTurnOn.yaml, tests/ca/script_HassTurnOn.yaml, tests/ca/shopping_list_HassShoppingListAddItem.yaml
Adds support for:
- shopping list
- scenes
- scripts
=> [ca] Add new shopping list, scripts and scenes

responses/es/HassShoppingListAddItem.yaml, sentences/es/_common.yaml, sentences/es/shopping_list_HassShoppingListAddItem.yaml, tests/es/shopping_list_HassShoppingListAddItem.yaml
Adds support for shopping list voice commands in Spanish
=> [es] Adds support for shopping list voice commands

sentences/de/light_HassTurnOff.yaml, sentences/de/light_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml
"Licht an im Wohnzimmer"
"Licht aus in der Küche"
=> Add short forms for light onOff with area at the end

responses/fr/HassTurnOff.yaml, responses/fr/HassTurnOn.yaml, sentences/fr/_common.yaml, sentences/fr/lock_HassTurnOff.yaml, sentences/fr/lock_HassTurnOn.yaml, tests/fr/lock_HassTurnOff.yaml, tests/fr/lock_HassTurnOn.yaml
Add lock_HassTurnOff and lock_HassTurnOn with tests and responses
=> [Fr] Add lock_HassTurnOff and lock_HassTurnOn

responses/cs/HassShoppingListAddItem.yaml, sentences/cs/_common.yaml, sentences/cs/shopping_list_HassShoppingListAddItem.yaml, tests/cs/shopping_list_HassShoppingListAddItem.yaml
Add new shopping lists intents in Czech.
=> [cs] Add shopping list intents

responses/nl/HassGetState.yaml
Add default response for HassGetState (for custom intents)
See #1512
=> [NL] Add default response for HassGetState

sentences/nl/_common.yaml, sentences/nl/sensor_HassGetState.yaml, tests/nl/_fixtures.yaml, tests/nl/sensor_HassGetState.yaml
Added sentences to get sensors by name for (almost) all `device_class`es from here https://www.home-assistant.io/integrations/sensor/
Based on #1451
=> [NL] HassGetState for sensors using device_class

sentences/ro/homeassistant_HassNevermind.yaml, tests/ro/homeassistant_HassNevermind.yaml
=> [RO] Nevermind

sentences/de/homeassistant_HassNevermind.yaml, tests/de/homeassistant_HassNevermind.yaml
Add German support for a future HA intent: `HassNevermind` (see #1549).
=> [DE] Add HassNevermind

responses/hr/HassTurnOn.yaml, sentences/hr/scene_HassTurnOn.yaml, sentences/hr/script_HassTurnOn.yaml, tests/hr/_fixtures.yaml, tests/hr/scene_HassTurnOn.yaml, tests/hr/script_HassTurnOn.yaml
Added Croatian language for scripts and scenes
=> (hr) Scene and Script Croatian sentences

responses/nb/HassTurnOff.yaml, responses/nb/HassTurnOn.yaml, tests/nb/homeassistant_HassTurnOff.yaml, tests/nb/homeassistant_HassTurnOn.yaml
This PR will fix "Slo av light" and similar.
From a FB group:
=> Fix missing NB translations

responses/hr/HassShoppingListAddItem.yaml, sentences/hr/_common.yaml, sentences/hr/shopping_list_HassShoppingListAddItem.yaml, tests/hr/shopping_list_HassShoppingListAddItem.yaml
[hr] added shopping list support
=> [hr] added shopping list support

responses/sv/HassTurnOff.yaml, responses/sv/HassTurnOn.yaml, sentences/sv/light_HassTurnOff.yaml, sentences/sv/light_HassTurnOn.yaml, tests/sv/_fixtures.yaml, tests/sv/light_HassTurnOff.yaml, tests/sv/light_HassTurnOn.yaml
Added possibility to turn on and off individual lights in a given area in swedish.
=> [sv] possibility to turn on and off individual lights

responses/es/HassGetState.yaml, responses/es/HassNevermind.yaml, sentences/es/_common.yaml, sentences/es/homeassistant_HassGetState.yaml, sentences/es/homeassistant_HassNevermind.yaml, sentences/es/sensor_HassGetState.yaml, tests/es/_fixtures.yaml, tests/es/climate_HassClimateGetTemperature.yaml, tests/es/homeassistant_HassGetState.yaml, tests/es/homeassistant_HassNevermind.yaml, tests/es/sensor_HassGetState.yaml
Spanish lenguage addons:
- homeassistant_HassNevermind and sensor_HassGetState sentences and test.
- Add some response tests to climate_HassClimateGetTemperature.
- Improvements _common and HassGetState files to allow more natural language.
=> Spanish lenguage improvements

sentences/en/lock_HassTurnOff.yaml, sentences/en/lock_HassTurnOn.yaml, tests/en/lock_HassTurnOff.yaml, tests/en/lock_HassTurnOn.yaml
Some more sentence variety. Added test sentences as examples.
=> [en] Allow singular use of lock or door for lock and unlock

sentences/en/lock_HassGetState.yaml, tests/en/lock_HassGetState.yaml
This will cover phrases like "Are there any unlocked doors?" or "Is any door unlocked?".
=> [en] Extend lock HassGetState sentences with some alternatives

responses/pt/HassNevermind.yaml, sentences/pt/homeassistant_HassNevermind.yaml, tests/pt/homeassistant_HassNevermind.yaml
Add pt-pt support for HA intent: `HassNevermind` (see #1549).
=> [PT] Add HassNevermind

sentences/de/_common.yaml, sentences/de/binary_sensor_HassGetState.yaml
Change naming of co-sensor to co_sensor as requested in #1577
=> [DE] Change naming of co-sensor

responses/pt/HassClimateSetTemperature.yaml, responses/pt/HassGetState.yaml, responses/pt/HassLightSet.yaml, responses/pt/HassTurnOff.yaml, responses/pt/HassTurnOn.yaml, sentences/pt/homeassistant_HassTurnOff.yaml, sentences/pt/homeassistant_HassTurnOn.yaml, tests/pt/climate_HassClimateSetTemperature.yaml, tests/pt/homeassistant_HassGetState.yaml, tests/pt/homeassistant_HassTurnOff.yaml, tests/pt/homeassistant_HassTurnOn.yaml
Make the responses simpler "Turned off" instead of "X turned off", following the guidelines.
Also use the word "Set" instead of "Changed" for brightness and color.
=> [PT] Simplify responses + remove redundant sentences

sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml, tests/test_language_intents.py
Add support for sentence "**_Allume la lumière du salon à 10%_**"
and fix error `homeassistant.helpers.intent.IntentHandleError: No area named all` for sentence "**_Éteint toutes les lumières_**"
=> [fr] add new sentence control brightness and fix all areas

requirements.txt
New hassil features:
- Numbers to words for many languages using [unicode-rbnf](https://github.com/rhasspy/unicode-rbnf)
- Sort wildcard sentences by number of literal text chunks
=> Bump hassil to 1.4.0

requirements.txt
Adds fuzzy matching using edit distance
=> Bump to hassil 1.5.0

intents.yaml, responses/en/HassListAddItem.yaml, sentences/en/todo_HassListAddItem.yaml, tests/en/_fixtures.yaml, tests/en/todo_HassListAddItem.yaml
Adds a new intent: `HassListAddItem` that lets you add something to a to-do list by name ("add beer to my Trader Joe's list").
=> Add HassListAddItem intent

responses/ro/HassListAddItem.yaml, sentences/ro/todo_HassListAddItem.yaml, tests/ro/_fixtures.yaml, tests/ro/todo_HassListAddItem.yaml
Added `todo_HassListAddItem` as per #1626
=> [RO] Added todo_HassListAddItem

responses/ro/HassGetWeather.yaml, sentences/ro/weather_HassGetWeather.yaml, tests/ro/_fixtures.yaml, tests/ro/weather_HassGetWeather.yaml
Added `weather_HassGetWeather` according to #1627
"cum e vremea?"
"cat de cald este la Bucuresti?"
"cate grade sunt afara?"
=> [RO] Add HassGetWeather

responses/ro/HassGetState.yaml, sentences/ro/_common.yaml, sentences/ro/person_HassGetState.yaml, tests/ro/_fixtures.yaml, tests/ro/person_HassGetState.yaml
Add person_HassGetState according to #1613
Encountered [two](https://github.com/home-assistant/hassil/issues/83) hassil [bugs](https://github.com/home-assistant/hassil/issues/84) but the tests should be unaffected after fixing the bugs
"unde e Mihai?"
"este la serviciu Mihai?"
"este toata lumea acasa?"
"cine este acasa?"
"cate persoane sunt acasa?"
=> [RO] Add person_HassGetState

responses/fr/HassGetState.yaml, responses/fr/HassGetWeather.yaml, responses/fr/HassListAddItem.yaml, sentences/fr/_common.yaml, sentences/fr/person_HassGetState.yaml, sentences/fr/sensor_HassGetState.yaml, sentences/fr/shopping_list_HassShoppingListAddItem.yaml, sentences/fr/todo_HassListAddItem.yaml, sentences/fr/weather_HassGetWeather.yaml, tests/fr/_fixtures.yaml, tests/fr/person_HassGetState.yaml, tests/fr/sensor_HassGetState.yaml, tests/fr/todo_HassListAddItem.yaml, tests/fr/weather_HassGetWeather.yaml
Including new expansion rule <What...>
Add default response in HassGetState responses
For the time being, the first 2 classes translated
=> [Fr] sensor_HassGetState

responses/de/HassGetWeather.yaml, sentences/de/weather_HassGetWeather.yaml, tests/de/_fixtures.yaml, tests/de/weather_HassGetWeather.yaml
=> [DE] HassGetWeather

responses/nl/HassListAddItem.yaml, responses/nl/HassShoppingListAddItem.yaml, sentences/nl/todo_HassListAddItem.yaml, tests/nl/_fixtures.yaml, tests/nl/shopping_list_HassShoppingListAddItem.yaml, tests/nl/todo_HassListAddItem.yaml
=> [NL] ToDo add item intent

responses/cs/HassGetState.yaml, responses/cs/HassTurnOn.yaml, sentences/cs/_common.yaml, sentences/cs/scene_HassTurnOn.yaml, tests/cs/_fixtures.yaml, tests/cs/scene_HassTurnOn.yaml
Add scene support for Czech language
=> [cs] Add scene support

sentences/fr/homeassistant_HassNevermind.yaml, tests/fr/homeassistant_HassNevermind.yaml
homeassistant_HassNevermind.yaml
=> [FR] Add homeassistant_HassNevermind.yaml

sentences/fr/_common.yaml, sentences/fr/sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/sensor_HassGetState.yaml
Atmospheric pressure
Battery
CO2
CO
Current
Data rate
Data size
=> [FR] Add translation for more device classes in sensor_HassGetState

responses/nl/HassGetWeather.yaml, sentences/nl/weather_HassGetWeather.yaml, tests/nl/_fixtures.yaml, tests/nl/weather_HassGetWeather.yaml
=> [NL] Add HassGetWeather

sentences/uk/_common.yaml
=> [UK] New colours, brightness, locks and binary sensors were added.

sentences/fr/_common.yaml, sentences/fr/sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/sensor_HassGetState.yaml
date, distance
duration, energy
energy storage, frequency
gas, humidity
illuminance, irradiance
=> [FR] New device classes translation

sentences/sl/_common.yaml
fixed small typo in area where bedroom (spalnica) is recongnized in different inclination.
=> fixed typo in area in common.yaml

responses/ro/HassClimateGetTemperature.yaml, sentences/ro/_common.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, tests/ro/_fixtures.yaml, tests/ro/climate_HassClimateGetTemperature.yaml
=> [RO] HassClimateGetTemperature attribute fix

responses/cs/HassListAddItem.yaml, sentences/cs/todo_HassListAddItem.yaml, tests/cs/_fixtures.yaml, tests/cs/todo_HassListAddItem.yaml
=> [cs] Add todo domain (HassListAddItem) sentences

sentences/sl/homeassistant_HassNevermind.yaml, tests/sl/homeassistant_HassNevermind.yaml
Added Slovenian translation for homeassistant_HassNevermind.yaml
=> [SL] added Nevermind sentences and tests

responses/sl/HassShoppingListAddItem.yaml, sentences/sl/_common.yaml, sentences/sl/shopping_list_HassShoppingListAddItem.yaml, tests/sl/shopping_list_HassShoppingListAddItem.yaml
Slovenian translation for shopping lists
=> [SL] added shopping_list_HassShoppingListAddItem.yaml, sentences and tests, response, common fixed

sentences/sl/scene_HassTurnOn.yaml, tests/sl/scene_HassTurnOn.yaml
Added Slovenian translation for sceneHassTurnOn.
=> [SL] added sceneHassTurnOn.yaml, sentence and tests

sentences/sl/script_HassTurnOn.yaml, tests/sl/script_HassTurnOn.yaml
Added Slovenian sentence, test, response for script_HassTurnOn
=> [SL] added script_HassTurnOn, sentence and test, response

responses/sl/HassGetWeather.yaml, sentences/sl/_common.yaml, sentences/sl/weather_HassGetWeather.yaml, tests/sl/_fixtures.yaml, tests/sl/weather_HassGetWeather.yaml
Added Slovenian translation - sentences, responses, tests, fixed common, fixtures
=> [SL] added weather_HassGetWeather

responses/sl/HassListAddItem.yaml, sentences/sl/todo_HassListAddItem.yaml, tests/sl/_fixtures.yaml, tests/sl/todo_HassListAddItem.yaml
Added Slovenian sentence, response, test for HassListAddItem
=> [SL] added HassListAddItem, sentence, test, response, amended fixtures

responses/sl/HassGetState.yaml, sentences/sl/_common.yaml, sentences/sl/person_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/person_HassGetState.yaml
Added Slovenian sentences, test for person_HassGetState.yaml 
- amended common (added binary sensor for presence, zone)
- amended fixtures accordingly
- amended responses file for *where* sentence
=> [SL] added person_HassGetState, sentences etc

responses/sl/HassTurnOn.yaml, sentences/sl/_common.yaml, sentences/sl/lock_HassGetState.yaml, sentences/sl/lock_HassTurnOff.yaml, sentences/sl/lock_HassTurnOn.yaml, tests/sl/_fixtures.yaml, tests/sl/lock_HassGetState.yaml, tests/sl/lock_HassTurnOff.yaml, tests/sl/lock_HassTurnOn.yaml
Added Slovenian sentences, tests, responses for 
- lock_HassGetState
- lockHassTunOn
- lock_HassTurnOff
- amended common.yaml, fixtures.yaml and responses
=> [SL] added lock_HassGetState, lock_HassTurnOn, lock_HassTurnOff

sentences/ro/weather_HassGetWeather.yaml, tests/ro/weather_HassGetWeather.yaml
=> [RO] Fix weather without name

sentences/fr/lock_HassTurnOff.yaml, sentences/fr/lock_HassTurnOn.yaml, sentences/fr/sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/sensor_HassGetState.yaml
+ a small addition in lock files
=> [FR] Add device classes translation in sensor_HassGetState

sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
=> [RO] Fix context area for lights

sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
* Use same pattern for turning off and on lights in area.
* Lights in area should not be toggled by plain "zapnout area".
=> [cs] Minor improvements/fixes for lights area intents

responses/et/HassTurnOff.yaml, responses/et/HassTurnOn.yaml, tests/et/homeassistant_HassTurnOff.yaml, tests/et/homeassistant_HassTurnOn.yaml
Translated from English to Estonian.
=> [ET] Fixed two translations

responses/sl/HassClimateGetTemperature.yaml, responses/sl/HassGetState.yaml, responses/sl/HassNevermind.yaml, sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, sentences/sl/cover_HassTurnOn.yaml, sentences/sl/todo_HassListAddItem.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml, tests/sl/cover_HassGetState.yaml, tests/sl/cover_HassTurnOff.yaml, tests/sl/cover_HassTurnOn.yaml, tests/sl/lock_HassGetState.yaml, tests/sl/person_HassGetState.yaml, tests/sl/shopping_list_HassShoppingListAddItem.yaml, tests/sl/todo_HassListAddItem.yaml
Added Slovenian sentences, tests for binary sensors - 1st part
=> [SL] added binary sensors  - partly, sentences,, tests, amended fixtures and common, responses

responses/de-CH/HassListAddItem.yaml, responses/de-CH/HassShoppingListAddItem.yaml, sentences/de-CH/_common.yaml, sentences/de-CH/climate_HassClimateGetTemperature.yaml, sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml, sentences/de-CH/todo_HassListAddItem.yaml, tests/de-CH/_fixtures.yaml, tests/de-CH/shopping_list_HassShoppingListAddItem.yaml, tests/de-CH/todo_HassListAddItem.yaml
Slight adjustment of GetTemperature-sentences
=> [de-CH] slight adjustment of GetTemperature

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translation for binary sensors for gas.
=> [SL] binary sensor for gas added

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Slovenian sentences, tests added for binary sensor for heat and light
=> [SL] binary sensors heat, light

sentences/de/homeassistant_HassNevermind.yaml, tests/de/homeassistant_HassNevermind.yaml
I've added 'nichts' as an option to the HassNevermind intent, as it is a valid "nevermind-sentence" in other voice assistants like Siri
ChrM3r
=> [DE] added 'nichts' as an option for HassNevermind

responses/gl/HassClimateGetTemperature.yaml, responses/gl/HassClimateSetTemperature.yaml, responses/gl/HassGetWeather.yaml, sentences/gl/weather_HassGetWeather.yaml, tests/gl/_fixtures.yaml, tests/gl/weather_HassGetWeather.yaml
Adds weather related sentences for Galician
=> [GL] Add weather sentences

responses/sl/HassLightSet.yaml, responses/sl/HassTurnOff.yaml, sentences/sl/_common.yaml, sentences/sl/climate_HassClimateGetTemperature.yaml, sentences/sl/light_HassLightSet.yaml, sentences/sl/light_HassTurnOff.yaml, sentences/sl/light_HassTurnOn.yaml, tests/sl/_fixtures.yaml, tests/sl/climate_HassClimateGetTemperature.yaml, tests/sl/light_HassLightSet.yaml, tests/sl/light_HassTurnOff.yaml, tests/sl/light_HassTurnOn.yaml
Fixed sentences and test for lights and climate
Added sentence for lights in the same area as a satellite device
=> [SL] lights, climate fixed

responses/en/HassGetState.yaml, responses/en/HassGetWeather.yaml, sentences/en/_common.yaml, sentences/en/person_HassGetState.yaml, tests/en/_fixtures.yaml, tests/en/person_HassGetState.yaml, tests/en/weather_HassGetWeather.yaml
Depends on https://github.com/home-assistant/core/pull/105524
=> [EN] Fix intents with untranslated state

responses/ro/HassGetState.yaml, responses/ro/HassGetWeather.yaml, sentences/ro/_common.yaml, sentences/ro/person_HassGetState.yaml, tests/ro/_fixtures.yaml, tests/ro/person_HassGetState.yaml
Depends on https://github.com/home-assistant/core/pull/105524
=> [RO] Fix intents with untranslated state

responses/de/HassGetState.yaml, responses/de/HassGetWeather.yaml, sentences/de/_common.yaml, sentences/de/person_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/person_HassGetState.yaml
As requested by @tetele in https://github.com/home-assistant/intents/discussions/1768#discussioncomment-7830669
based on https://github.com/home-assistant/intents/pull/1767
waiting for: https://github.com/home-assistant/core/pull/105524
=> [DE] Fix intents with untranslated states

responses/es/HassGetState.yaml, responses/es/HassGetWeather.yaml, sentences/es/_common.yaml, sentences/es/person_HassGetState.yaml, tests/es/_fixtures.yaml, tests/es/person_HassGetState.yaml, tests/es/weather_HassGetWeather.yaml
Depends on https://github.com/home-assistant/core/pull/105524
=> [ES] Fix intents with untranslated state

responses/pl/HassGetState.yaml, responses/pl/HassGetWeather.yaml, sentences/pl/_common.yaml, sentences/pl/person_HassGetState.yaml, sentences/pl/weather_HassGetWeather.yaml, tests/pl/_fixtures.yaml, tests/pl/homeassistant_HassNevermind.yaml, tests/pl/person_HassGetState.yaml, tests/pl/weather_HassGetWeather.yaml
**WARNING**
This pull request contains more than just ported and translated changes from #1767, as some sentences where missing from PL version I've decided to also implement them in the same PR to avoid pushing half broken version to the repository.
I would really appreciate if any other Polish speaker would sanity check all the changes, this is more than I've initially intended but this is what had to be done in order to implement changes.
@witold-gren , @dziadeck47 , @Misiu, @fejrr, @panpawelgit
=> [PL] Fix intents with untranslated state (#1767) AND MORE

sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
=> [NL] Turn lights on/off in the area of a satellite

responses/nl/HassGetState.yaml, responses/nl/HassGetWeather.yaml, sentences/nl/_common.yaml, sentences/nl/person_HassGetState.yaml, tests/nl/_fixtures.yaml, tests/nl/person_HassGetState.yaml
As requested by @tetele in https://github.com/home-assistant/intents/discussions/1768#discussioncomment-7830669
based on https://github.com/home-assistant/intents/pull/1767
waiting for: https://github.com/home-assistant/core/pull/105524
=> [NL] Fix intents with untranslated states

responses/pt/HassGetWeather.yaml, tests/pt/_fixtures.yaml, tests/pt/weather_HassGetWeather.yaml
=> [PT] Fix weather intents with untranslated state

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translation for binary sensor - occupancy
=> [SL] binary sensors - occupancy added

responses/sl/HassGetState.yaml, sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian sentences for binary sensors - opening and plug
Modified connectivity binary sensor from "priključen" to "povezan"
=> [SL] added opening and plug, modified connectivity

sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
See https://github.com/home-assistant/intents/issues/1815
=> [Fr] light with satellite intents

responses/gl/HassListAddItem.yaml, sentences/gl/todo_HassListAddItem.yaml, tests/gl/_fixtures.yaml, tests/gl/todo_HassListAddItem.yaml
Adding ListAddItem sentences, responses and tests for Galician.
=> [GL] ListAddItem sentences

sentences/gl/homeassistant_HassNevermind.yaml, tests/gl/homeassistant_HassNevermind.yaml
Added nevermind sentences and tests
=> [GL] Nevermind sentences

sentences/nb/_common.yaml, sentences/nb/sensor_HassGetState.yaml, tests/nb/_fixtures.yaml, tests/nb/sensor_HassGetState.yaml
This PR includes an initial draft for the Norwegian translation of the `what_is_the_class_of_name` expansion rule used in the english version of sensor_HassGetSensor.
=> [NB] Initial HassGetSensor for humidity & battery

sentences/nl/shopping_list_HassShoppingListAddItem.yaml, sentences/nl/todo_HassListAddItem.yaml, tests/nl/shopping_list_HassShoppingListAddItem.yaml, tests/nl/todo_HassListAddItem.yaml
Add `mijn`, `m'n`, `ons` and `onze`
=> [NL] Add additional pronouns to list intents

responses/nl/HassClimateGetTemperature.yaml, sentences/nl/climate_HassClimateGetTemperature.yaml, tests/nl/_fixtures.yaml, tests/nl/climate_HassClimateGetTemperature.yaml
Make changes for NL intents to get the current temperature from a climate entity
=> [NL] Update ClimateGetTemperature

script/intentfest/validate.py
Make validate work proper encoding="utf8"
=> add  utf8 encoding option on validate.py

sentences/de/light_HassTurnOff.yaml, sentences/de/light_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml
I've tried to adopt the area awareness part of the english version. Therefor we have to differentiate more between "lichter" and "alle_lichter".
=> [DE] Add sentences for turning lights on/off in the area of a satellite device

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translations for binary sensor - presence and power
=> [SL] added presence and power for binary sensor

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translation for binary sensors for problem and running
=> [SL] added binary sensor - problem, running

sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translation for binary sensors:
- safety
- smoke
- sound
- tamper
=> [SL] binary sensor - safety, smoke, sound, tamper

responses/sl/HassGetState.yaml, sentences/sl/_common.yaml, sentences/sl/binary_sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/binary_sensor_HassGetState.yaml
Added Slovenian translation for binary sensors:
- update
- vibration
- window
=> [SL] added binary sensors - update, vibration, window

sentences/sl/_common.yaml, sentences/sl/sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/sensor_HassGetState.yaml
Added Slovenian translation for AQI sensor.
=> [SL] sensor added for AQI

sentences/es/_common.yaml, sentences/es/cover_HassTurnOff.yaml, sentences/es/cover_HassTurnOn.yaml, sentences/es/fan_HassTurnOff.yaml, sentences/es/fan_HassTurnOn.yaml, sentences/es/light_HassLightSet.yaml, sentences/es/light_HassTurnOff.yaml, sentences/es/light_HassTurnOn.yaml, tests/es/cover_HassTurnOff.yaml, tests/es/cover_HassTurnOn.yaml, tests/es/fan_HassTurnOff.yaml, tests/es/fan_HassTurnOn.yaml, tests/es/light_HassLightSet.yaml, tests/es/light_HassTurnOff.yaml, tests/es/light_HassTurnOn.yaml
Updating Spanish translation, translating changes from: #1785 and #1865
=> [ES] Updating translations

sentences/ro/_common.yaml
=> [RO] Migrate errors

sentences/hu/_common.yaml
The previous one became problematic after the merge.
=> [HU] Migrate errors

CODEOWNERS, languages.yaml
@v1k70rk4 applied as the second language leader for Hungarian with [a multitude](https://github.com/home-assistant/intents/pulls?q=is%3Apr+author%3Av1k70rk4+is%3Aclosed) of PRs already merged and a lot of helpful discussions, both here and on Discord.
Initial application [on Discord](https://discord.com/channels/330944238910963714/1054846248374505572/1200096788766531584)
@synesthesiam could you add him?
=> [HU] second language leader

sentences/ro/cover_HassTurnOff.yaml, sentences/ro/cover_HassTurnOn.yaml, sentences/ro/fan_HassTurnOff.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/light_HassLightSet.yaml, tests/ro/cover_HassTurnOff.yaml, tests/ro/cover_HassTurnOn.yaml, tests/ro/fan_HassTurnOff.yaml, tests/ro/fan_HassTurnOn.yaml, tests/ro/light_HassLightSet.yaml
=> [RO] Context area aware intents

sentences/nl/_common.yaml
Add missing error responses, and adjust existing ones to match the EN versions.
=> [NL] Add missing new error responses

sentences/de/_common.yaml
adopt from English all missing errors (_after #1906_)
=> [de] Add missing errors

sentences/de/_common.yaml, sentences/de/binary_sensor_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/binary_sensor_HassGetState.yaml
#1338 got closed so I'm adding the connectivity states including some more sentences and expansion rules.
=> [DE] Add binary sensor connectivity

sentences/de/_common.yaml, sentences/de/binary_sensor_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/binary_sensor_HassGetState.yaml
#1412 got closed so I'm adding the problem binary sensor.
=> [DE] Add binary sensor problem

sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Add plural form because some STT writes "Jour" as "Jours" because it's only one word. WDYT @jlpouffier?
=> Improve light control in french

sentences/sv/_common.yaml
Added the new error messages from #1906 and added missing colors from the english
=> [SV] Translating new error messages from #1906 to Swedish and added missing colors

sentences/de-CH/_common.yaml
Implement new error responses for de-CH
=> [de-CH] add new error responses

sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
Adding a singular form of "light" to area in CS language (e.g. Turn on the light in the living room)
=> [CS] Add singular for area light

sentences/hu/homeassistant_HassSetPosition.yaml, sentences/hu/media_player_HassSetVolume.yaml, tests/hu/media_player_HassSetVolume.yaml
`<set>` -> `<numeric_value_set>` in HassSetVolume and HassSetPosition
=> [hu] bugfix

sentences/de/_common.yaml, tests/de/homeassistant_HassSetPosition.yaml, tests/de/light_HassLightSet.yaml, tests/de/media_player_HassSetVolume.yaml
Implement feedback from #1970 and create test cases for it.
=> [DE] Implement additions from #1970

responses/ru/HassMediaNext.yaml, responses/ru/HassMediaPause.yaml, responses/ru/HassMediaUnpause.yaml, responses/ru/HassSetVolume.yaml, sentences/ru/_common.yaml, sentences/ru/media_player_HassMediaNext.yaml, sentences/ru/media_player_HassMediaPause.yaml, sentences/ru/media_player_HassMediaUnpause.yaml, sentences/ru/media_player_HassSetVolume.yaml, tests/ru/_fixtures.yaml, tests/ru/media_player_HassMediaNext.yaml, tests/ru/media_player_HassMediaPause.yaml, tests/ru/media_player_HassMediaUnpause.yaml, tests/ru/media_player_HassSetVolume.yaml
=> [RU] add intents for media_player

sentences/ro/_common.yaml, sentences/ro/binary_sensor_HassGetState.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, sentences/ro/climate_HassClimateSetTemperature.yaml, sentences/ro/cover_HassGetState.yaml, sentences/ro/cover_HassTurnOff.yaml, sentences/ro/cover_HassTurnOn.yaml, sentences/ro/fan_HassTurnOff.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/homeassistant_HassGetState.yaml, sentences/ro/homeassistant_HassNevermind.yaml, sentences/ro/homeassistant_HassSetPosition.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml, sentences/ro/light_HassGetState.yaml, sentences/ro/light_HassLightSet.yaml, sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, sentences/ro/lock_HassGetState.yaml, sentences/ro/media_player_HassMediaPause.yaml, sentences/ro/media_player_HassMediaUnpause.yaml, sentences/ro/media_player_HassSetVolume.yaml, sentences/ro/scene_HassTurnOn.yaml, sentences/ro/script_HassTurnOn.yaml, sentences/ro/shopping_list_HassShoppingListAddItem.yaml
Optimized sentence template syntax to avoid double whitespaces and other performance issues.
=> [RO] Fixes and improvements

tests/test_language_intents.py
In #2003 I forgot to also update the tester that tests `sentences` folder. This fixes that.
Thanks @jlpouffier for pointing out.
=> Allow other files in intent foler too

tests/ro/light_HassGetState.yaml
=> [RO] Fix tests

responses/cs/HassGetState.yaml, sentences/cs/_common.yaml, sentences/cs/person_HassGetState.yaml, tests/cs/_fixtures.yaml, tests/cs/person_HassGetState.yaml
Adding person_HassGetState.yaml, tests and updating related files.
=> [CS] Add person state

sentences/sl/cover_HassGetState.yaml
Fixed `any` sentence in cover_HassGetState.yaml
=> [SL] cover_HassGetState fix

responses/nl/HassVacuumReturnToBase.yaml, responses/nl/HassVacuumStart.yaml, sentences/nl/vacuum_HassVacuumReturnToBase.yaml, sentences/nl/vacuum_HassVacuumStart.yaml, tests/nl/vacuum_HassVacuumReturnToBase.yaml, tests/nl/vacuum_HassVacuumStart.yaml
Add new vacuum intents for Dutch
=> [NL] Add Vacuum intents

responses/nl/HassSetPosition.yaml, responses/nl/HassTurnOff.yaml, responses/nl/HassTurnOn.yaml, sentences/nl/_common.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, sentences/nl/homeassistant_HassSetPosition.yaml, sentences/nl/light_HassLightSet.yaml, sentences/nl/valve_HassTurnOff.yaml, sentences/nl/valve_HassTurnOn.yaml, tests/nl/cover_HassTurnOff.yaml, tests/nl/cover_HassTurnOn.yaml, tests/nl/homeassistant_HassSetPosition.yaml, tests/nl/valve_HassTurnOff.yaml, tests/nl/valve_HassTurnOn.yaml
Add intents to open and close valves and change position for valves and covers.
Had to amend the cover intents as well, as they were using `slots` instead of `requires_context`, same applies to the light intents to set brightness.
=> [NL] Add intents for valve en set position

sentences/cs/_common.yaml, sentences/cs/cover_HassTurnOff.yaml, sentences/cs/cover_HassTurnOn.yaml, sentences/cs/homeassistant_HassNevermind.yaml, sentences/cs/homeassistant_HassSetPosition.yaml, sentences/cs/light_HassLightSet.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/cover_HassTurnOff.yaml, tests/cs/cover_HassTurnOn.yaml, tests/cs/homeassistant_HassNevermind.yaml, tests/cs/homeassistant_HassSetPosition.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
Based on the Discord discussion, changing intents for light turn off and on for devices in the satellite area. And adding it to the cover set position, covers and light set brightness and color (revisiting some set-light sentences that were wrong).
Adding never mind intent.
=> [CS] add and fix intents in the satellite area

sentences/ro/cover_HassSetPosition.yaml, sentences/ro/valve_HassSetPosition.yaml, tests/ro/cover_HassSetPosition.yaml, tests/ro/valve_HassSetPosition.yaml
=> [RO] HassSetPosition refactoring

responses/tr/HassTurnOn.yaml, tests/tr/cover_HassTurnOn.yaml
Fixes for https://github.com/home-assistant/intents/pull/2011
=> [tr] Fix responses

sentences/es/_common.yaml
Related to #2057, but I think this as a temporary fix.
=> [ES] Translating device classes and domains in error messages

sentences/cs/light_HassLightSet.yaml
When correcting set-color intents and implementing intents for controlling lights in the satellite area (#2036), I introduced an error. I am adding these intents back to their original state.
=> [CS] re-implement intents removed in previous PR

responses/cs/HassVacuumReturnToBase.yaml, responses/cs/HassVacuumStart.yaml, sentences/cs/vacuum_HassVacuumReturnToBase.yaml, sentences/cs/vacuum_HassVacuumStart.yaml, tests/cs/_fixtures.yaml, tests/cs/vacuum_HassVacuumReturnToBase.yaml, tests/cs/vacuum_HassVacuumStart.yaml
Adding intents for vacuum cleaner in CS
=> [CS] vacuum cleaner

sentences/it/_common.yaml
=> Update italian expansion rule for <all>

sentences/sl/sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/sensor_HassGetState.yaml
Added Slovenian translation for sensors:
- humidity
- moisture
- illuminance
- irradiance
- monetary
- nitrogen dioxide
- nitrogen monixide
=> [SL] added sensors 

sentences/sw/_common.yaml, tests/sw/_fixtures.yaml
Combination of PR's that are blocked in CI:
- https://github.com/home-assistant/intents/pull/1790
- https://github.com/home-assistant/intents/pull/1596
=> Add common/fixtures for sw

responses/ru/HassMediaPause.yaml, sentences/ru/media_player_HassMediaUnpause.yaml, tests/ru/media_player_HassMediaPause.yaml, tests/ru/media_player_HassMediaUnpause.yaml
added additional options for intents
=> [RU]Add intent options for HassMediaUnpause

sentences/sl/sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/sensor_HassGetState.yaml
Slovenian intents added for sensors:
- pressure, 
- reactive pwr, 
- signal, 
- sound, 
- speed, 
- SO2, 
- temp, 
- VOC 
- VOC parts
=> [SL] sensor intents added 

sentences/cs/cover_HassGetState.yaml, tests/cs/cover_HassGetState.yaml
The current intent is only "je garáž zavřená?" adding the alternative "je zavřená garáž?"
=> [CS) add alternative  intent to cover get state

responses/ru/HassTurnOff.yaml, responses/ru/HassTurnOn.yaml, sentences/ru/_common.yaml, tests/ru/light_HassTurnOff.yaml, tests/ru/light_HassTurnOn.yaml
The response options have been modified.
=> [RU] Improving the interaction experience

sentences/nl/media_player_HassSetVolume.yaml, tests/nl/media_player_HassSetVolume.yaml
=> [NL] Improve HassSetVolume intent

responses/ru/HassTurnOff.yaml, responses/ru/HassTurnOn.yaml, sentences/ru/light_HassTurnOff.yaml, sentences/ru/light_HassTurnOn.yaml, tests/ru/light_HassTurnOff.yaml, tests/ru/light_HassTurnOn.yaml
Adaptation of intenеs from PR #2100
=> [RU] Adding new intents for lighting control in the whole house

responses/ru/HassTurnOff.yaml, responses/ru/HassTurnOn.yaml
Determining the gender of a participle by reference to the gender of the entity's name by comparing the ending with the expected values
=> [RU]Correction of errors in the selection of participle endings

responses/sv/HassGetWeather.yaml, responses/sv/HassMediaNext.yaml, responses/sv/HassMediaPause.yaml, responses/sv/HassMediaUnpause.yaml, responses/sv/HassSetVolume.yaml, sentences/sv/_common.yaml, sentences/sv/media_player_HassMediaNext.yaml, sentences/sv/media_player_HassMediaPause.yaml, sentences/sv/media_player_HassMediaUnpause.yaml, sentences/sv/media_player_HassSetVolume.yaml, sentences/sv/weather_HassGetWeather.yaml, tests/sv/_fixtures.yaml, tests/sv/media_player_HassMediaNext.yaml, tests/sv/media_player_HassMediaPause.yaml, tests/sv/media_player_HassMediaUnpause.yaml, tests/sv/media_player_HassSetVolume.yaml, tests/sv/weather_HassGetWeather.yaml
Adding support for media control (Next, Pause, Unpaus and SetVolume)
Adding support for getting weather info
=> [SV] Add weather and media

responses/lv/HassClimateSetTemperature.yaml, responses/lv/HassGetWeather.yaml, responses/lv/HassLightSet.yaml, responses/lv/HassTurnOff.yaml, responses/lv/HassTurnOn.yaml, sentences/lv/weather_HassGetWeather.yaml, tests/lv/_fixtures.yaml, tests/lv/cover_HassTurnOff.yaml, tests/lv/cover_HassTurnOn.yaml, tests/lv/weather_HassGetWeather.yaml
Adding weather intent and some translations
=> Adding intent translations for latvian (lv)

sentences/ca/cover_HassTurnOff.yaml, sentences/ca/cover_HassTurnOn.yaml, tests/ca/cover_HassTurnOff.yaml, tests/ca/cover_HassTurnOn.yaml
Missing action to "raise and lower" the covers. This is common.
=> [ca] Update cover actions

sentences/fr/_common.yaml
Ok it's done ... I have signed the CLA
With regards
=> Issue 2148 correction

responses/ru/HassGetWeather.yaml, sentences/ru/weather_HassGetWeather.yaml, tests/ru/_fixtures.yaml, tests/ru/weather_HassGetWeather.yaml
A more natural form of response. The decimal part for integers has been removed
=> [RU] Improved weather data output for TTS processing.

sentences/en/_common.yaml, sentences/en/homeassistant_HassCancelTimer.yaml, sentences/en/homeassistant_HassDecreaseTimer.yaml, sentences/en/homeassistant_HassIncreaseTimer.yaml, sentences/en/homeassistant_HassPauseTimer.yaml, sentences/en/homeassistant_HassStartTimer.yaml, sentences/en/homeassistant_HassUnpauseTimer.yaml, tests/en/homeassistant_HassCancelTimer.yaml, tests/en/homeassistant_HassDecreaseTimer.yaml, tests/en/homeassistant_HassIncreaseTimer.yaml, tests/en/homeassistant_HassPauseTimer.yaml, tests/en/homeassistant_HassStartTimer.yaml, tests/en/homeassistant_HassUnpauseTimer.yaml
Got tired of using my own limited set of sentences :smile:
=> [EN] Add more timer sentences

responses/en/HassMediaUnpause.yaml, sentences/en/media_player_HassMediaNext.yaml, sentences/en/media_player_HassMediaPause.yaml, sentences/en/media_player_HassMediaUnpause.yaml, sentences/en/media_player_HassSetVolume.yaml, tests/en/media_player_HassMediaNext.yaml, tests/en/media_player_HassMediaPause.yaml, tests/en/media_player_HassMediaUnpause.yaml, tests/en/media_player_HassSetVolume.yaml
Lets you say things like "pause music in the kitchen".
=> Add area sentences for media intents

sentences/ro/media_player_HassMediaNext.yaml, sentences/ro/media_player_HassMediaPause.yaml, sentences/ro/media_player_HassMediaUnpause.yaml, sentences/ro/media_player_HassSetVolume.yaml, tests/ro/_fixtures.yaml, tests/ro/media_player_HassMediaNext.yaml, tests/ro/media_player_HassMediaPause.yaml, tests/ro/media_player_HassMediaUnpause.yaml, tests/ro/media_player_HassSetVolume.yaml
RO translations of #2180, #2184 and #2186
Add both implied and explicit area-aware sentences for media control
=> [RO] Add area-aware media sentences

responses/lt/HassTurnOff.yaml
Not correct translation of lights_area.
=> [LT] Update HassTurnOff.yaml

responses/ro/HassRespond.yaml, sentences/ro/homeassistant_HassRespond.yaml, tests/ro/homeassistant_HassRespond.yaml
=> [RO] HassRespond

responses/nl/HassRespond.yaml, sentences/nl/homeassistant_HassRespond.yaml, tests/nl/homeassistant_HassRespond.yaml
GitHub did some strange stuff with the first attempt (#2449) so here's another go.
Provides Dutch translations for #2448
=> [NL] New attempt for HassRespond translations

shared/__init__.py, tests/es/climate_HassClimateGetTemperature.yaml
Particularly I added masculine examples and examples that used "de la / del" instead of "en la / en el", which is also a valid way command that wasn't tested.
=> [ES] Add more sentences to test getting the temperature

sentences/nl/_common.yaml, sentences/nl/media_player_HassMediaNext.yaml, sentences/nl/media_player_HassMediaPause.yaml, sentences/nl/media_player_HassMediaUnpause.yaml, sentences/nl/media_player_HassSetVolume.yaml, tests/nl/media_player_HassMediaNext.yaml, tests/nl/media_player_HassMediaPause.yaml, tests/nl/media_player_HassMediaUnpause.yaml, tests/nl/media_player_HassSetVolume.yaml
* Make all media_player intents area aware
* add area support to all media_player intents
* add additional options to `<media_item>` expansion rule
~~Other change~~
* ~~Add `wil je` to `skip_words`. This will allow sentences like `wil je het volgende liedje opzetten`. I've noticed my kids tend to include `wil je` when they try to ask something.~~ removed for now, was causing conflicts with other intents. Will add this in a later PR
=> [NL] Improvements media_player intents

responses/ca/HassRespond.yaml, sentences/ca/homeassistant_HassRespond.yaml, tests/ca/homeassistant_HassRespond.yaml
=> [CA] Add HassRespond intent

sentences/ca/_common.yaml
=> [CA] Update _common.yaml

responses/sv/HassListAddItem.yaml, sentences/sv/todo_HassListAddItem.yaml, tests/sv/_fixtures.yaml, tests/sv/todo_HassListAddItem.yaml
Add support for Swedish for `HassListAddItem`
Used AI to generate this as an experiment, needs sign off from a Swedish native speaker.
=> Add Swedish HassListAddItem

sentences/de-CH/homeassistant_HassRespond.yaml, tests/de-CH/homeassistant_HassRespond.yaml
=> [de-CH] Add sentences and tests for HassRespond

responses/nl/HassDecreaseTimer.yaml, responses/nl/HassIncreaseTimer.yaml, tests/nl/homeassistant_HassDecreaseTimer.yaml, tests/nl/homeassistant_HassIncreaseTimer.yaml
This adds the duration to the responses when timers are increased or decreased, like also added to the start timer responses.
=> [NL] Add duration to increase and decrease timer

responses/nl/HassMediaPrevious.yaml, sentences/nl/media_player_HassMediaPrevious.yaml, tests/nl/media_player_HassMediaPrevious.yaml
=> [NL] Add HassMediaPrevious

responses/en/HassDecreaseTimer.yaml, responses/en/HassIncreaseTimer.yaml, tests/en/homeassistant_HassDecreaseTimer.yaml, tests/en/homeassistant_HassIncreaseTimer.yaml
In addition to #2494 this PR also adds the duration added or removed from a timer when the respective intents are used.
=> [EN] Add duration added or removed from timer

sentences/nl/cover_HassSetPosition.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, tests/nl/cover_HassSetPosition.yaml, tests/nl/cover_HassTurnOff.yaml, tests/nl/cover_HassTurnOn.yaml
Add `<would>` for cover intents.
Add more options to set position
=> [NL] Improve cover intents

sentences/ca/climate_HassTurnOff.yaml, sentences/ca/climate_HassTurnOn.yaml, sentences/ca/homeassistant_HassTurnOn.yaml, sentences/ca/light_HassTurnOff.yaml, sentences/ca/light_HassTurnOn.yaml, tests/ca/climate_HassTurnOff.yaml, tests/ca/climate_HassTurnOn.yaml, tests/ca/light_HassTurnOff.yaml, tests/ca/light_HassTurnOn.yaml
* Improve `light` turn on-off with `area` context, rather than "all lights" from the house
* Turn on-off air conditioner / climate with generic name
=> [CA] Improve light and climate on-off action

responses/ro/HassMediaPrevious.yaml, sentences/ro/_common.yaml, sentences/ro/media_player_HassMediaPrevious.yaml, tests/ro/media_player_HassMediaPrevious.yaml
RO translation of media_player_HassMediaPrevious
=> [RO] HassMediaPrevious

sentences/ro/_common.yaml
Better error messages regarding domains (now they are proper objects in sentences), following @jlpouffier's suggestion on Discord.
=> [RO] Better error messages - domains

sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
* remove sentences like `zou je de keukenlampen uit willen doen`
* add support for floors
=> [NL] Review LightTurnOn/Off

sentences/nl/_common.yaml, sentences/nl/lock_HassTurnOff.yaml, sentences/nl/lock_HassTurnOn.yaml, tests/nl/lock_HassTurnOff.yaml, tests/nl/lock_HassTurnOn.yaml
* add additional expansion rules
* remove sentences like `zou je het slot in de keuken open willen doen`
=> [NL] Review LockTurnOn/Off

sentences/nl/scene_HassTurnOn.yaml, sentences/nl/script_HassTurnOn.yaml, tests/nl/scene_HassTurnOn.yaml, tests/nl/script_HassTurnOn.yaml
Remove sentences like `zou je feestscript aan willen zetten`
=> [NL] Review Script/Scene TurnOn

sentences/nl/valve_HassSetPosition.yaml, sentences/nl/valve_HassTurnOff.yaml, sentences/nl/valve_HassTurnOn.yaml, tests/nl/valve_HassSetPosition.yaml, tests/nl/valve_HassTurnOff.yaml, tests/nl/valve_HassTurnOn.yaml
Add more options to intents for valve, including options using `<would>`
=> [NL] Review valve intents

sentences/nl/climate_HassClimateSetTemperature.yaml, tests/nl/climate_HassClimateSetTemperature.yaml
Add some more options for setting the temperature (including `<would>` sentences)
=> [NL] Review ClimateSet intent

sentences/ca/_common.yaml, tests/ca/light_HassLightSet.yaml
Voice assistant would miss the article.
=> [CA] Add case for LightSet

script/intentfest/count_sentences.py, script/intentfest/util.py
Adds a `count_sentences` command to `intentfest`
Example:
```
python3 -m script.intentfest count_sentences --language fr
```
=> Add count_sentences command to intentfest

responses/eu/HassClimateGetTemperature.yaml, responses/eu/HassClimateSetTemperature.yaml, responses/eu/HassGetState.yaml, responses/eu/HassLightSet.yaml, sentences/eu/_common.yaml, sentences/eu/homeassistant_HassGetState.yaml, tests/eu/_fixtures.yaml, tests/eu/homeassistant_HassGetState.yaml
Responses:
- HassGetState.yaml
- HassClimateGetTemperature.yaml
- HassClimateSetTemperature.yaml
- HassLightSet.yaml
Sentences:
- _common.yaml
- homeassistant_HassGetState.yaml
Tests:
- _fixtures.yaml
- homeassistant_HassGetState.yaml
=> [EU] First set of HassGetState + add some other responses

sentences/nl/media_player_HassMediaPause.yaml, tests/nl/media_player_HassMediaPause.yaml
Adds sentences using `stop` and `stoppen` to pause media players
=> [NL] Add `stoppen` as verb to pause media player

sentences/de/_common.yaml, sentences/de/climate_HassClimateGetTemperature.yaml, sentences/de/climate_HassClimateSetTemperature.yaml, sentences/de/homeassistant_HassGetState.yaml, sentences/de/homeassistant_HassSetPosition.yaml, sentences/de/light_HassLightSet.yaml, sentences/de/media_player_HassMediaUnpause.yaml, sentences/de/media_player_HassSetVolume.yaml, tests/de/light_HassLightSet.yaml
This is the first optimization wave (_catching the "low hanging fruits"_) to optimize the complexity of all intents
| Intent | prior | now |
| --- | --- | --- |
| summary | 7,375,726,420 | 2,849,752,235 |
| HassCancelTimer | 2,088 | 2,088 |
| HassClimateGetTemperature | 83,636 | 9,827 |
| HassClimateSetTemperature | 3,898,752 | 162,864 |
| HassDecreaseTimer | 129,828 | 129,828 |
| HassGetCurrentDate | 620 | 620 |
| HassGetCurrentTime | 13 | 13 |
| HassGetState | 143,689,654 | 117,000,166 |
| HassGetWeather | 228 | 116 |
| HassIncreaseTimer | 64,914 | 64,914 |
| HassLightSet | 5,212,372,684 | 724,455,228 |
| HassListAddItem | 560 | 560 |
| HassMediaNext | 67,752 | 41,832 |
| HassMediaPause | 12,235 | 12,171 |
| HassMediaPrevious | 677,52 | 418,32 |
| HassMediaUnpause | 1,611,211 | 931,763 …
=> [DE] Optimize sentences

responses/nl/HassGetState.yaml, responses/nl/HassTurnOn.yaml, tests/nl/climate_HassClimateSetTemperature.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml, tests/nl/lock_HassTurnOff.yaml, tests/nl/lock_HassTurnOn.yaml
=> [NL] Add missing responses to tests and remove unused responses

sentences/cs/_common.yaml, sentences/cs/cover_HassGetState.yaml, sentences/cs/fan_HassTurnOff.yaml, sentences/cs/fan_HassTurnOn.yaml, sentences/cs/homeassistant_HassTurnOff.yaml, sentences/cs/homeassistant_HassTurnOn.yaml, tests/cs/fan_HassTurnOff.yaml, tests/cs/fan_HassTurnOn.yaml
Make fans room aware
Fix for failing test where window binary sensors got matched with cover intents to get state
=> [CS] Make fans room aware

.github/actions/count-words/action.yml, .github/workflows/ci.yaml
When modifying a language, GHA will write a message in PR with the new word count.
=> ci: add check for language changes

sentences/fr/_common.yaml
**Before** 
fr: 1,129,456,092,651
-- HassDecreaseTimer: 717,848,679,744
-- HassIncreaseTimer: 410,199,245,568
-- HassGetState: 1,089,834,319
-- HassSetPosition: 96,704,060
-- HassStartTimer: 83,485,892
-- HassTimerStatus: 35,872,728
-- HassCancelTimer: 29,787,156
-- HassPauseTimer: 23,061,024
-- HassTurnOff: 18,610,207
-- HassLightSet: 14,020,102
-- HassUnpauseTimer: 7,687,008
-- HassTurnOn: 5,552,702
-- HassMediaPause: 1,748,217
-- HassMediaUnpause: 1,527,014
-- HassSetVolume: 161,700
-- HassMediaNext: 41,486
-- HassMediaPrevious: 41,486
-- HassClimateSetTemperature: 28,512
-- HassShoppingListAddItem: 1,296
-- HassListAddItem: 1,260
-- HassGetWeather: 814
-- HassVacuumReturnToBase: 175
-- HassClimateGetTemperature: 108
-- HassVacuumStart: 20
-- HassRespond: 18
-- HassGetCurrentDate: 17 …
=> Reduce french sentences count by 42

sentences/fr/_common.yaml
**Before**
fr: 26,847,040,651
-- HassDecreaseTimer: 16,285,607,744
-- HassIncreaseTimer: 9,306,061,568
-- HassGetState: 1,089,834,319
-- HassSetPosition: 96,704,060
-- HassTurnOff: 18,610,207
-- HassLightSet: 14,020,102
-- HassStartTimer: 12,561,892
-- HassTurnOn: 5,552,702
-- HassTimerStatus: 5,408,728
-- HassCancelTimer: 4,491,156
-- HassPauseTimer: 3,477,024
-- HassMediaPause: 1,748,217
-- HassMediaUnpause: 1,527,014
-- HassUnpauseTimer: 1,159,008
-- HassSetVolume: 161,700
-- HassMediaNext: 41,486
-- HassMediaPrevious: 41,486
-- HassClimateSetTemperature: 28,512
-- HassShoppingListAddItem: 1,296
-- HassListAddItem: 1,260
-- HassGetWeather: 814
-- HassVacuumReturnToBase: 175
-- HassClimateGetTemperature: 108
-- HassVacuumStart: 20
-- HassRespond: 18
-- HassGetCurrentDate: 17
-- …
=> Reduce french sentences count by 19

intents.yaml, responses/fr/HassClimateGetTemperature.yaml, sentences/fr/_common.yaml, sentences/fr/climate_HassClimateGetTemperature.yaml, sentences/fr/cover_HassSetPosition.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/media_player_HassSetVolume.yaml, sentences/fr/todo_HassListAddItem.yaml, tests/fr/climate_HassClimateGetTemperature.yaml, tests/fr/cover_HassSetPosition.yaml, tests/fr/cover_HassTurnOff.yaml, tests/fr/cover_HassTurnOn.yaml, tests/fr/media_player_HassSetVolume.yaml, tests/fr/todo_HassListAddItem.yaml
- I added `degrés` to the response of ClimateGetTemperature
- I made ClimateGetTemperature context aware so you can ask about the temperature in your current room
- Cover (Turn on , Turn off, set position) support floors
- I added verbs (`Baisser`, `Monter`) to set the volume of a media player
- I added one form `AjouteZ` to the todo intent because HA CLoud keeps transcribing as such
=> [FR] A Bunch of small fixes

responses/hr/HassRespond.yaml, sentences/hr/homeassistant_HassRespond.yaml, tests/hr/homeassistant_HassRespond.yaml
added Croatian translation for HassRespond
=> [HR] respond intent

responses/hr/HassGetWeather.yaml, sentences/hr/_common.yaml, sentences/hr/weather_HassGetWeather.yaml, tests/hr/_fixtures.yaml, tests/hr/weather_HassGetWeather.yaml
added Croatian intents for Get Weather
=> [HR] GetWeather

responses/hr/HassVacuumReturnToBase.yaml, responses/hr/HassVacuumStart.yaml, sentences/hr/vacuum_HassVacuumReturnToBase.yaml, sentences/hr/vacuum_HassVacuumStart.yaml, tests/hr/_fixtures.yaml, tests/hr/vacuum_HassVacuumReturnToBase.yaml, tests/hr/vacuum_HassVacuumStart.yaml
added croatian intents for vacuum
=> [HR] vacuum

responses/hr/HassMediaNext.yaml, responses/hr/HassMediaPause.yaml, responses/hr/HassMediaPrevious.yaml, responses/hr/HassMediaUnpause.yaml, responses/hr/HassSetVolume.yaml, sentences/hr/_common.yaml, sentences/hr/media_player_HassMediaNext.yaml, sentences/hr/media_player_HassMediaPause.yaml, sentences/hr/media_player_HassMediaPrevious.yaml, sentences/hr/media_player_HassMediaUnpause.yaml, sentences/hr/media_player_HassSetVolume.yaml, tests/hr/_fixtures.yaml, tests/hr/media_player_HassMediaNext.yaml, tests/hr/media_player_HassMediaPause.yaml, tests/hr/media_player_HassMediaPrevious.yaml, tests/hr/media_player_HassMediaUnpause.yaml, tests/hr/media_player_HassSetVolume.yaml
added croatian translations for media intents
=> [HR] media intents

responses/de/HassCancelAllTimers.yaml, sentences/de/homeassistant_HassCancelAllTimers.yaml, tests/de/homeassistant_HassCancelAllTimers.yaml
DE intent for cancelling all timers (see https://github.com/home-assistant/intents/pull/2603)
=> [DE] HassCancelAllTimers

responses/hr/HassStartTimer.yaml, sentences/hr/_common.yaml, sentences/hr/homeassistant_HassStartTimer.yaml, tests/hr/_fixtures.yaml, tests/hr/homeassistant_HassStartTimer.yaml
added croatian SetTimer intent
=> [HR] SetTimer

responses/hr/HassCancelTimer.yaml, sentences/hr/_common.yaml, sentences/hr/homeassistant_HassCancelTimer.yaml, tests/hr/homeassistant_HassCancelTimer.yaml
=> [HR] CancelTimer

responses/fr/HassCancelAllTimers.yaml, sentences/fr/_common.yaml, sentences/fr/homeassistant_HassCancelAllTimers.yaml, sentences/fr/homeassistant_HassCancelTimer.yaml, tests/fr/homeassistant_HassCancelAllTimers.yaml
Support canceling all timers in French.
**NOTE**, since we support canceling all timers of an area, I also made a context-aware version of fit.
=> [FR] Cancel All Timers

sentences/de/homeassistant_HassCancelAllTimers.yaml, tests/de/homeassistant_HassCancelAllTimers.yaml
=> [DE] Add area awareness and further area sentences for HassCancelAllTimers

responses/hr/HassTimerStatus.yaml, sentences/hr/_common.yaml, sentences/hr/homeassistant_HassTimerStatus.yaml, tests/hr/_fixtures.yaml, tests/hr/homeassistant_HassTimerStatus.yaml
=> [HR] TimerStatus

responses/de/HassGetState.yaml, sentences/de/_common.yaml, sentences/de/homeassistant_HassGetState.yaml, sentences/de/person_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/person_HassGetState.yaml
Add person HassGetState intents - adopted from EN
=> [DE] Add person intents

responses/nl/HassCancelAllTimers.yaml, sentences/nl/_common.yaml, sentences/nl/homeassistant_HassCancelAllTimers.yaml, sentences/nl/homeassistant_HassCancelTimer.yaml, sentences/nl/homeassistant_HassDecreaseTimer.yaml, sentences/nl/homeassistant_HassIncreaseTimer.yaml, sentences/nl/homeassistant_HassTimerStatus.yaml, tests/nl/homeassistant_HassCancelAllTimers.yaml
Adds CancelAllTimers sentences, also added area aware sentences.
Moved some timer related local expansion rules to _common.yaml
Revised <all> expansion rule to remove unused options
=> [NL] Add CancelAllTimers

CODEOWNERS, languages.yaml
Herzlich Willkommen @andreasbrett :heart:
=> [DE] Add @andreasbrett as new language leader 

sentences/sk/light_HassTurnOff.yaml, sentences/sk/light_HassTurnOn.yaml, tests/sk/light_HassTurnOff.yaml, tests/sk/light_HassTurnOn.yaml
Added ability to turn on/off light entities. It is supported, but was missing in sk language
=> [sk] lights turn on/off entity

responses/ro/HassCancelAllTimers.yaml, sentences/ro/homeassistant_HassCancelAllTimers.yaml, tests/ro/homeassistant_HassCancelAllTimers.yaml
=> [RO] HassCancelAllTimers

sentences/ro/_common.yaml, sentences/ro/vacuum_HassVacuumStart.yaml, tests/ro/vacuum_HassVacuumStart.yaml
=> [RO] Start vacuum on floor

sentences/sv/_common.yaml
I've added error messages for floors in the swedish _common.yaml-file.
I've also added a few other sentences that were included in the English _common.yaml-file.
This is my first ever PR, so I'm not sure I've done everything right. Just wanting to contribute. :)
=> [SV] Update _common.yaml error messages for floors

responses/hr/HassCancelAllTimers.yaml, responses/hr/HassCancelTimer.yaml, sentences/hr/_common.yaml, sentences/hr/homeassistant_HassCancelAllTimers.yaml, tests/hr/homeassistant_HassCancelAllTimers.yaml, tests/hr/homeassistant_HassCancelTimer.yaml
Added Croatian HassCancelAllTimers intent
=> [HR] HassCancelAllTimers

sentences/de/_common.yaml, tests/de/_fixtures.yaml, tests/de/cover_HassTurnOff.yaml, tests/de/cover_HassTurnOn.yaml
fixes https://github.com/home-assistant/intents/issues/2713
=> [DE] fix Rollladen vs Rolladen

sentences/sk/_common.yaml, sentences/sk/climate_HassClimateGetTemperature.yaml, sentences/sk/climate_HassClimateSetTemperature.yaml, sentences/sk/cover_HassTurnOff.yaml, sentences/sk/cover_HassTurnOn.yaml, sentences/sk/fan_HassTurnOff.yaml, sentences/sk/fan_HassTurnOn.yaml, sentences/sk/homeassistant_HassGetState.yaml, sentences/sk/homeassistant_HassTurnOff.yaml, sentences/sk/homeassistant_HassTurnOn.yaml, sentences/sk/light_HassLightSet.yaml, sentences/sk/light_HassTurnOff.yaml, sentences/sk/light_HassTurnOn.yaml
Moved prepositions into area expansion rule. United usage of area across intents.
=> [sk] prepositions refactoring

responses/sk/HassGetState.yaml, sentences/sk/_common.yaml, sentences/sk/binary_sensor_HassGetState.yaml, tests/sk/_fixtures.yaml, tests/sk/binary_sensor_HassGetState.yaml
Added binary sensor get state, count, etc for device class door,garage_door,window
=> [SK] binary_sensor HassGetState added

responses/it/HassSetPosition.yaml, sentences/it/cover_HassSetPosition.yaml, tests/it/cover_HassSetPosition.yaml
=> [IT] Fix responses for cover_HassSetPosition

script/intentfest/website_summary.py, website/src-11ty/index.html
Add a new table below intent table to list which intents are needed for the usable languages to be marked complete.
=> List almost complete languages

responses/fi/HassGetWeather.yaml, sentences/fi/weather_HassGetWeather.yaml, tests/fi/_fixtures.yaml, tests/fi/weather_HassGetWeather.yaml
Responses are taken from already translated stuff so had to change them.
Also "kerro millainen sää on" didn't work because STT changes that to "sä" for some reason.
=> Fixed responses and some sentences.

.pre-commit-config.yaml, tests/test_language_sentences.py
Found by @andreasbrett in #2752
cc @synesthesiam
=> Fix HassRespond tests

sentences/it/vacuum_HassVacuumStart.yaml
=> [IT] Add support for vacuum_HassVacuumStart.yaml

responses/it/HassGetCurrentDate.yaml, sentences/it/homeassistant_HassGetCurrentDate.yaml, tests/it/homeassistant_HassGetCurrentDate.yaml
Add Italian support to "GetCurrentDate"
=> [IT] Current Date

responses/it/HassCancelAllTimers.yaml, sentences/it/_common.yaml, sentences/it/homeassistant_HassCancelAllTimers.yaml, tests/it/homeassistant_HassCancelAllTimers.yaml
Add support for Italian intents of CancelAllTimers
=> [IT] Add support for CancelAllTimers

responses/pt/HassTurnOn.yaml
=> [PT] Fixed typo on turning lights on

sentences/it/_common.yaml
Update _common.yaml with two more errors
entity_wrong_state
feature_not_supported
=> [IT] Update _common.yaml with two more errors

sentences/de/homeassistant_HassTurnOff.yaml, sentences/de/homeassistant_HassTurnOn.yaml, tests/de/homeassistant_HassTurnOff.yaml, tests/de/homeassistant_HassTurnOn.yaml
SSIA (fixes https://github.com/home-assistant/intents/issues/2775)
=> [DE] allow targeting switchables in areas for HassTurnOn/Off

sentences/de/climate_HassClimateGetTemperature.yaml, tests/de/climate_HassClimateGetTemperature.yaml
this is a PoC to properly solve https://github.com/home-assistant/core/issues/133733
=> [DE] Add area-awareness to HassClimateGetTemperature

responses/bg/HassRespond.yaml, responses/bg/HassSetPosition.yaml, responses/bg/HassVacuumReturnToBase.yaml, responses/bg/HassVacuumStart.yaml, sentences/bg/_common.yaml, sentences/bg/cover_HassSetPosition.yaml, sentences/bg/homeassistant_HassRespond.yaml, sentences/bg/vacuum_HassVacuumReturnToBase.yaml, sentences/bg/vacuum_HassVacuumStart.yaml, tests/bg/_fixtures.yaml, tests/bg/cover_HassSetPosition.yaml, tests/bg/homeassistant_HassRespond.yaml, tests/bg/vacuum_HassVacuumReturnToBase.yaml, tests/bg/vacuum_HassVacuumStart.yaml
Initial attempt to add - HassRespond, HassSetPosition, HassVacuumStart and HassVacuumReturnToBase
=> [BG] add HassRespond, HassSetPosition, HassVacuumStart, HassVacuumReturnToBase

responses/sl/HassCancelAllTimers.yaml, sentences/sl/homeassistant_HassCancelAllTimers.yaml, tests/sl/homeassistant_HassCancelAllTimers.yaml
Added Slovenian sentences and test for HassCancelAllTimers.
=> [sl] add HassCancelAllTimers

sentences/sr/homeassistant_HassNevermind.yaml, tests/sr/homeassistant_HassNevermind.yaml
Add serbian intents for Nevermind
=> [SR] Add Nevermind

sentences/ca/homeassistant_HassGetCurrentTime.yaml
=> [CA] Add alternatives for HassGetCurrentTime

sentences/ca/homeassistant_HassGetCurrentDate.yaml, tests/ca/homeassistant_HassGetCurrentDate.yaml
=> [CA] Add alternatives for HassGetCurrentDate

sentences/sk/light_HassTurnOff.yaml, sentences/sk/light_HassTurnOn.yaml, tests/sk/light_HassTurnOff.yaml, tests/sk/light_HassTurnOn.yaml
Added ability to turn on/off lights with satellite
=> [SK] lights on/off with satellite

responses/sk/HassStartTimer.yaml, sentences/sk/_common.yaml, sentences/sk/homeassistant_HassStartTimer.yaml, tests/sk/homeassistant_HassStartTimer.yaml
Zdravim,
implementoval som set timer intent pre slovenský jazyk. Mám v pláne postupne doimplementovať aj zbytok timer intentov v nasledujúcom čase. Toto je môj prvý pull request na githube tak dúfam že bude všetko v poriadku. Uvítam akúkoľvek spätnú väzbu.
=> [SK] Implemented set timer intent for sk language 

sentences/de/shopping_list_HassShoppingListAddItem.yaml, sentences/de/todo_HassListAddItem.yaml, tests/de/shopping_list_HassShoppingListAddItem.yaml, tests/de/todo_HassListAddItem.yaml
SSIA - fixes https://github.com/home-assistant/intents/issues/2808
@mib1185 @easterapps could you please review this? don't want to rush this although tests and (my late night) logic behind the PR work out.
=> [DE] harmonize todo and shopping lists

sentences/sv/shopping_list_HassShoppingListAddItem.yaml, tests/sv/shopping_list_HassShoppingListAddItem.yaml
Added the word "på" to HassShoppingListAddItem for a more correct sentence structure
=> [SV] Added word "på" for adding items to shoppinglist

sentences/sv/homeassistant_HassTurnOff.yaml, sentences/sv/homeassistant_HassTurnOn.yaml, sentences/sv/script_HassTurnOn.yaml, tests/sv/_fixtures.yaml, tests/sv/script_HassTurnOn.yaml
Added support for scripts and excluded them from HassTurnOn.
=> [SV] Scripts

responses/fr/HassGetWeather.yaml, tests/fr/weather_HassGetWeather.yaml
These two sentences are not quite correct in French, there should only be one "pas".
=> Fix incorrect French responses in HassGetWeather.yaml

sentences/de/shopping_list_HassShoppingListAddItem.yaml, tests/de/shopping_list_HassShoppingListAddItem.yaml
some more examples for #2808 and  #2840
=> [DE] Add more german shopping list examples

sentences/it/todo_HassListAddItem.yaml, tests/it/todo_HassListAddItem.yaml
Merged sentence in single line and added some tests.
This is also needed for a future cleanup of <the> expansion rule in _common.yaml
=> [IT] Clean and merge 'todo' sentences

sentences/de/homeassistant_HassStartTimer.yaml, tests/de/homeassistant_HassStartTimer.yaml
With Alexa and Siri, I'm able to set a timer just by saying "Timer X Minuten". This PR adds this possibility along with some variations for named timers.
=> [DE] Add some shorter sentences for "set timer"

sentences/bg/binary_sensor_HassGetState.yaml
Колко лампи светят в банята 
Колко лампи са светнати в банята
Светнати ли са крушките в банята
=> [BG] Update binary_sensor_HassGetState.yaml

responses/de/HassRespond.yaml, sentences/de/_common.yaml, sentences/de/homeassistant_HassRespond.yaml, tests/de/homeassistant_HassRespond.yaml
Reverts home-assistant/intents#2752
explanation: see https://github.com/home-assistant/intents/pull/2876
=> Revert "[DE] say xyz"

responses/nl/HassBroadcast.yaml, sentences/nl/_common.yaml, sentences/nl/assist_satellite_HassBroadcast.yaml, tests/nl/assist_satellite_HassBroadcast.yaml
=> [NL] Add assist_satellite_HassBroadcast

responses/da/HassSetPosition.yaml, sentences/da/_common.yaml, sentences/da/cover_HassSetPosition.yaml, tests/da/cover_HassSetPosition.yaml
Add support for Cover HassSetPosition in danish
=> [DA] Add support for Cover HassSetPosition

responses/da/HassPauseTimer.yaml, responses/da/HassUnpauseTimer.yaml, sentences/da/_common.yaml, sentences/da/homeassistant_HassPauseTimer.yaml, sentences/da/homeassistant_HassUnpauseTimer.yaml, tests/da/homeassistant_HassPauseTimer.yaml, tests/da/homeassistant_HassUnpauseTimer.yaml
Add support for Timer pause/unpause in danish
=> [DA] Add support for Timer pause/unpause

responses/sr-Latn/HassBroadcast.yaml, sentences/sr-Latn/_common.yaml, sentences/sr-Latn/assist_satellite_HassBroadcast.yaml, tests/sr-Latn/assist_satellite_HassBroadcast.yaml
=> [sr-Latn] Add support for HassBroadcast

responses/da/HassGetWeather.yaml, tests/da/_fixtures.yaml
=> [DA] Fix HassGetWeather

responses/da/HassGetWeather.yaml, tests/da/_fixtures.yaml
Reverts home-assistant/intents#2907 shouldn't have merged
=> Revert "[DA] Fix HassGetWeather"

responses/ru/HassBroadcast.yaml, sentences/ru/_common.yaml, sentences/ru/assist_satellite_HassBroadcast.yaml, tests/ru/assist_satellite_HassBroadcast.yaml
Translation of intent into Russian
_Обязательные блок (о|что) для уменьшения вероятности ложных срабатываний. Позднее можно сделать опциональным._
=> [RU] Add HassBroadcast

responses/zh-hk/HassCancelAllTimers.yaml, responses/zh-hk/HassRespond.yaml, sentences/zh-hk/_common.yaml, sentences/zh-hk/homeassistant_HassCancelAllTimers.yaml, sentences/zh-hk/homeassistant_HassRespond.yaml, tests/zh-hk/homeassistant_HassCancelAllTimers.yaml, tests/zh-hk/homeassistant_HassRespond.yaml
update CancelAllTimes and Responsd translation
=> [zh-hk] CancelAllTimers, Rspond

responses/cs/HassGetState.yaml, sentences/cs/_common.yaml, sentences/cs/binary_sensor_HassGetState.yaml, tests/cs/_fixtures.yaml, tests/cs/binary_sensor_HassGetState.yaml
Add all mising binary sensor intents
Revise current binary sensor intents
=> [CS] Revision of binary sensors

responses/cs/HassTurnOn.yaml, sentences/cs/_common.yaml, sentences/cs/homeassistant_HassTurnOff.yaml, sentences/cs/homeassistant_HassTurnOn.yaml, sentences/cs/scene_HassTurnOn.yaml, sentences/cs/script_HassTurnOn.yaml, tests/cs/_fixtures.yaml, tests/cs/script_HassTurnOn.yaml
Exclude sensors from HassTurnOn and HassTurnOff as they should be read only
Review of scene intent
Separate script intent
=> [CS] Review scene and script intents

responses/da/HassVacuumReturnToBase.yaml, responses/da/HassVacuumStart.yaml, sentences/da/_common.yaml, sentences/da/vacuum_HassVacuumReturnToBase.yaml, sentences/da/vacuum_HassVacuumStart.yaml, tests/da/_fixtures.yaml, tests/da/vacuum_HassVacuumReturnToBase.yaml, tests/da/vacuum_HassVacuumStart.yaml
Add HassVacuumStart/ReturnToBase support in danish
=> [DA] Add HassVacuum support

responses/ro/HassBroadcast.yaml, sentences/ro/_common.yaml, sentences/ro/assist_satellite_HassBroadcast.yaml, tests/ro/assist_satellite_HassBroadcast.yaml
=> [RO] HassBroadcast

sentences/ro/_common.yaml, sentences/ro/climate_HassClimateSetTemperature.yaml, tests/ro/climate_HassClimateSetTemperature.yaml
RO translation, completion and adaptation of #2921
=> [RO] HassClimateSetTemperature

sentences/zh-hk/_common.yaml, sentences/zh-hk/weather_HassGetWeather.yaml, tests/zh-hk/weather_HassGetWeather.yaml
updated weather_HassGetWeather language combination
=> [zh-hk]weather_HassGetWeather

sentences/ru/climate_HassClimateSetTemperature.yaml, tests/ru/climate_HassClimateSetTemperature.yaml
Added commands to control climate device by name
=> [RU] Improvements for HassClimateSetTemperature

responses/it/HassClimateSetTemperature.yaml, sentences/it/_common.yaml, sentences/it/climate_HassClimateSetTemperature.yaml, tests/it/_fixtures.yaml, tests/it/climate_HassClimateSetTemperature.yaml
Expand HassClimateSetTemperature rules to align with the changes made in #2921
=> [IT] Update HassClimateSetTemperature 

responses/fr/HassBroadcast.yaml, sentences/fr/_common.yaml, sentences/fr/assist_satellite_HassBroadcast.yaml, sentences/fr/climate_HassClimateSetTemperature.yaml, tests/fr/_fixtures.yaml, tests/fr/assist_satellite_HassBroadcast.yaml, tests/fr/climate_HassClimateSetTemperature.yaml
Added Broadcast intent, basic sentences for now. 
To be completed later when we can target floors and areas.
The sentences were already present but we refreshed them.
We now support
- Targeting an area
- Targeting a floor
- Targeting a specific device
- Targeting the current area or floor.
=> [FR] Broadcast and Set Temperature Intents

responses/it/HassBroadcast.yaml, sentences/it/_common.yaml, sentences/it/assist_satellite_HassBroadcast.yaml, tests/it/assist_satellite_HassBroadcast.yaml
Translation of this intent in Italian
=> [IT ] Add HassBroadcast

responses/de/HassGetState.yaml, sentences/de/person_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/person_HassGetState.yaml
Fixes https://github.com/home-assistant/intents/issues/2952
=> [DE] fix person_HassGetState for home zone

sentences/de/cover_HassGetState.yaml, sentences/de/cover_HassTurnOff.yaml, sentences/de/cover_HassTurnOn.yaml, tests/de/cover_HassGetState.yaml, tests/de/cover_HassTurnOff.yaml, tests/de/cover_HassTurnOn.yaml
- allows targeting floors for cover domain
- aligns [DE] with [EN] and fixes https://github.com/home-assistant/intents/issues/2919
=> [DE] add floors to cover_*

sentences/nl/climate_HassClimateGetTemperature.yaml, tests/nl/climate_HassClimateGetTemperature.yaml
Added context sentences for getting the current temperature from [wyoming-rhasspy-speech](https://github.com/rhasspy/wyoming-rhasspy-speech/blob/master/wyoming_rhasspy_speech/sentences/nl.yaml#L374)
=> [NL] Add context sentences for HassClimateGetTemperature

responses/da/HassTurnOff.yaml, responses/da/HassTurnOn.yaml, sentences/da/homeassistant_HassTurnOff.yaml, sentences/da/homeassistant_HassTurnOn.yaml, sentences/da/valve_HassSetPosition.yaml, sentences/da/valve_HassTurnOff.yaml, sentences/da/valve_HassTurnOn.yaml, tests/da/_fixtures.yaml, tests/da/valve_HassSetPosition.yaml, tests/da/valve_HassTurnOff.yaml, tests/da/valve_HassTurnOn.yaml
Add
- HassTurnOn
- HassTurnOff
- HassSetPosition
in danish for Valve domain
=> [DA] Add intents for Valve domain

requirements.txt, sentences/sv/homeassistant_HassCancelTimer.yaml, sentences/sv/homeassistant_HassDecreaseTimer.yaml, sentences/sv/homeassistant_HassIncreaseTimer.yaml, sentences/sv/homeassistant_HassPauseTimer.yaml, sentences/sv/homeassistant_HassTimerStatus.yaml
* Bump hassil: https://github.com/home-assistant/hassil/compare/v2.2.1...v2.2.3
* Add fixes for when wildcards are part of a word or not (must be explicit now)
=> Bump hassil and fix wildcards inside/outside words

sentences/sv/cover_HassTurnOn.yaml, sentences/sv/homeassistant_HassTurnOn.yaml, tests/sv/_fixtures.yaml, tests/sv/cover_HassTurnOn.yaml, tests/sv/homeassistant_HassTurnOn.yaml
Clean up unused cover fixture and combind testcase
that testes same intent and reduces redundancy in
sentences.
=> SV: Move cover from generic HassTurnOn

sentences/sv/homeassistant_HassTurnOff.yaml, sentences/sv/homeassistant_HassTurnOn.yaml, sentences/sv/light_HassTurnOff.yaml, sentences/sv/light_HassTurnOn.yaml, tests/sv/homeassistant_HassTurnOff.yaml, tests/sv/homeassistant_HassTurnOn.yaml, tests/sv/light_HassTurnOff.yaml, tests/sv/light_HassTurnOn.yaml
Add support to turn on and off all lights
=> SV: Move light from generic HassTurnOn/HassTurnOn

responses/nl/HassClimateSetTemperature.yaml, sentences/nl/_common.yaml, sentences/nl/climate_HassClimateSetTemperature.yaml, tests/nl/_fixtures.yaml, tests/nl/climate_HassClimateSetTemperature.yaml
Update to work in 2025.2.0
* added floor support
* added named entity sentences
* added target temperature to response
=> [NL] Update ClimateSetTemperature

responses/da/HassClimateGetTemperature.yaml, sentences/da/_common.yaml, sentences/da/climate_HassClimateGetTemperature.yaml, tests/da/_fixtures.yaml, tests/da/climate_HassClimateGetTemperature.yaml
Update to ClimateGetTemperature in Danish:
1. Fixed responding "heat grader" as temperature
2. Extended sentences
=> [DA] Fix ClimateGetTemperature

responses/cs/HassBroadcast.yaml, sentences/cs/_common.yaml, sentences/cs/assist_satellite_HassBroadcast.yaml, tests/cs/assist_satellite_HassBroadcast.yaml
Add intents for `HassBroadcast`
* I'm not sure if the response **"Hotovo"** is the best choice or if a more specific answer, such as **"Oznámeno"** would be better.
=> [CS] Add intents for HassBroadcast

tests/sv/light_HassLightSet.yaml
Testcase was missing respose check for light_HassLightSet.
=> SV: Add response check to light_HassLightSet

responses/cs/HassGetCurrentDate.yaml, responses/cs/HassGetCurrentTime.yaml, sentences/cs/homeassistant_HassGetCurrentDate.yaml, sentences/cs/homeassistant_HassGetCurrentTime.yaml, tests/cs/homeassistant_HassGetCurrentDate.yaml, tests/cs/homeassistant_HassGetCurrentTime.yaml
Add built-in intents for `HassGetCurrentDate` and `HassGetCurrentTime`.
=> [CS] Add intents for Date and Time

responses/ru/HassTurnOn.yaml, tests/ru/homeassistant_HassTurnOn.yaml
There is always a need for more testing to avoid making typos.
=> [RU] fix typo

sentences/hr/homeassistant_HassCancelTimer.yaml, tests/hr/homeassistant_HassCancelTimer.yaml
The proposed change adds support for another sentence form when canceling a timer.
=> [HR] Support another form in canceling a timer

responses/hr/HassTimerStatus.yaml, tests/hr/homeassistant_HassTimerStatus.yaml
This PR improves the timer responses such that it is in line with the Croatian grammar.
=> [HR] Improve timer response

sentences/hr/homeassistant_HassIncreaseTimer.yaml, tests/hr/homeassistant_HassIncreaseTimer.yaml
This PR allows providing a timer area such that the sentence is grammatically correct.
=> [HR] Increase timer: provide an area according to the Croatian grammar

sentences/pt/light_HassTurnOff.yaml, sentences/pt/light_HassTurnOn.yaml
[PT] Makes lights sentences more consistent across use cases for better maintainability.
=> [PT] Lights consistency improvements

sentences/pt-br/light_HassTurnOff.yaml, sentences/pt-br/light_HassTurnOn.yaml
[PT-BR] Makes lights sentences more consistent across use cases for better maintainability.
=> [PT-BR] Lights consistency improvements

responses/pt-br/HassTurnOff.yaml, responses/pt-br/HassTurnOn.yaml, sentences/pt-br/cover_HassTurnOff.yaml, sentences/pt-br/cover_HassTurnOn.yaml, tests/pt-br/cover_HassTurnOff.yaml, tests/pt-br/cover_HassTurnOn.yaml
Based on comments on #2988 and comparing with other languages, I made some minor improvements on cover on-off.
Closes #2988
=> [PT-BR] Improve cover turn on-off usage cases

sentences/zh-hk/weather_HassGetWeather.yaml, tests/zh-hk/weather_HassGetWeather.yaml
update weather_HassGetWeather language support
=> [zh-hk] update weather format support

intents.yaml, script/intentfest/validate.py
Adds an `importance` key to intents in `intents.yaml`
This will be used to determine language support.
=> Add importance level to intents

intents.yaml, script/intentfest/validate.py
Adds a "usable" level for importance that indicates that an intent is important but not necessarily required.
=> Add "usable" label for intent importance

responses/cs/HassCancelTimer.yaml, responses/cs/HassStartTimer.yaml, responses/cs/HassTimerStatus.yaml, sentences/cs/_common.yaml, sentences/cs/homeassistant_HassCancelTimer.yaml, sentences/cs/homeassistant_HassStartTimer.yaml, sentences/cs/homeassistant_HassTimerStatus.yaml, tests/cs/_fixtures.yaml, tests/cs/homeassistant_HassCancelTimer.yaml, tests/cs/homeassistant_HassStartTimer.yaml, tests/cs/homeassistant_HassTimerStatus.yaml
Picked basic controls from PR #3008 and aligned them with minimal voice subset https://github.com/rhasspy/hassio-addons/blob/master/rhasspy-speech/src/wyoming_rhasspy_speech/sentences/cs.yaml
=> [CS] add basic timer commands, aligned with minimal voice set

responses/cs/HassRespond.yaml, sentences/cs/homeassistant_HassRespond.yaml, tests/cs/homeassistant_HassRespond.yaml
Took HassRespond from #3008 with small modifications.
=> [CS] hass respond

responses/sk/HassUnpauseTimer.yaml, sentences/sk/_common.yaml, sentences/sk/homeassistant_HassUnpauseTimer.yaml, tests/sk/homeassistant_HassUnpauseTimer.yaml
Ahoj @jose1711, vychádzal som z tvojho pausetimer. Ďakujem za veľa dobrej práce.
=> [SK] Add unpause timer intent

sentences/sk/_common.yaml, tests/sk/climate_HassClimateSetTemperature.yaml
=> [SK] Improve tests for ClimateSetTemperature.

sentences/sk/_common.yaml, tests/sk/homeassistant_HassIncreaseTimer.yaml
- recognize "jednu minútu/hodinu"
- increase range (it should be allowed to say "increase timer by 120 seconds")
=> [SK] Improve IncreaseTimer intent.

responses/sk/HassGetWeather.yaml, sentences/sk/_common.yaml, sentences/sk/weather_HassGetWeather.yaml, tests/sk/_fixtures.yaml, tests/sk/weather_HassGetWeather.yaml
- add rounding for coverage, UV index, pressure
- more sentences
- more tests
=> [SK] Improve GetWeather intent.

responses/sk/HassGetState.yaml, sentences/sk/_common.yaml, sentences/sk/binary_sensor_HassGetState.yaml, sentences/sk/cover_HassGetState.yaml, sentences/sk/cover_HassTurnOff.yaml, sentences/sk/homeassistant_HassGetState.yaml, tests/sk/_fixtures.yaml, tests/sk/binary_sensor_HassGetState.yaml, tests/sk/cover_HassGetState.yaml, tests/sk/homeassistant_HassGetState.yaml
- correct states for binary_sensors and covers
- more tests and comments
- remove query to check state/number of open/closed windows
- duplicate fixtures removed
=> [SK] Fix and improve intents related to covers and bs.

.pre-commit-config.yaml
Prettier v4 is causing issues in codespaces
=> Revert prettier back to v3

responses/ro/HassListCompleteItem.yaml, responses/ro/HassShoppingListCompleteItem.yaml, sentences/ro/shopping_list_HassShoppingListCompleteItem.yaml, sentences/ro/todo_HassListCompleteItem.yaml, tests/ro/shopping_list_HassShoppingListCompleteItem.yaml, tests/ro/todo_HassListCompleteItem.yaml
RO translation of #3004 and #3035
=> [RO] ListCompleteItem

responses/de/HassListCompleteItem.yaml, sentences/de/todo_HassListCompleteItem.yaml, tests/de/todo_HassListCompleteItem.yaml
DE version of https://github.com/home-assistant/intents/pull/3004
=> [DE] Add HassListCompleteItem

responses/gl/HassMediaNext.yaml, responses/gl/HassMediaPrevious.yaml, sentences/gl/_common.yaml, sentences/gl/media_player_HassMediaNext.yaml, sentences/gl/media_player_HassMediaPrevious.yaml, tests/gl/_fixtures.yaml, tests/gl/homeassistant_HassGetState.yaml, tests/gl/media_player_HassMediaNext.yaml, tests/gl/media_player_HassMediaPrevious.yaml
These are the first intents for media control. More to come later.
=> [GL] Add intents HassMediaNext and HassMediaPrevious

sentences/de/todo_HassListCompleteItem.yaml, tests/de/todo_HassListCompleteItem.yaml
this allows to use more prepositions to match further natural speaking, further it allows to use compound words for the list name
=> [DE] Extend HassListCompleteItem

responses/sk/HassGetState.yaml, sentences/sk/_common.yaml, sentences/sk/binary_sensor_HassGetState.yaml, sentences/sk/cover_HassGetState.yaml, sentences/sk/lock_HassGetState.yaml, tests/sk/_fixtures.yaml, tests/sk/cover_HassGetState.yaml, tests/sk/lock_HassGetState.yaml
=> [SK] Improve cover and lock domains.

sentences/pt-br/_common.yaml, sentences/pt-br/cover_HassTurnOff.yaml, sentences/pt-br/cover_HassTurnOn.yaml, tests/pt-br/cover_HassTurnOff.yaml, tests/pt-br/cover_HassTurnOn.yaml
=> [PT-BR] Fix cover turn on-off

responses/nl/HassListCompleteItem.yaml, responses/nl/HassShoppingListCompleteItem.yaml, sentences/nl/shopping_list_HassShoppingListCompleteItem.yaml, sentences/nl/todo_HassListCompleteItem.yaml, tests/nl/_fixtures.yaml, tests/nl/shopping_list_HassShoppingListCompleteItem.yaml, tests/nl/todo_HassListCompleteItem.yaml
Add translations for the ListCompleteItem intent both for todo lists and shopping lists.
=> [NL] Add ListRemoveItem

responses/pt-br/HassListAddItem.yaml, responses/pt-br/HassListCompleteItem.yaml, responses/pt-br/HassShoppingListAddItem.yaml, responses/pt-br/HassShoppingListCompleteItem.yaml, sentences/pt-br/_common.yaml, sentences/pt-br/shopping_list_HassShoppingListAddItem.yaml, sentences/pt-br/shopping_list_HassShoppingListCompleteItem.yaml, sentences/pt-br/todo_HassListCompleteItem.yaml, tests/pt-br/shopping_list_HassShoppingListAddItem.yaml, tests/pt-br/shopping_list_HassShoppingListCompleteItem.yaml, tests/pt-br/todo_HassListAddItem.yaml, tests/pt-br/todo_HassListCompleteItem.yaml
- pt-br: adds `todo_HassListCompleteItem`
- pt-br: small improvements in response for `todo_HassListAddItem`, `shopping_list_HassShoppingListAddItem` and `shopping_list_HassShoppingListCompleteItem`
=> [PT-BR] List intents improvements

requirements.txt, responses/sr/HassShoppingListCompleteItem.yaml, sentences/sr/shopping_list_HassShoppingListCompleteItem.yaml, sentences/sr/todo_HassListAddItem.yaml, tests/sr/shopping_list_HassShoppingListCompleteItem.yaml
Add serbian intens for HassShoppingListCompleteItem
=> [SR| Add HassShoppingListCompleteItem

responses/zh-cn/HassGetCurrentTime.yaml
Fix HassGetCurrentTime response error
=> [zh-cn] Fix HassGetCurrentTime response error

sentences/nl/_common.yaml, sentences/nl/climate_HassClimateSetTemperature.yaml, tests/nl/climate_HassClimateSetTemperature.yaml
=> [NL] HassClimateSetTemperature: allow verwarming next to temperatuur

responses/ca/HassListCompleteItem.yaml, sentences/ca/_common.yaml, sentences/ca/todo_HassListAddItem.yaml, sentences/ca/todo_HassListCompleteItem.yaml, tests/ca/_fixtures.yaml, tests/ca/todo_HassListCompleteItem.yaml
Add HassListCompleteItem (https://github.com/home-assistant/intents/pull/3004) to Catalan language.
=> [CA] Add HassListCompleteItem

responses/ca/HassShoppingListCompleteItem.yaml, sentences/ca/shopping_list_HassShoppingListCompleteItem.yaml, tests/ca/shopping_list_HassShoppingListCompleteItem.yaml
Add HassShoppingListCompleteItem (https://github.com/home-assistant/intents/pull/3035) to Catalan language.
=> [CA] Add HassShoppingListCompleteItem

responses/de/HassMediaSearchAndPlay.yaml, sentences/de/_common.yaml, sentences/de/media_player_HassMediaSearchAndPlay.yaml, tests/de/_fixtures.yaml, tests/de/media_player_HassMediaSearchAndPlay.yaml
DE version of https://github.com/home-assistant/intents/pull/3169
=> [DE] HassMediaSearchAndPlay

sentences/de/binary_sensor_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/binary_sensor_HassGetState.yaml
implements https://github.com/home-assistant/intents/issues/3156
=> [DE] query for all doors / windows

sentences/nl/_common.yaml, sentences/nl/cover_HassTurnOn.yaml, tests/nl/cover_HassTurnOn.yaml
Add more verbs to control blinds, shutters and shades.
* HassTurnOn: `optrekken`, `ophalen`
* HassTurnOff: `laten zakken`, `neer laten`
=> [NL] cover: add verbs to control blind|shutter|shade

sentences/de/_common.yaml, sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
Sometimes You want to adress a single light in a room. Or you talking about a single light but mean all of the lights. And also we have to use the genetive.
Example:
`Dimme das Licht im Esszimmer auf 100%`
`Setze die Helligkeits des Lichts im Esszimmer auf 100%`
`Setze die Helligkeit des Lichtes im Esszimmer auf 100%`
=> [DE] Update light_HassLightSet.yaml

responses/nl/HassMediaSearchAndPlay.yaml, sentences/nl/_common.yaml, sentences/nl/media_player_HassMediaSearchAndPlay.yaml, tests/nl/_fixtures.yaml, tests/nl/media_player_HassMediaSearchAndPlay.yaml
=> [NL] Add Media Search and Play

responses/cs/HassMediaSearchAndPlay.yaml, sentences/cs/_common.yaml, sentences/cs/media_player_HassMediaSearchAndPlay.yaml, tests/cs/_fixtures.yaml, tests/cs/media_player_HassMediaSearchAndPlay.yaml
Add built-in intents for `HassMediaSearchAndPlay`.
=> [CS] Add intents for HassMediaSearchAndPlay

script/intentfest/add_language.py
Add floor/timer/etc. TODO errors to add_language script
=> Add more errors to add_language script

intents.yaml, sentences/en/media_player_HassMediaSearchAndPlay.yaml, tests/en/_fixtures.yaml, tests/en/media_player_HassMediaSearchAndPlay.yaml
Requires #3225
Add some English sentences for the new SearchAndPlay
=> English sentences media search play

README.md
The intents table link in the readme was broken. This fixes that.
=> Fix intents table link

sentences/pt-br/_common.yaml, sentences/pt-br/cover_HassGetState.yaml, sentences/pt-br/cover_HassTurnOff.yaml, sentences/pt-br/cover_HassTurnOn.yaml, tests/pt-br/cover_HassGetState.yaml, tests/pt-br/cover_HassTurnOff.yaml, tests/pt-br/cover_HassTurnOn.yaml
=> [PT-BR] Fix cover turn on-off device classes

responses/de/HassClimateGetTemperature.yaml
Apply the fix of https://github.com/OHF-Voice/intents/pull/3189 to de in order to solve https://github.com/home-assistant/core/issues/142331#issuecomment-2838527468
=> [DE] Fix responses for get temperature

sentences/pt-BR/_common.yaml, sentences/pt-BR/cover_HassSetPosition.yaml, sentences/pt-BR/valve_HassSetPosition.yaml, tests/pt-BR/cover_HassSetPosition.yaml, tests/pt-BR/valve_HassSetPosition.yaml
=> [pt-BR] HassSetPosition refactor

sentences/de/media_player_HassSetVolume.yaml
Removes permutations like
> Ändere die Lautstärke des TV auf 10 ein
overall sentence count - ~25.000
=> [DE] Reduce permutations in HassSetVolume

responses/ca/HassGetState.yaml
Translate 🏠 `home` to catalan (casa).
=> [CA] Translate HassGetState at home

responses/ca/HassSetVolumeRelative.yaml, sentences/ca/_common.yaml, sentences/ca/media_player_HassSetVolume.yaml, sentences/ca/media_player_HassSetVolumeRelative.yaml, tests/ca/_fixtures.yaml, tests/ca/media_player_HassSetVolumeRelative.yaml
=> [CA] Add HassSetVolumeRelative

sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
...and add tests for new variations covered by global expansion rule
=> [DE] HassLightSet: remove local expansion rule covered by global expansion rule

sentences/de/_common.yaml, tests/de/light_HassLightSet.yaml
This PR extends the `brightness_level` list to also cover
- größte Stufe
- hellste Stufe
- kleinste Stufe
- geringste Stufe
- ...
=> [DE] HassLightSet: extend brightness_level list

responses/ro/HassFanSetSpeed.yaml, sentences/ro/_common.yaml, sentences/ro/fan_HassFanSetSpeed.yaml, tests/ro/fan_HassFanSetSpeed.yaml
=> [RO] HassFanSetSpeed

responses/ro/HassSetVolumeRelative.yaml, sentences/ro/_common.yaml, sentences/ro/media_player_HassSetVolumeRelative.yaml, tests/ro/media_player_HassSetVolumeRelative.yaml
=> [RO] HassSetVolumeRelative

responses/ro/HassMediaSearchAndPlay.yaml, sentences/ro/_common.yaml, sentences/ro/media_player_HassMediaSearchAndPlay.yaml, tests/ro/_fixtures.yaml, tests/ro/media_player_HassMediaSearchAndPlay.yaml
RO translation of #3169, #3237
=> [RO] HassMediaSearchAndPlay

sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
This PR adds 
- Helligkeitsstufe
- dimmen
as commands to brightness controls by min/max sentences.
=> [DE] HassLightSet: additional variations for brightness controls by min/max commands

sentences/de/_common.yaml, sentences/de/lock_HassGetState.yaml
this simplifies the expansion rules and only adds ~1k permutations.
see #3398 comments for further details
=> [DE] remove <alle_genitiv_natural_subset> in favor of less complexity

responses/pt-BR/HassFanSetSpeed.yaml, sentences/pt-BR/_common.yaml, sentences/pt-BR/climate_HassClimateSetTemperature.yaml, sentences/pt-BR/fan_HassFanSetSpeed.yaml, sentences/pt-BR/light_HassTurnOff.yaml, sentences/pt-BR/light_HassTurnOn.yaml, tests/pt-BR/_fixtures.yaml, tests/pt-BR/fan_HassFanSetSpeed.yaml
- Add HassFanSetSpeed
- Fix small issue on <piso> expansion rule
=> [pt-BR] Add HassFanSetSpeed

sentences/de/shopping_list_HassShoppingListCompleteItem.yaml, tests/de/shopping_list_HassShoppingListCompleteItem.yaml
similar to #3411 
this pr adds support for `unsere Liste` in all its variations.
streiche fom 3411 was already supported here.
=> [DE] shopping_list_HassShoppingListCompleteItem: add support for "unsere Liste"

CODEOWNERS, languages.yaml
_Su misión, si decide aceptarla... Será revisar las traducciones al español, para que el asistente de voz pueda entender a más gente y ser capaz de cumplir más acciones._
_Esta PR se autodestruirá en 3, 2..._
---
Adding myself to review Spanish as well, if that's ok 😙
=> Add duhow as Spanish leader

responses/nl/HassFanSetSpeed.yaml, sentences/nl/_common.yaml, sentences/nl/fan_HassFanSetSpeed.yaml, tests/nl/fan_HassFanSetSpeed.yaml
Add support for HassFanSetSpeed
=> [NL] Add HassFanSetSpeed

sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
for this PR I removed options in `(...|...)` that could result in an empty string and split them up to reduce permutations.
this led to a reduction in overall sentence count of 17.000
=> [DE] HassLightSet: optimize sentence structure

sentences/ro/_common.yaml
Fix https://github.com/home-assistant/core/issues/151274
=> [RO] Fix domain-related error messages

sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
This PR adds `Färbe (den|diesen) Raum {color}` as a possible command
=> [DE] HassLightSet: additional command for color controls

sentences/de/light_HassLightSet.yaml
This PR further reduces overall sentence count by another 5%.
I split up the two sentences with the most permutations and slightly adjusted the sentence structures.
OSC - ~800.000   -   no tested sentences lost.
=> [DE] HassLightSet: further reduce sentence count

sentences/pt/_common.yaml, sentences/pt/climate_HassClimateSetTemperature.yaml, sentences/pt/cover_HassSetPosition.yaml, sentences/pt/cover_HassTurnOff.yaml, sentences/pt/cover_HassTurnOn.yaml, sentences/pt/homeassistant_HassTurnOff.yaml, sentences/pt/homeassistant_HassTurnOn.yaml, sentences/pt/light_HassLightSet.yaml, sentences/pt/light_HassTurnOff.yaml, sentences/pt/light_HassTurnOn.yaml, sentences/pt/media_player_HassSetVolume.yaml
- Making infinitive verbs a standard for expansion rules for better consistency.
=> [pt] Infinitive verbs for consistency

sentences/de/_common.yaml, sentences/de/fan_HassTurnOff.yaml, sentences/de/fan_HassTurnOn.yaml, tests/de/fan_HassTurnOff.yaml, tests/de/fan_HassTurnOn.yaml
fan-edition( 😇 ) of #3489
adds support for 
- Überall die Lüfter anschalten
- schalte die Ventilatoren überall aus
- ...
=> [DE] Add "Überall" as a command for fan on/off

sentences/de/media_player_HassSetVolumeRelative.yaml, tests/de/media_player_HassSetVolumeRelative.yaml
This PR adds 
- zu laut
- Es ist zu laut
- die Musik ist zu laut
- zu leise
- es ist zu leise
- die Musik ist zu leise
as commands to HassSetVolumeRelative
=> [DE] HassSetVolumeRelative: add "Es ist zu Laut/Leise"

responses/de-CH/HassListCompleteItem.yaml, sentences/de-CH/_common.yaml, sentences/de-CH/todo_HassListAddItem.yaml, sentences/de-CH/todo_HassListCompleteItem.yaml, tests/de-CH/todo_HassListCompleteItem.yaml
Add swiss german intents for HassListAddItem
=> [de-CH] Add HassListAddItem

responses/de-CH/HassShoppingListCompleteItem.yaml, sentences/de-CH/_common.yaml, sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml, sentences/de-CH/shopping_list_HassShoppingListCompleteItem.yaml, tests/de-CH/shopping_list_HassShoppingListCompleteItem.yaml
Add swiss german intents for HassShoppingListCompleteItem
=> [de-CH] Add HassShoppingListCompleteItem
