sentences/README.md, sentences/en/cover_HassCloseCover.yaml, sentences/en/cover_HassOpenCover.yaml
The cover intents still had the old category key. If we want that one, we should add it to `intents.yaml`
=> Remove category

script/intentfest/validate.py, tests/nl/cover_HassCloseCover.yaml, tests/nl/cover_HassOpenCover.yaml
Each sentence will now be checked if all referenced slots are valid for the intent, and all referenced expansion rules will be checked to make sure their slots are valid for the intent.
=> Validate referenced slots/lists in sentences and expansion rules

script/intentfest/validate.py
This does a rough validation to ensure that all sentences are tested. 
If all sentences are tested, the number of test cases should be equal or higher than the number of sentences. This first pass validation checks this number. More refinement is possible and could be added in the future.
Current output:
```
❯ python3 -m script.intentfest validate
Validation failed
Language: nl
- tests/nl/cover_HassOpenCover.yaml: not all sentences have tests
- tests/nl/cover_HassCloseCover.yaml: not all sentences have tests
Language: fr
- tests/fr/homeassistant_HassTurnOn.yaml: not all sentences have tests
- tests/fr/homeassistant_HassToggle.yaml: not all sentences have tests
- tests/fr/homeassistant_HassTurnOff.yaml: not all sentences have tests
Language: en
- tests/en/homeassistant_HassTurnOn.yaml: not …
```
=> Validate that all sentences have at least 1 test

sentences/README.md
If an expansion rule wraps a slot name, it should be named after the slot name. Otherwise it should native language.
Fixes #27 and fixes #28.
=> Clarify expansion rule guidelines

responses/cs/HassClimateGetTemperature.yaml, sentences/cs/_common.yaml, sentences/cs/climate_HassClimateGetTemperature.yaml, sentences/cs/climate_HassClimateSetTemperature.yaml, sentences/cs/cover_HassCloseCover.yaml, sentences/cs/cover_HassOpenCover.yaml, sentences/cs/fan_HassTurnOff.yaml, sentences/cs/fan_HassTurnOn.yaml, sentences/cs/homeassistant_HassTurnOff.yaml, sentences/cs/homeassistant_HassTurnOn.yaml, sentences/cs/light_HassLightSet.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/_common.yaml, tests/cs/climate_HassClimateGetTemperature.yaml, tests/cs/climate_HassClimateSetTemperature.yaml, tests/cs/cover_HassCloseCover.yaml, tests/cs/cover_HassOpenCover.yaml, tests/cs/fan_HassTurnOff.yaml, tests/cs/fan_HassTurnOn.yaml, tests/cs/homeassistant_HassTurnOff.yaml, tests/cs/homeassistant_HassTurnOn.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
#57
This adds basic support for Czech, with the features implemented that `python3 -m script.intentfest add_language cs` suggested for the initial commit. And common translations. I'm going to keep adding sentences
=> Add empty Czech templates (cs)

sentences/pl/_common.yaml
https://pl.wiktionary.org/wiki/pomara%C5%84cz
=> Fix a typo in the Polish common sentences

tests/en/_fixtures.yaml, tests/en/cover_HassCloseCover.yaml, tests/en/cover_HassOpenCover.yaml, tests/nl/_fixtures.yaml, tests/nl/cover_HassCloseCover.yaml, tests/nl/cover_HassOpenCover.yaml
Use a common fixture name for the cover entity for both Dutch and English.
CC @TheFes @waltlillyman
=> Use better fixture name for cover

sentences/nl/_common.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, sentences/nl/light_HassLightSet.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/nl/light_HassLightSet.yaml
Merge `doe_enkelvoud` and `doe_meervoud`. Most were the same, only  mag/mogen was using an singular and plural form.
Also added `maak` to make `maak bolletje rood` a possible option ~~(will do that in a separate PR)~~ (made `<naar>` optional to support this)
=> [NL] Merge doe_enkelvoud and doe_meervoud

sentences/hu/_common.yaml, tests/hu/light_HassLightSet.yaml
Color names need to be outputted in English as per #119. This fixes it for HU.
=> Make sure HU outputs English color names

sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml
I think these duplicates have originated from the singular / plural <doe> format.
=> [NL] Remove duplicate sentences

sentences/sv/_common.yaml
Color names need to be outputted in English as per #119. This fixes it for SV.
=> Make sure SV outputs English color names

script/intentfest/validate.py
Home Assistant intents only work with English colors. Any color matched in non-English needs to be translated using the in-out format. Example:
```yaml
lists:
color:
values:
- in: "wit"
out: "white"
- in: "zwart"
out: "black"
```
This validation currently fails on:
```
❯ python3 -m script.intentfest validate
Validation failed
Language: sv
- Colors should use the in-out format to output English color names for Home Assistant. See sentences/nl/_common.yaml for an example.
Language: hu
- Colors should use the in-out format to output English color names for Home Assistant. See sentences/nl/_common.yaml for an example.
Language: nb
- Colors should use the in-out format to output English color names for Home Assistant. See sentences/nl/_common.yaml for an example.
```
=> Validate color names are outputted in English

script/intentfest/validate.py, tests/__init__.py, tests/conftest.py, tests/test_language_intents.py, tests/test_language_sentences.py
I want the validate step to be more about file format. The tests should test if all sentences are referencing correct intents. This is a first step to allow this structure. It moves the tests for a language common file into a new test.
=> Refactor tests to move some from validate to tests

script/intentfest/validate.py, tests/__init__.py, tests/test_language_sentences.py
Our format allows the same keys for `_common.yaml` and the intent files. However, as convention we don't allow that in this repository. This ensures validation checks this.
Also moves that all tested intents match the filename from validation to the test.
=> Make validation more strict

sentences/de/_common.yaml
Versuch etwas näher an den englischen Ausdrücken zu bleiben.
Einheiten sind im deutschen groß geschrieben
=> [DE] Minor adjustments

README.md, script/intentfest/validate.py, tests/__init__.py, tests/conftest.py, tests/test_language_intents.py, tests/test_language_sentences.py
This splits language intents tests by file.
Since we only allow lists/expansion rules to be defined in `_common.yaml`, we can limit the intent parser to common + the sentences in the file that we're looking at.
~~This however did not result in a speedup.~~
**Before**
```
48 passed in 11.36s
Slowest:
3.99s setup    tests/test_language_intents.py::test_language_sentences[de]
2.22s setup    tests/test_language_intents.py::test_language_sentences[nl]
1.74s setup    tests/test_language_intents.py::test_language_sentences[hu]
```
**After**
```
288 passed in 38.57s
Slowest:
2.25s call     tests/test_language_intents.py::test_cover_HassOpenCover[de]
1.83s call     tests/test_language_intents.py::test_cover_HassCloseCover[de]
1.76s call …
```
=> Split language intents tests by file

tests/en/_fixtures.yaml
Area name was in Dutch instead of English.
Missing double-quotes for consistency in file.
=> fix wrong language in area

tests/test_language_sentences.py
Before:
```
E                   AssertionError: For 'éteins la lumière de la chambre' did not receive slot 'name'
E                   assert 'name' in {'area': MatchEntity(name='area', value='bedroom'), 'domain': MatchEntity(name='domain', value='light')}
```
After:
```
E                   AssertionError: For 'éteins la lumière de la chambre' did not receive slot 'name'
E                   assert 'name' in ['area', 'domain']
E                    +  where ['area', 'domain'] = list({'area': MatchEntity(name='area', value='bedroom'), 'domain': MatchEntity(name='domain', value='light')})
```
=> Make test output slightly more readable if slot missing

.vscode/tasks.json, docs/codespace/README.md, script/test_file
- Add scrip to run the tests for a specific file `script/test_file `script/test_file sentences/nl/fan_HassTurnOn.yaml`
- Select all tests of language of passed in file by adding `--select-language` to the command.
- Add VSCode task that leverages this script
=> Add VSCode task to test current file or language

script/intentfest/validate.py, tests/pl/_fixtures.yaml, tests/pl/cover_HassCloseCover.yaml, tests/pl/cover_HassOpenCover.yaml
Validate that all area IDs used for entity fixtures are valid. Found 1 error for Polish.
=> Validate area ids correct

script/intentfest/validate.py
Validate to ensure match sentences do not contain any punctuation.
Punctuation is already ignored by the matcher and we don't want to have characters in our match sentences that are going to be ignored, as it that can lead to confusion.
=> Validate to guard no question marks added to sentences

docs/forking/README.md
When trying to run command as in example:
```
python3 -m script.intentfest add-language <lang_code>
```
following error appeared:
> error: argument action: invalid choice: 'add-language' (choose from 'add_language', 'validate', 'parse', 'sample', 'sample_template')
=> Fix command to add new language

.github/workflows/ci.yaml, CONTRIBUTING.md, README.md, docs/forking/README.md, languages.yaml, script/intentfest/add_language.py, script/intentfest/const.py, script/intentfest/validate.py
This adds a languages.YAML file to track leaders and names of the language. Support added to both validate and add_language commands.
We’re going to use this file as a foundation for generating `CODEOWNERS` and language summaries.
=> Add languages yaml

sentences/pt/_common.yaml
The frase "Não existe nenhum dispositivo ou entidade com o nome {{ entity }}." sounds more natural and complete.
=> [PT] New skip_word and error message "no_entity" tweak

README.md, languages.yaml, script/intentfest/const.py, script/intentfest/language_table.py, script/intentfest/util.py
Don't escape Unicode characters in `languages.yaml`
Add `python3 -m script.intentfest language_table` to generate the Markdown table of languages for the README
=> Add script to generate language table

.github/workflows/ci.yaml, CODEOWNERS, languages.yaml, script/intentfest/codeowners.py, script/intentfest/util.py
- Add new `codeowners` command to generate the `CODEOWNERS` file
- Check the file is up to date as part of CI
- Update `languages.yaml` with all code owners
=> generate codeowners based on languages.yaml

README.md, script/intentfest/website_summary.py, website/src-11ty/_data/intentSummary.json, website/src-11ty/index.html
This replaces the list in the README that we had to manually keep up to date.
=> Add language leaders to website

script/intentfest/merged_output.py, script/intentfest/util.py
This adds a new command to generate merged output as we'll need to export this repository to Home Assistant core.
```
python3 -m script.intentfest merged_output build
```
Merge approach is to first merge all files belonging to a single language, and then split them based on the domain that defines the intent.
The output for the `homeassistant` domain will also include the lists, expansion rules etc.
Marking this PR as a draft until we are sure how the HA Core part will consume this data.
=> Add command to generate merged output

sentences/pl/light_HassLightSet.yaml
Removed hardcoded entry for `Lampka nocna` (a bedside lamp) that was also a duplicate of the preceding entry.
=> [PL] removed hardcoded device name

tests/test_language_sentences.py
The old behavior tested only that the slots specified in the test file were found by the matcher. This new behavior requires all matched slots to be specified in the test file. This is to ensure correctness.
=> Expect tests to specify all matched slots

sentences/ca/fan_HassTurnOff.yaml, sentences/ca/fan_HassTurnOn.yaml, tests/ca/fan_HassTurnOff.yaml, tests/ca/fan_HassTurnOn.yaml, tests/ca/homeassistant_HassTurnOff.yaml, tests/ca/homeassistant_HassTurnOn.yaml, tests/ca/light_HassTurnOn.yaml
Catalan was testing some sentences in the wrong files. Move them to the correct place. I've removed 2 sentences that didn't make sense: "Turn on ventilator <name>" would match sentence "Turn on ventilator left ventilator"
Found by #335.
=> Re-organize tests for Catalan

tests/de/homeassistant_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml
Sentence files like `light_HassTurnOn.yaml` should only contain sentences that map to a hardcoded domain `light`. This PR makes sure that the test sentences match these. 
Found by #335.
=> Re-organize tests for German

tests/pl/homeassistant_HassTurnOff.yaml, tests/pl/homeassistant_HassTurnOn.yaml, tests/pl/light_HassTurnOff.yaml, tests/pl/light_HassTurnOn.yaml
Sentence files like `light_HassTurnOn.yaml` should only contain sentences that map to a hardcoded domain `light`. This PR makes sure that the test sentences match these. 
Found by #335.
=> Re-organize tests for Polish

tests/test_language_intents.py, tests/test_language_sentences.py
Sentence files like `fan_HassTurnOn.yaml` should only contain sentences that map to a hardcoded domain `fan`. This PR makes sure that the test sentences also expect the domain to be set to `fan`.
=> Validate that domain tests only test domain sentences

sentences/fr/homeassistant_HassTurnOff.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, tests/ca/homeassistant_HassTurnOff.yaml, tests/ca/light_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOn.yaml, tests/test_language_intents.py, tests/test_language_sentences.py
Make sure that files like `homeassistant_HassTurnOff.yaml` do not test for sentences defined in `light_HassTurnOff.yaml`.
=> Validate non domain files

sentences/pl/cover_HassOpenCover.yaml
`Rozsłoń` is actually an archaic form and is not used in Polish anymore. Replaced it with `Odsłoń`.
=> [PL] Update cover opening sentences

sentences/bg/_common.yaml
My initial commit of `_common.yaml` in bulgarian language.
=> Initial commit of _common.yaml in bulgarian language

script/intentfest/validate.py, tests/ca/cover_HassOpenCover.yaml, tests/en/cover_HassCloseCover.yaml, tests/en/cover_HassOpenCover.yaml, tests/es/cover_HassCloseCover.yaml, tests/es/cover_HassOpenCover.yaml, tests/fr/cover_HassCloseCover.yaml, tests/fr/cover_HassOpenCover.yaml, tests/hu/cover_HassOpenCover.yaml, tests/pl/cover_HassCloseCover.yaml, tests/pl/cover_HassOpenCover.yaml, tests/pt/cover_HassCloseCover.yaml, tests/pt/cover_HassOpenCover.yaml, tests/ru/cover_HassCloseCover.yaml, tests/ru/cover_HassOpenCover.yaml, tests/test_language_sentences.py, tests/uk/cover_HassCloseCover.yaml, tests/uk/cover_HassOpenCover.yaml
We allowed both a value or a dictionary containing a `value` key for expected slot values. In practice, we don't support any other keys but `value` so we could just always use the shortcut.
This updates our validation to enforce shortcuts and converts all test files to shortcuts.
=> Slot values no dict

sentences/lv/_common.yaml, sentences/lv/homeassistant_HassTurnOff.yaml, sentences/lv/homeassistant_HassTurnOn.yaml
Added more sentences and stuff to _common and made changes based on the [comment on my last PR](https://github.com/home-assistant/intents/pull/397#issuecomment-1373790031).  
Though, not sure if I need to translate other `expansion_rules`' keys (`set`, `close`, `open`, etc.)  too to the native language.
=> [LV] Add more to common

sentences/sv/_common.yaml, tests/sv/_fixtures.yaml, tests/sv/climate_HassClimateGetTemperature.yaml, tests/sv/fan_HassTurnOn.yaml, tests/sv/homeassistant_HassTurnOff.yaml, tests/sv/homeassistant_HassTurnOn.yaml, tests/sv/light_HassLightSet.yaml, tests/sv/light_HassTurnOff.yaml
Fixed overlapping area names lik kök and köket to only one per room and using the shortest form for the room name (to allow testing of room name expantions  like rum->rummet garage->garagets kök->kökets)
Entity id's where a mix of swedish and english, converted all these to english. As it feels more natural to have "variable" names in english for me.
Updated all tests to run with the new fixtures and the test runs.
=> [SV] Streamline language of fixtures

languages.yaml, responses/kn/HassClimateGetTemperature.yaml, sentences/kn/_common.yaml, sentences/kn/climate_HassClimateGetTemperature.yaml, sentences/kn/climate_HassClimateSetTemperature.yaml, sentences/kn/cover_HassCloseCover.yaml, sentences/kn/cover_HassOpenCover.yaml, sentences/kn/fan_HassTurnOff.yaml, sentences/kn/fan_HassTurnOn.yaml, sentences/kn/homeassistant_HassTurnOff.yaml, sentences/kn/homeassistant_HassTurnOn.yaml, sentences/kn/light_HassLightSet.yaml, sentences/kn/light_HassTurnOff.yaml, sentences/kn/light_HassTurnOn.yaml, tests/kn/_fixtures.yaml, tests/kn/climate_HassClimateGetTemperature.yaml, tests/kn/climate_HassClimateSetTemperature.yaml, tests/kn/cover_HassCloseCover.yaml, tests/kn/cover_HassOpenCover.yaml, tests/kn/fan_HassTurnOff.yaml, tests/kn/fan_HassTurnOn.yaml, tests/kn/homeassistant_HassTurnOff.yaml, tests/kn/homeassistant_HassTurnOn.yaml, tests/kn/light_HassLightSet.yaml, tests/kn/light_HassTurnOff.yaml, tests/kn/light_HassTurnOn.yaml
In #195 we accidentally added the Kannada language under ka, which is the code for Georgia. In #486 we repurposed ka again for Georgian, so this PR adds Kannada back as kn.
=> Add Kannada correctly under kn

sentences/nl/_common.yaml, sentences/nl/climate_HassClimateGetTemperature.yaml
`de` should not have been included in these sentences, this is already included in the expansion_rule.
Also removed the parentheses in the `lamp` expansion rule
=> [NL] Remove "de" from GetTemperature

script/intentfest/parse.py, script/intentfest/sample.py, script/intentfest/util.py, script/intentfest/validate.py, tests/test_language_sentences.py
Allows `requires_context` and `excludes_context` to be used in intents. These can be used to prevent general intents (e.g., `HassTurnOn`) from matching cases where specific intents are desired (e.g., `HassOpenCover`).
See: https://github.com/home-assistant/intents/issues/574#issuecomment-1379426746
=> Add domain context to test entities and allow requires/excludes context

responses/en/HassTurnOff.yaml, script/package
English area responses had wrong slot "name".
=> Fix area responses

.github/workflows/gh-pages.yml, .github/workflows/nightly.yaml
There are multiple forks of the project, and each of them will run Actions by default.
Unless explicit confirmation or change from the user, I expect that these jobs should run only in here.
Confirm that this is not blocking anyone from the team, feel free to close if not needed.
=> Run Actions only in main repository

sentences/sv/_common.yaml
Added the skip word "kan du" which is superfluous.
=> [SV] Added skip word.

sentences/it/_common.yaml
Having used the generic term `"ventilazione"` for `fans_area` in responses (#746), I'm afraid the user may pick up the response and use the same term as the assistant in formulating the intent. That's why this PR adds `"ventilazione"` as a synonym in `<fan>`.
=> [IT] Fan intents consistent with responses

sentences/nl/homeassistant_HassTurnOn.yaml
Replaced `doe` and `(doe | mogen)` with `<doe>` expansion rules, as words such as `maak` and `zet` would likely be used in the sentences aswell. For example: `zet de gordijnen open in de keuken`. Also added `vitrage`, `vitrages` and `schermen` as synonyms for `gordijnen`.
=> More naturally occurring sentences

responses/ro/HassTurnOff.yaml, responses/ro/HassTurnOn.yaml, sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml
Cred că sună mai bine ”am aprins lumina” și ”am stins lumina” decât ”am pornit lumina„ și ”am oprit lumina”. Dacă pentru ”cover” s-au pus răspunsuri personalizate, cred că s-ar putea face acest lucru și pentru lumini. Cred că soluția ideală ar fi să se facă o corespondență între cuvântul cu care se face cererea cu cel care se răspunde (de exemplu aprinde→am aprins, pornește→am pornit ), dar deocamdată încercăm să facem ce ni s-a pus la dispoziție să sune cât mai natural.
=> [RO] Updated responses and sentences for ligths

intents.yaml, script/intentfest/merged_output.py, script/intentfest/validate.py
Do not include temperature sentences, as we don't support those intents. This is causing users to get "intent not supported" errors instead of "I don't understand"
=> Omit sentences for unsupported intents from merged output

sentences/nl/_common.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml
It's polite to say 'graag' when interacting with an assistant. I believe this should be added to the skip words.
Also: it's currently not possible to say something like: plafondlamp woonkamer aan without saying 'doe' first. Sso I added that to the turnOn and turnOff files. I'm not sure if I did this correct, so please decline if it's not how it should be.
=> Added graag to skip words and make doe optional

script/intentfest/validate.py, tests/test_language_intents.py
Allow tests.intent.context in test schema - `python3 -m script.intentfest validate --language ro` produces errors if context is given in tests as per https://github.com/home-assistant/intents/pull/626
Required context should be inferred in tests, so that `slot_combinations` is met.
=> Fix some dependencies regarding context

sentences/cs/_common.yaml
=> Add 've' option to area in Czech.

requirements.txt
Fixes a bug in skip words, where `ignore_whitespace` was not being respected.
=> Bump hassil to 1.0.2 (skip words can ignore whitespace)

sentences/ru/homeassistant_HassTurnOff.yaml, sentences/ru/light_HassLightSet.yaml, tests/ru/climate_HassClimateGetTemperature.yaml
As I pointed in #919, preps `[в|на]` already defined in `_common.yaml` and shouldn't be duplicated in other sentences files.
=> [RU] Remove duplicated preps from <area> parts

intents.yaml
Add `HassGetState` to `intents.yaml`. This intent is currently being worked on in Home Assistant.
=> Add description of HassGetState intent

sentences/nl/_common.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
@TheFes discovered that you can currently not say `Zou de eettafellamp aan mogen?`. This is because `je, jij or u` is mandatory right now. This PR makes it optional.
I also added two tests for the new expansion rule.
=> Make je, jij and u optional

sentences/nl/_common.yaml
Even though fan is not a Dutch word, it's still being used often in a Dutch sentence. Can we add fan[s] to the ventilator expansion rule?
Also, I'd like to add `lichtsterkte` for the helderheid expansion rule and `opwaarts` for the open expansion rule.
=> [NL] Add expansion rule words

responses/nb/HassGetState.yaml, sentences/nb/_common.yaml, sentences/nb/homeassistant_HassGetState.yaml, tests/nb/_fixtures.yaml, tests/nb/homeassistant_HassGetState.yaml, tests/nb/homeassistant_HassTurnOff.yaml, tests/nb/homeassistant_HassTurnOn.yaml
This is the first pass of a translation to NB. Note that the states still return "on/off", and that some of the tests still says "soveromslampe is off". Covers is not part of this PR (except an update of _common to prepare for different kind of covers.
=> [NB] HassGetState - first pass

script/intentfest/validate.py, shared/__init__.py
This adds the ability to include translated state names in test fixtures. For example:
```yaml
entities:
- name: "lustra"
id: light.bedroom_lamp
area: bedroom
state:
in: "oprit"
out: "off"
```
The `in` part of `state` is the human/translated name of the state, and `out` is the Home Assistant state name.
=> Allow in/out for states in test fixtures.

tests/nb/cover_HassTurnOff.yaml, tests/nb/cover_HassTurnOn.yaml
Note that device class "garage" has not yet been translated by the system and will show as "garage ble lukket". I assume the live environment will use the translated version.
=> [NB] Correct translation of autogenerated cover tests

sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
Using "aprinde"/"stinge" for lights instead of "porneste"/"opreste" for other things.
=> [RO] Added light-specific responses

responses/ar/HassClimateGetTemperature.yaml, responses/ar/HassClimateSetTemperature.yaml, responses/ar/HassLightSet.yaml, responses/ar/HassTurnOff.yaml, responses/ar/HassTurnOn.yaml, script/intentfest/add_language.py, script/intentfest/website_summary.py, sentences/ar/_common.yaml, website/script/build, website/script/develop, website/src-11ty/_data/intentSummary.json
With abbreviated responses + templates, there are several responses that now exactly match the English "translations". For example, `{{ state.state_with_unit }}` as a response to `HassGetTemperature`
For the website summary, I am now looking for a "TODO" in the response to indicate it is not yet translated. This is added automatically by `add_language.py`.
=> Check for TODO in responses instead of directly comparing to English

responses/nb/HassTurnOff.yaml, responses/nb/HassTurnOn.yaml, tests/nb/cover_HassTurnOff.yaml, tests/nb/cover_HassTurnOn.yaml, tests/nb/homeassistant_HassTurnOff.yaml, tests/nb/homeassistant_HassTurnOn.yaml
Ref https://developers.home-assistant.io/docs/voice/intent-recognition/style-guide/ and [EN] example and proposal on Discord.
Please consider the following carefully in reviewing this PR. I considered a few different responses to meet the shorter and more accurate feedback to actions. 
We are advised not to repeat slots.name/slots.area, and to give a concise answer in the present tense and active voice. By removing slots.name / slots area, I am not certain whether it is correct to answer "It's on" or "It's on". The [ENG] example not not fully meet the style guide, but is my preferred example to follow. Here we have several options (this PR reflects the last one):
HassTurnOn: (keep slots.name/area to ease grammar challenges)
default: {{ slots.name }} er slått på
lights_area: Lys i {{ …
=> [NB] Shorter response according to style guide

responses/ro/HassGetState.yaml, responses/ro/HassLightSet.yaml, responses/ro/HassTurnOff.yaml, responses/ro/HassTurnOn.yaml, sentences/ro/_common.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, sentences/ro/climate_HassClimateSetTemperature.yaml, sentences/ro/cover_HassGetState.yaml, sentences/ro/cover_HassTurnOff.yaml, sentences/ro/cover_HassTurnOn.yaml, sentences/ro/fan_HassTurnOff.yaml, sentences/ro/fan_HassTurnOn.yaml, sentences/ro/homeassistant_HassGetState.yaml, sentences/ro/light_HassGetState.yaml, sentences/ro/light_HassLightSet.yaml, sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml, tests/ro/cover_HassGetState.yaml, tests/ro/cover_HassTurnOff.yaml, tests/ro/cover_HassTurnOn.yaml, tests/ro/fan_HassTurnOff.yaml, tests/ro/fan_HassTurnOn.yaml, tests/ro/homeassistant_HassGetState.yaml, tests/ro/light_HassGetState.yaml, tests/ro/light_HassLightSet.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
Drastically reduced the amount of grammatically incorrect sentences that are allowed by simply separating the singular/plural forms of domains, device classes, states etc. and only allowing correctly worded sentences.
=> [RO] Grammar fixes

responses/ro/HassClimateGetTemperature.yaml, responses/ro/HassClimateSetTemperature.yaml, responses/ro/HassGetState.yaml, sentences/ro/climate_HassClimateGetTemperature.yaml, sentences/ro/climate_HassClimateSetTemperature.yaml, tests/ro/_fixtures.yaml, tests/ro/binary_sensor_HassGetState.yaml, tests/ro/climate_HassClimateGetTemperature.yaml, tests/ro/climate_HassClimateSetTemperature.yaml, tests/ro/cover_HassGetState.yaml, tests/ro/fan_HassTurnOff.yaml, tests/ro/fan_HassTurnOn.yaml, tests/ro/homeassistant_HassGetState.yaml, tests/ro/light_HassTurnOff.yaml, tests/ro/light_HassTurnOn.yaml
Follow the style guide to provide a short and concise answer
"Nu, este X" implies that the state in question is in singular, which is not always the case. The "but" (="ci") is more impersonal and lacks cardinality.
=> [RO] Cleanup

sentences/nb/light_HassTurnOff.yaml, sentences/nb/light_HassTurnOn.yaml, tests/nb/light_HassTurnOff.yaml, tests/nb/light_HassTurnOn.yaml
This PR will fix an issue with turning on/off lights.
When I ran this command:
```bash
python3 -m script.intentfest parse --language nb --sentence "skru på lys i garasje"
```
I got this error:
```bash
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/stale/private_projects/home-assistant/intents/script/intentfest/__main__.py", line 29, in <module>
sys.exit(main())
File "/Users/stale/private_projects/home-assistant/intents/script/intentfest/__main__.py", line 24, in main
return module.run()
File …
```
=> [NB] Fix light response bug

responses/nl/HassTurnOff.yaml, responses/nl/HassTurnOn.yaml, sentences/nl/_common.yaml, sentences/nl/climate_HassClimateGetTemperature.yaml, sentences/nl/climate_HassClimateSetTemperature.yaml, sentences/nl/cover_HassGetState.yaml, sentences/nl/cover_HassTurnOff.yaml, sentences/nl/cover_HassTurnOn.yaml, sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, sentences/nl/light_HassLightSet.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, sentences/nl/lock_HassTurnOff.yaml, sentences/nl/lock_HassTurnOn.yaml, sentences/nl/scene_HassTurnOn.yaml, sentences/nl/script_HassTurnOn.yaml, tests/nl/lock_HassTurnOff.yaml, tests/nl/lock_HassTurnOn.yaml
* Added intents for opening/closing locks by name
* Added intents for opening/closing all locks in an area
* Made a minor change the polite ending of sentences `[zouden|willen] [<doe>]` is changed to `[[zouden|willen] <doe>]` to treat it as one optional part (this causes the changes in the other files)
* replaced `in <area>` for all sentences to `<in> <area>` to allow `op zolder`, `bij de schoorsteen`
I already used the new expansion rules from #1174 
For the named intents a reference to `<slot>` is required in case `[doe] open/sluit/doe dicht` is used to avoid confusion with doors
For the area intents you can refer to `deur[en]` instead of `<slot>` in case `vergrendelen|ontgrendelen|op slot|van slot` is used. You can only refer to `<slot>` for `open|sluiten|dicht doen|open doen`.
=> [NL] Support for opening and closing locks

sentences/nl/_common.yaml, sentences/nl/binary_sensor_HassGetState.yaml, sentences/nl/cover_HassGetState.yaml
Introduced a new expansion_rule `<name_are>`
It has 3 frequently used options for the combination of the name and the area.
It has 2 advantages
* it simplifies the sentences (as all expansion rules do)
* it avoids grammatically incorrect versions or double usage of area around the name, as the 3 options are now separated, and not in one line which would allow all to be used.
=> [NL] Expansion rules <name_area> and <met>

sentences/nb/_common.yaml, sentences/nb/cover_HassGetState.yaml, sentences/nb/homeassistant_HassGetState.yaml, sentences/nb/lock_HassGetState.yaml, tests/nb/lock_HassGetState.yaml
I have, as per prior dialog, replaces "hva" with "hvilke". "Hva" is used in some sentences without the use of expansion rules.
=> [NB] Correct hvilke vs hva

responses/fr/HassGetState.yaml, sentences/fr/homeassistant_HassGetState.yaml, tests/fr/binary_sensor_HassGetState.yaml, tests/fr/cover_HassGetState.yaml, tests/fr/homeassistant_HassGetState.yaml, tests/fr/lock_HassGetState.yaml
Added a few sentences that feel more natural when trying to get the state of a sensor.
A few examples:
- Donne moi la température extérieure
- Donne moi la valeur de ...
- etc...
I also added the feminine of "Quel est" ...
Today if you ask assist "Quelle est la temperature extérieure?", no intent will match because the STT understands feminine but the only intent available is masculine "Quel est ..."
I also removed the word "Appareil" from every response to simplify the answers
=> [FR] more sentence for Get State. And simplification of some answers

sentences/de/homeassistant_HassTurnOff.yaml, sentences/de/homeassistant_HassTurnOn.yaml
Exclude `sensor` and `binary_sensor` from `homeassistant_HassTurnOff` and `homeassistant_HassTurnOn` as they are in English.
=> [DE] exclude sensor and binary sensor from homeassistant_HassTurnOff and homeassistant_HassTurnOn

sentences/en/homeassistant_HassGetState.yaml, tests/en/homeassistant_HassGetState.yaml
An attempt to fix #1343 
The short form of "what is" ("what's") was missing from the sentences for the `homeassistant_HassGetState` intent.
=> [EN] Add short form of what's in HassGetState

sentences/de/_common.yaml, sentences/de/homeassistant_HassTurnOff.yaml, sentences/de/homeassistant_HassTurnOn.yaml, tests/de/homeassistant_HassTurnOff.yaml, tests/de/homeassistant_HassTurnOn.yaml
Add `<machen>` for more possible commands and `<schalten>` for the sake of reusability.
=> [DE] improve homeassistant_HassTurnOn and homeassistant_HassTurnOff

responses/fr/HassLightSet.yaml, responses/fr/HassTurnOff.yaml, responses/fr/HassTurnOn.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/fan_HassTurnOff.yaml, sentences/fr/fan_HassTurnOn.yaml, sentences/fr/homeassistant_HassTurnOff.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, tests/fr/cover_HassTurnOff.yaml, tests/fr/cover_HassTurnOn.yaml, tests/fr/fan_HassTurnOff.yaml, tests/fr/fan_HassTurnOn.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml
👋 
As per [this discussion](https://github.com/home-assistant/intents/discussions/1354), and as per [this guide](https://developers.home-assistant.io/docs/voice/intent-recognition/style-guide/), I removed all mentions of {name} and {area} in the 3 most used intents
- HassLightSet
- HassTurnOff
- HassTurnOn
The answers are now simpler and more generic, so they are cached better (among other benefits)
I'll try to do the other intent whenever I have time 🙏
=> [FR] Match french answers to the official Response Style Guide (part 1)

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/fr/binary_sensor_HassGetState.yaml
Takes into account exchanges in PR [[fr] New expansion rules and split binary_sensors intents](https://github.com/home-assistant/intents/commit/208ad67e6b20bb3313896a8a10ae831303e3d830)
=> [fr] New expansion rules and split binary_sensors intents

sentences/el/_common.yaml, sentences/el/homeassistant_HassGetState.yaml, tests/el/_fixtures.yaml, tests/el/homeassistant_HassGetState.yaml
This PR adds the missing el sentences and tests for homeassistant_HassGetState.
Btw I'm generally trying to be consistent with the current translations of state values. But I noticed that the on/off states for light entities are currently translated as:
- on: Ενεργό
- off: Ανενεργό
I don't think that anyone really says "το φως είναι ενεργό", the usual phrases are:
- το φως είναι ανοικτό / κλειστό
- το φως είναι αναμμένο / σβηστό
Maybe we can try to fix this? Should this change be done in lokalise?
=> [el] Add sentences/test for homeassistant_HassGetState

requirements.txt, script/intentfest/validate.py, tests/test_language_intents.py
Bump hassil to 1.1.0 (Local expansion rules)
Implement logic that allows access to expansion rules in the context of an intent
We could easily have reusable sentences if we were able to define or overwrite some expansion rules locally. Imagine the following scenario:
Most nominal binary sensor sentences sound something like
```
- is [<some_particular_device_class>] <name> {bs_device_class_state:state} [in <area>]
- is <name> [<some_particular_device_class>] {bs_device_clas0s_state:state} [in <area>]
- is [<some_particular_device_class>] <name> in <area> {bs_device_class_state:state}
- is <name> [<some_particular_device_class>] in <area> {bs_device_class_state:state}
```
but it's hard to write those variations for each device_class.
Imagine the following expansion rule:
``` …
```
=> Local expansion rules

requirements.txt
Bump hassil library to version 1.2.0: https://github.com/home-assistant/hassil/compare/v1.1.0...v1.2.0
=> Bump hassil to 1.2.0

requirements.txt, sentences/bg/cover_HassTurnOff.yaml, sentences/bg/cover_HassTurnOn.yaml, sentences/he/light_HassLightSet.yaml, sentences/vi/fan_HassTurnOff.yaml, sentences/vi/fan_HassTurnOn.yaml, tests/bg/cover_HassTurnOff.yaml, tests/bg/cover_HassTurnOn.yaml, tests/bg/homeassistant_HassTurnOff.yaml, tests/bg/homeassistant_HassTurnOn.yaml, tests/he/homeassistant_HassTurnOff.yaml, tests/he/homeassistant_HassTurnOn.yaml, tests/he/light_HassLightSet.yaml, tests/hr/light_HassLightSet.yaml, tests/ka/light_HassTurnOff.yaml, tests/ka/light_HassTurnOn.yaml, tests/ms/cover_HassTurnOff.yaml, tests/ms/cover_HassTurnOn.yaml, tests/ms/fan_HassTurnOff.yaml, tests/ms/fan_HassTurnOn.yaml, tests/ms/homeassistant_HassTurnOff.yaml, tests/ms/homeassistant_HassTurnOn.yaml, tests/vi/fan_HassTurnOff.yaml, tests/vi/fan_HassTurnOn.yaml
1. Upgrade to hassil 1.2.2 which contains bugfixes: https://github.com/home-assistant/hassil/compare/v1.2.1...v1.2.2
2. Fix incorrect slot values exposed by the bug fixes
In previous hassil versions, hard-coded slot values always overrode the slot values discovered during recognition. This was fixed in 1.2.2.
=> Bugfixes from hassil 1.2.2

intents.yaml, requirements.txt, responses/README.md, responses/en/HassShoppingListAddItem.yaml, script/intentfest/validate.py, sentences/en/_common.yaml, sentences/en/shopping_list_HassShoppingListAddItem.yaml, tests/en/shopping_list_HassShoppingListAddItem.yaml
Using the new [wildcards](https://github.com/home-assistant/hassil/pull/56) feature of hassil, this PR adds support for the `HassShoppingListAddItem` intent (English) and adds wildcards to the validation logic.
Phrases like "add apples to the shopping list" will work as expected. However, "add apples and bananas to the shopping list" will add a single item named "apples and bananas". Splitting conjunctions may be done in the future, but this behavior is acceptable for now.
=> Add HassShoppingListAddItem intent + wildcards

script/intentfest/validate.py
With the introduction of permutations in hassil 1.2.0 (#1465), the semicolon character is now a valid character in sentences.
This PR updates the validation script called when linting in order to allow semicolons
=> Fix validation for permutations

responses/ru/HassShoppingListAddItem.yaml, sentences/ru/_common.yaml, sentences/ru/shopping_list_HassShoppingListAddItem.yaml, tests/ru/shopping_list_HassShoppingListAddItem.yaml
Leading spaces in slots complicate testing slightly, as sometimes they're present, sometimes not. Are they really necessary?
I've chosen within this particular intent for Russian to run with `<item>` in accusative case (винительный падеж) as that form in particular is useful both in a sentence and response — but isn't as great at getting displayed in the list (which normally uses nominative, именительный).
It would be the English equivalent of having a list that looks kinda like this:
- of potatoes
- of cheese
- of bread
…only in Russian that "of" being expressed as a particular form of the item. It's that same feeling of something missing at the front of it. Could feasibly be fixed with the right heading like "Top up supplies:" that flows nicely into "…of `<item>`" which I find a-ok. …
=> Add basic shopping list sentences for Russian

sentences/cs/_common.yaml
Some error responses in Czech are not written in neutral grammatical gender, sounding weird when female voice is used for TTS.
=> [cs] Make error responses gender neutral

sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Following the issue https://github.com/home-assistant/intents/issues/1509, it seems that under some conditions the sentence in 
french "allumer les lumières du salon" is not recognized.
the problem comes from the setting **name: all** in _light_HassTurnOn.yaml_ and _light_HassTurnOff.yaml_
=> fix control lights of a room

sentences/en/_common.yaml, sentences/en/sensor_HassGetState.yaml, tests/en/_fixtures.yaml, tests/en/sensor_HassGetState.yaml
Added sentences to get sensors by name for (almost) all `device_class`es from here https://www.home-assistant.io/integrations/sensor/
=> [EN] HassGetState for sensors with different device_class

responses/en/HassGetState.yaml, tests/en/binary_sensor_HassGetState.yaml, tests/en/cover_HassGetState.yaml, tests/en/homeassistant_HassGetState.yaml, tests/en/lock_HassGetState.yaml
**Query**: "are all windows closed?"
**Answer**: "No, Living Room Window Left and Shed Window not"
**Query**: "are all water sensors wet?"
**Answer**: "No, Kitchen leak sensor not"
**Query**: "are all windows closed?"
**Answer**: "No, Living Room Window Left and Shed Window are not closed"
**Query**: "are all water sensors wet?"
**Answer**: "No, Kitchen leak sensor is not wet"
=> Fix "all" response grammar and include the state

responses/cs/HassTurnOff.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
This should workaround #1471 by adding word `světlo` to ambiguous intents . Commands `rozsviť/zhasni` can be still used without `světlo`, as they're not ambiguous.
Also `HassTurnOff` intent for "all lights" domain present in EN version has been added.
=> [cs] Fix light intents, add HassTurnOff for all lights

sentences/en/_common.yaml, sentences/en/scene_HassTurnOn.yaml, tests/en/scene_HassTurnOn.yaml
Adds alternative sentences starting with `change` and `transition` to activate scenes. Additionally adds several alternatives to allow the activation of scenes with an area slot.
=> [en] Add alternative sentences for scenes

responses/cs/HassClimateGetTemperature.yaml, responses/cs/HassClimateSetTemperature.yaml, responses/cs/HassGetState.yaml, responses/cs/HassLightSet.yaml, responses/cs/HassTurnOff.yaml, responses/cs/HassTurnOn.yaml, sentences/cs/cover_HassTurnOff.yaml, sentences/cs/cover_HassTurnOn.yaml, sentences/cs/light_HassLightSet.yaml, tests/cs/_fixtures.yaml, tests/cs/cover_HassGetState.yaml, tests/cs/cover_HassTurnOff.yaml, tests/cs/cover_HassTurnOn.yaml, tests/cs/fan_HassTurnOff.yaml, tests/cs/fan_HassTurnOn.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
This is rather a big change - it adjusts all responses to follow the official [response style guide](https://developers.home-assistant.io/docs/voice/intent-recognition/style-guide/). For English this was done in #1040 - this PR aligns (or tries to) the Czech language with that.
Although it seems detrimental by making the assistant less chatty, it improves maintainability and removes the need for adjusting for clumsy responses (with bad grammatical cases/tenses), such as those that can be seen in the removed test cases.
=> [cs] Adjust responses to follow style guide

responses/ro/HassGetState.yaml
Used mainly for custom sentences
=> [RO] HassGetState default response

sentences/ro/homeassistant_HassTurnOff.yaml, sentences/ro/homeassistant_HassTurnOn.yaml, sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml
For consistency with covers, locks etc., I've added optional [in <area>] to HassTurnOn and HassTurnOff intents for the light domain and the generic homeassistant domain.
Now you can say things like `aprinde vezoza din dormitor`, whereas until now you could only say `aprinde veioza`.
=> [RO] Add optional "din area" for lights and generic HassTurnOn/Off

sentences/en/homeassistant_HassTurnOff.yaml, sentences/en/homeassistant_HassTurnOn.yaml, sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml
For consistency with covers, locks etc., I've added optional `[in <area>]` to HassTurnOn and HassTurnOff intents for the `light` domain and the generic `homeassistant` domain.
Now you can say things like `turn off the desk lamp in the office` or `turn off the office desk lamp`, whereas until now you could only say `turn off the desk lamp`
=> [EN] Add optional "in area" to light and generic HassTurnOn/Off

intents.yaml, sentences/en/homeassistant_HassNevermind.yaml, tests/en/homeassistant_HassNevermind.yaml, tests/test_language_intents.py, tests/test_language_sentences.py
Add English support for a future HA intent: `HassNevermind`.
This intent does nothing, it's just used to be able to cancel a request by saying something like "nevermind".
Because this intent returns no slot values, some test code needed to be a bit more robust.
=> Add HassNevermind (not yet supported in HA)

sentences/fr/_common.yaml, tests/fr/light_HassTurnOn.yaml
Add more skip_words  in `_common.yaml` to allow more natural conversations with Assist (currently it's a bit too robotic):
- stp
- please
- tu peux
- peux tu
- peux-tu
=> [FR] Add skip words for more natural sentences

responses/fr/HassTurnOff.yaml, responses/fr/HassTurnOn.yaml, tests/fr/cover_HassTurnOff.yaml, tests/fr/cover_HassTurnOn.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml
I made a mistake when I tried to simplify the French responses on https://github.com/home-assistant/intents/pull/1374
For the cover domain, I kept the generic word for cover `Ouvrants`.
But the opening and closing sentences became very unnatural
- `Ouvrants ouverts`
- `Ouvrant fermés`
I checked how English dealt with this issue, as cover is also a very unusual name in the English dictionary, and they just ommit the word altogether.
So I decided to align French with English for that response too
- `Ferme less volets > Fermé`
- `Ouvre les rideaux > Ouvert`
=> Simlpify french responses for the cover domain

sentences/en/_common.yaml
Fix template to avoid incorrect sentences like "change X brightness to Npercent" without a space between `N` and percent.
=> [en] Don't produce <N>percent

sentences/ro/light_HassTurnOff.yaml, sentences/ro/light_HassTurnOn.yaml
The context-aware sentences were already in place in Romanian (see #1632) but I've added "[[from|in] here]" in the sentences.
"aprinde luminile de aici"
"stinge lumina aici"
=> [RO] Improve sentences for light_HassTurnOn/Off

requirements.txt, script/intentfest/parse.py, sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
Removing "all" from "turn on/off all lights", as this will be used to turn off all lights in the house in the future.
Additionally, this bumps to hassil 1.5.1 to allow copying `area` from context to a slot with:
```yaml
requires_context:
area:
slot: true
```
This allows fine-grained control by the templates as to whether a context value should be copied to a slot and sent along to the intent.
=> [en] Bump hassil to 1.5.1, remove "all" from light

responses/el/HassTurnOff.yaml, responses/el/HassTurnOn.yaml
The current default response is "Άνοιξαν τα φώτα στο {{ slots.name }}" ("Lights were turned on in {{ slots.name }}") resulting in nonsensical responses like "Άνοιξα τα φώτα στο καφετιέρα" ("Lights were turned on in coffee machine").
Change this to "Άνοιξε", to mimic what most other languages do.
=> [EL] Fix default response to HassTurnOn/HassTurnOff

responses/nl/HassGetState.yaml, sentences/nl/_common.yaml, sentences/nl/person_HassGetState.yaml, tests/nl/_fixtures.yaml, tests/nl/person_HassGetState.yaml
I added specific sentences for the `not_home` test, for which I specifically check on that state.
I tried just excluding everybody at home, so persons in another zone like `werk` would also be returned, by using `excludes_context`  but this also returned the persons at home
intent
```yaml
- sentences:
- "[is|zijn] <name> (niet thuis|weg)"
response: one_zone
requires_context:
domain: person
excludes_context:
state: home
slots:
domain: person
```
test (Joost has the state `home`)
```
@TheFes ➜ /workspaces/intents (nl_person_hasshetstate) $ python3 -m script.intentfest parse --language nl --sentence 'is Joost weg'
{
"text": "is Joost weg",
"match": true,
"intent": "HassGetState",
"slots": {
"name": "Joost",
"domain": "person"
},
"context": {
"domain": "person"
},
"response_key": "one_zone", …
```
=> [NL] Add person_HassGetState

sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOn.yaml
This properly fixes #1471, which was caused by the missing `requires_context` definition for the whole time. Also removing the awkward Yoda-sounding variant introduced in #1525.
=> [cs] Fix light intents clashing with generic HassTurnOn/Off

responses/sl/HassClimateGetTemperature.yaml, sentences/sl/climate_HassClimateGetTemperature.yaml, tests/sl/_fixtures.yaml, tests/sl/climate_HassClimateGetTemperature.yaml
Rewritten resonses.yaml Slovenian grammar accordingly for singular, dual and plural. Where decimals are the output is grammar compliant (3.7 degress - > 3.7 stopinj**e**). 
Added test and sentence.
=> [SL] ClimateHassGetTemperature attribute fix, added sentences and tests

sentences/en/weather_HassGetWeather.yaml, shared/__init__.py, tests/en/weather_HassGetWeather.yaml
Sentences like "what is the weather" were not working because I forgot to split them out. Additionally, the test intent "handling" logic needed to be updated to match weather entities.
=> [en] Fix weather sentences without a name

responses/ro/HassClimateGetTemperature.yaml, responses/ro/HassGetWeather.yaml, tests/ro/_fixtures.yaml, tests/ro/climate_HassClimateGetTemperature.yaml, tests/ro/weather_HassGetWeather.yaml
In Romanian, floating point numbers are formatted using a comma as a decimal separator
The TTS engines I've tested don't properly pronounce numeric values if a dot is used as a decimal separator. This PR aims to fix pronunciation issues with numerals in Romanian
Before: "-0.4 grade" -> "zero. patru grade"
After: "-0,4 grade" -> "minus zero virgula patru grade"
=> [RO] Fix temperature values for TTS

sentences/en/climate_HassClimateGetTemperature.yaml
Support sentences like "what is the name/area current temperature"
=> [EN] Add "current" as an optional temps attribute

sentences/nl/weather_HassGetWeather.yaml, tests/nl/_fixtures.yaml, tests/nl/weather_HassGetWeather.yaml
Add intent which gives the weather without providing a name for a weather entity
=> [NL] Weather intent without providing name

sentences/de/_common.yaml, tests/de/fan_HassTurnOff.yaml, tests/de/fan_HassTurnOn.yaml, tests/de/homeassistant_HassTurnOff.yaml, tests/de/homeassistant_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml
I've added an 'et' option to the expansion_rule 'schalten' because whisper often understands 'schaltet' instead of 'schalte'.
ChrM3r
=> [DE] added 'et' option to 'schalten' expansion rule + test

sentences/de/_common.yaml, tests/de/cover_HassTurnOff.yaml, tests/de/cover_HassTurnOn.yaml, tests/de/fan_HassTurnOff.yaml, tests/de/fan_HassTurnOn.yaml, tests/de/light_HassTurnOff.yaml, tests/de/light_HassTurnOn.yaml, tests/de/lock_HassTurnOff.yaml, tests/de/lock_HassTurnOn.yaml
Like in https://github.com/home-assistant/intents/pull/1663 I've added an 't' option to the expansion_rule 'machen' because whisper often understands 'macht'.
In addition to the other PR I've added all tests and this PR only contains one specific change.
ChrM3r
=> [DE] added 't' option to 'machen' expansion rule

sentences/gl/_common.yaml, sentences/gl/cover_HassTurnOff.yaml, sentences/gl/cover_HassTurnOn.yaml, sentences/gl/homeassistant_HassTurnOff.yaml, sentences/gl/homeassistant_HassTurnOn.yaml, sentences/gl/light_HassLightSet.yaml
Seems to be a common practice to use the local language for the rules' names instead of english.
=> [GL] Replace <name> expansion rule by <nome>

responses/de/HassGetState.yaml, sentences/de/_common.yaml, sentences/de/person_HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/person_HassGetState.yaml
Can get some more fine tuning but it's a start.
=> [DE] add support for person_HassGetState

responses/sl/HassGetState.yaml, responses/sl/HassGetWeather.yaml, sentences/sl/_common.yaml, sentences/sl/person_HassGetState.yaml, sentences/sl/weather_HassGetWeather.yaml, tests/sl/_fixtures.yaml, tests/sl/person_HassGetState.yaml, tests/sl/weather_HassGetWeather.yaml
Slovenian weather_HassGetWeather and person_HassGetState fix with untranslated states
As requested by @tetele in [#1768 ](https://github.com/home-assistant/intents/discussions/1768#discussioncomment-7830669)
based on https://github.com/home-assistant/intents/pull/1767
=> [SL] ] Fix intents with untranslated states

sentences/fr/_common.yaml, sentences/fr/binary_sensor_HassGetState.yaml, sentences/fr/climate_HassClimateGetTemperature.yaml, sentences/fr/climate_HassClimateSetTemperature.yaml, sentences/fr/cover_HassGetState.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/fan_HassTurnOff.yaml, sentences/fr/fan_HassTurnOn.yaml, sentences/fr/homeassistant_HassGetState.yaml, sentences/fr/homeassistant_HassTurnOff.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, sentences/fr/lock_HassGetState.yaml, sentences/fr/lock_HassTurnOff.yaml, sentences/fr/lock_HassTurnOn.yaml, sentences/fr/person_HassGetState.yaml, sentences/fr/scene_HassTurnOn.yaml, sentences/fr/script_HassTurnOn.yaml, sentences/fr/sensor_HassGetState.yaml, sentences/fr/weather_HassGetWeather.yaml
Co-worked with @jlpouffier to improve expansions rules
**Before**
```yaml
sentences: 
- allume la lumière dans <area>
```
Area variable is hidden in the expansion rule
**After**
```yaml
sentences: 
- allume la lumière dans [<le>]{area}
```
Area variable is now explicit in the sentence
**Before**
```yaml
sentences: 
- allume la lumière dans <le>{area}
```
We don't know that "le" is optional because it's hidden in the expansion rule
**After**
```yaml
sentences: 
- allume la lumière dans [<le>]{area}
```
We know that "le" is optional because it's explicit in the sentence
**Before**
```yaml
expansion_rules:
fenetre: "(fen(e|ê)tre[s]|baie[s]|v(e|é)lux|lucarne[s])"
```
**After**
```yaml
expansion_rules:
fenetre: "(fenetre[s]|fenêtre[s]|baie[s]|velux|vélux|lucarne[s])"
```
=> Improve expansion rules for french intents

sentences/fr/_common.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/homeassistant_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
- Removed `le`, `la`, etc from expansion rules `lumiere` and `lumieres`. We have an expansion rule `le` for that
- All intents use expansion rules for verbs. So that we are sure the infinitive and imperative forms work
- _Baisse la luminosité ...._
- _Baisser la luminosité ...._
- Added a comment in front of all sentences to help the reader and contributor understand at least one match
New sentences to turn on, off, and set brightness of all areas.
A few examples
- _Allume le bureau_
- _Éteins le bureau_
- _Baisse le bureau à 20%_
- _Monte le salon à 100%_
- `<ouvre> [<le>]{name}` was defined without context. You were able to "open" lights, or vacuums
- Added cover context
- Moved to cover file
- Turning off all lights in the home with missing a slot (`name: all`)
We cannot survive with …
=> [fr] Light intents rework 20231221

responses/he/HassClimateGetTemperature.yaml, tests/he/_fixtures.yaml, tests/he/climate_HassClimateGetTemperature.yaml
The Hebrew response for `HassClimateGetTemperature` returned the climate's state, rather than the current temp.
Also, when a sentence in Hebrew starts with a number, or an english letter, it jumbles it.
Fixed the value and added the name of the area to the beginning of the sentence to avoid it getting jumbled.
The new sentence translates to  "In {area} {temperature} degrees" (no need for ["it is"] between area and temperature in Hebrew)
=> Fix Hebrew response for HassClimateGetTemperature

sentences/fr/todo_HassListAddItem.yaml, tests/fr/_fixtures.yaml, tests/fr/todo_HassListAddItem.yaml
Sentences include:
- _Ajoute du pain à la liste des courses_
- _Met des oeufs dans la liste des courses_
- _Rajoute du lait sur la liste des courses_
- _ajoute réparer le volet aux tâches_
- _ajoute réparer le volet à la liste des tâches_
Features
- Infinitive and Imperatif forms for the action verbs _(Ajoute, Ajouter)_
- Singular and Plural, masculine, feminine for the item _(Ajoute du pain, de la bière, des craquottes, de l'eau, etc)_
- Singular and Plural, masculine, feminine for the list _(À la liste de courses, aux taches, au livre des dolenances, etc)_
What do we do with `HassShoppingListAddItem` ?
Now that all shopping lists are also todo entities, I think we could safely remove this intent completely from our intent collection.
For now, I did not touch it.
=> [FR] TODO improvements  20240101

sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, sentences/nl/light_HassTurnOff.yaml, sentences/nl/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml, tests/nl/light_HassTurnOff.yaml, tests/nl/light_HassTurnOn.yaml
The way context awareness is processed changed recently (See commit for EN sentences here https://github.com/home-assistant/intents/commit/eda5cba86371a7145124b1aa4d5c19e2351f9d6f) 
I mentioned that FR and NL were still using the old syntax to @synesthesiam and we agreed that we will try to fix this before tomorrow's release.
We now need to explicitly tell in the sentence to add the area in a slot as such:
```yaml
requires_context:
area:
slot: true
```
_This is what changed in the sentences._
The tests have been updated to accommodate the additional slot passed to the intent.
=> Fix context awareness

intents.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/fan_HassTurnOff.yaml, sentences/fr/fan_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, sentences/fr/lock_HassTurnOff.yaml, sentences/fr/lock_HassTurnOn.yaml, tests/fr/cover_HassTurnOff.yaml, tests/fr/cover_HassTurnOn.yaml, tests/fr/fan_HassTurnOff.yaml, tests/fr/fan_HassTurnOn.yaml, tests/fr/homeassistant_HassTurnOff.yaml, tests/fr/homeassistant_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml, tests/fr/lock_HassTurnOff.yaml, tests/fr/lock_HassTurnOn.yaml
Allow targeting all entities from a domain without setting `name: all` (e.g. turning on/off all lights of the house) by adding `domain_only` slot combination.
@synesthesiam Not sure if a core update is required for that so I put this PR in draft 🙂
I also noticed that slot combinations were missing for `HassTurnOff`.
=> [FR] Remove name all slot for french intents

sentences/en/cover_HassTurnOff.yaml, sentences/en/cover_HassTurnOn.yaml, sentences/en/fan_HassTurnOff.yaml, sentences/en/fan_HassTurnOn.yaml, sentences/en/light_HassLightSet.yaml, sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml, tests/en/cover_HassTurnOff.yaml, tests/en/cover_HassTurnOn.yaml, tests/en/fan_HassTurnOff.yaml, tests/en/fan_HassTurnOn.yaml, tests/en/light_HassLightSet.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
Added the area-aware ability to all action intents, not just `light_HassTurnXX` ones.
Also optimized the `light` sentences, as completely optional components in a permutation may result in duplicate matches.
=> [EN] Context area aware intents

sentences/en/_common.yaml
Friendlier error messages in the context of https://github.com/home-assistant/core/pull/107151
I picked "called" instead of "named" to hint that aliases are included as well, as opposed to just names.
I picked "I am not aware" instead of "I couldn't find" as I think that, traditionally, inability to find something hints to its non-existence, whereas the issue here might be a lack of exposure which can be fixed by exposing an entity to Assist.
I used `in the {{area}} area` instead of `in {{area}}` because of prepositionless area names like `Outside` or other area names that might require different prepositions, like `[on the] Lawn`, `[on the] Porch` etc.
=> [EN] Better error messages

sentences/fr/light_HassLightSet.yaml
@piitaya very strange PR, that requires a few explanations
So we have a bug on our French intents today on the intent `light_HassLightSet`.
As you can see here, the intent can be targeted by any entity, of any domain:
So my initial plan was to add 
```yaml
requires_context:
domain: light
``` 
on any sentences targeting a `{name}`
and add
```yaml
slots:
domain: light
```
on any sentences targeting an `{area}`
The thing is, the test engine fails if I add a `slot` on the `sentence` file with this:
```
FAILED tests/test_language_intents.py::test_light_HassLightSet[fr] - AssertionError: File light_HassLightSet.yaml should only have sentences without a domain slot
```
My gues is that, if you target an area, the `domain` `light` is already targeted on the intent itself and you do not need to add …
=> [FR] Add context light to sentence targeting `{name}`

sentences/fr/_common.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Added area context awareness to light brightness and light colour setting
=> Add context awareness to brightless and color

sentences/fr/_common.yaml, tests/fr/cover_HassTurnOn.yaml
We renamed `area` to `pièce` instead of `zone`.
`zone` is already used for `zone` (An external concept like your kid's school or your work place)
We felt the wording `Aucun appareil ou entité appelé ...` was a bit heavy for a voice interface so we simplified it to `je ne connais pas l'appareil ...`
The biggest change is that we now translate `domains` and `device_classes` for some errors.
Here are a few examples of interactions you will get from this PR:
- `Ouvre les rideaux du jardin`
- Before:  `Jardin ne continent pas de curtain`
- Now ✨: `Désolé, je n'ai pas trouvé de rideaux dans jardin`
- Allume les lumières du jardin
- Before:  `Jardin ne continent pas de light`
- Now ✨: `Désolé, je n'ai pas trouvé de lumières dans jardin`
`{area}` cannot be prefaced with the correct article. 
We …
=> [FR] Error message improvements

sentences/en/scene_HassTurnOn.yaml, tests/en/scene_HassTurnOn.yaml
Too many optional components in sentences for `scene` activation
Also, one set of sentences lacked the `requires_context: { domain: "scene" }` clause, making it match against other unintended custom sentences. [Details here](https://discord.com/channels/330944238910963714/646814454063038466/1199845994439905320).
=> [EN] Fix scene sentences

sentences/fr/_common.yaml
To be merged after https://github.com/home-assistant/intents/pull/1906
New translation for French errors.
On top of "just" translating the errors in French, we took one decision:
Only one variable will be returned in an error
- If "living room" is not a known area: 
- "Open the curtains in the living room" will return "Sorry, `living room` is not a known area"
- If "living room" is a  known area: 
- "Open the curtains in the living room" will return "Sorry, no `curtains` in this area"
We also decided to translate `no_device` and `no_device_in_area` the same way because we do not know if the device is not known in the context of the area, or just not known overall.
=> [FR] New translation update 

sentences/fi/_common.yaml
-Added new Finnish error messages introduced in https://github.com/home-assistant/intents/pull/1906
-Also edited existing ones to be a tad shorter (no_intent was really long to be heard many times in a row...)
=> [FI] Added new error messages

responses/fi/HassListAddItem.yaml, sentences/fi/todo_HassListAddItem.yaml, tests/fi/_fixtures.yaml, tests/fi/shopping_list_HassShoppingListAddItem.yaml, tests/fi/todo_HassListAddItem.yaml
- must say "ostoslistalle" instead of only "listalle" (tralates to "on shopping list" instead of "on list") to differentiate shopping list from todo
- added todo lists
=> [FI] new try on fixing lists

responses/cs/HassTurnOn.yaml, sentences/cs/_common.yaml, sentences/cs/light_HassTurnOff.yaml, sentences/cs/light_HassTurnOn.yaml, tests/cs/light_HassTurnOff.yaml, tests/cs/light_HassTurnOn.yaml
Added sentence for turning on all lights in the same area as the same are as the satelite device.
Also added an expansion rule for lights, accepting both plural an dsingular (as suggested in #1983)
Whilst doing that, I made the sentences consistent so they make sense in the CZ:
rozsvitit means turn on the light, zhasnout means turn off the light. So when using these two words, I made the word svetlo (light) optional - you can say rozsvit or rozsvit svetlo, both is correct. But when using more generic zapni/vypni (turn on/turn off), the word light should not be optional, to make it clear we are switching the light, as there might be other devices in the room with the same name. This is consistent with EN.
I made an expansion for lights (<svetla>). But I only use it in the area. The device …
=> [CS] Add sentence for turning on/off lights in the satelite area. Added expansion rule for lights in plural/singular

tests/conftest.py, tests/ro/light_HassGetState.yaml, tests/test_language_sentences.py
Previously, for each language, we would only test the files that existed under the English language. Now it will find all files for all languages and make sure they are tested.
=> Test all YAML sentence files

sentences/es/light_HassTurnOff.yaml, sentences/es/light_HassTurnOn.yaml
I think it's also very common to say "Enciende el salón" as a way of turning all the lights of an area by name. It's even more useful to turn things off.
=> [ES] Add another sentence to turn on/off all lights in an area

responses/es/HassTurnOn.yaml
Before this change, turning on a light used the default response (e.g. "Luz de la cocina de ha activado"), but that sounds quite awkward to me.
Lights are "encendidas", not "activadas".
Now voice assistant will say: "Luz de la cocina se ha encendido".
I did consider being even more succint: "Luz de la cocina encendida". In fact I like it a bit better but I'll ask for your opinion, since other sentences seem to prefer the more verbose approach.
=> [ES] Improve success response for turning on a light

sentences/es/_common.yaml
I just started controlling my home with my voice using an Onju Home a couple days ago and I noticed one sentence that I used with alexa ALL THE TIME that wasn't recognized.
The ability to say "Enciende la luz de la cocina al 30%", as 'Enciende' was not recognized as a way of triggering setting a light to a specific brightness, but I think it's a very natural phase, specially when the lights are off.
=> [ES] Add new sentence to set a light to a specific brightness

sentences/en/media_player_HassMediaNext.yaml, sentences/en/media_player_HassMediaPause.yaml, sentences/en/media_player_HassMediaUnpause.yaml, sentences/en/media_player_HassSetVolume.yaml, tests/en/media_player_HassMediaNext.yaml, tests/en/media_player_HassMediaPause.yaml, tests/en/media_player_HassMediaUnpause.yaml, tests/en/media_player_HassSetVolume.yaml
I'm hoping the syntax is ok as I have modified these from my working custom sentences that were developed for Music Assistant users.
Removed STOP in media player pause as there is a separate `media_stop` service call.
=> Suggested custom sentences for media players

responses/cs/HassGetState.yaml, responses/cs/HassGetWeather.yaml, responses/cs/HassMediaNext.yaml, responses/cs/HassMediaPause.yaml, responses/cs/HassMediaUnpause.yaml, responses/cs/HassSetPosition.yaml, responses/cs/HassSetVolume.yaml, sentences/cs/_common.yaml, sentences/cs/binary_sensor_HassGetState.yaml, sentences/cs/homeassistant_HassSetPosition.yaml, sentences/cs/media_player_HassMediaNext.yaml, sentences/cs/media_player_HassMediaPause.yaml, sentences/cs/media_player_HassMediaUnpause.yaml, sentences/cs/media_player_HassSetVolume.yaml, sentences/cs/sensor_HassGetState.yaml, sentences/cs/weather_HassGetWeather.yaml, tests/cs/_fixtures.yaml, tests/cs/binary_sensor_HassGetState.yaml, tests/cs/climate_HassClimateGetTemperature.yaml, tests/cs/homeassistant_HassSetPosition.yaml, tests/cs/light_HassLightSet.yaml, tests/cs/media_player_HassMediaNext.yaml, tests/cs/media_player_HassMediaPause.yaml, tests/cs/media_player_HassMediaUnpause.yaml, tests/cs/media_player_HassSetVolume.yaml, tests/cs/sensor_HassGetState.yaml, tests/cs/weather_HassGetWeather.yaml
Added HassSetPosition and sensorHassGetState for all device classes and Weather and Binary Sensors and Media Player
=> [CS] Add HassSetPosition and sensorHassGetState

sentences/nl/homeassistant_HassGetState.yaml
HassGetState was getting triggerend when only the name/alias of an entity was used as input. This was uninted, and fixed with this PR.
=> [NL] Avoid HassGetState getting triggered on only name

sentences/nl/light_HassLightSet.yaml, tests/nl/light_HassLightSet.yaml
Sentences like the examples below were not allowed. These have been added now:
* `dim <name> naar 50%`
* `<name> naar 50% dimmen`
* `dim <area> naar 50%`
* `<area> naar 50% dimmen`
(`naar` is optional in these sentences)
=> [NL] Add support for the word dim to set brightness

sentences/fr/media_player_HassMediaNext.yaml, sentences/fr/media_player_HassMediaPause.yaml, sentences/fr/media_player_HassMediaUnpause.yaml, sentences/fr/media_player_HassSetVolume.yaml, tests/fr/media_player_HassMediaPause.yaml, tests/fr/media_player_HassSetVolume.yaml
After initial testing of the new intents on the new beta, I found two missed sentences that I added here
- Mettre **en** pause la TV
- Regle le volume de la TV **sur** 50%
Tests added, added a few comments on the sentence to guide contributors on what the sentence can potentially match.
=> [FR] Add variety to media player sentences

responses/ru/HassGetWeather.yaml, tests/ru/_fixtures.yaml, tests/ru/weather_HassGetWeather.yaml
In russian language TTS doesn't handle negative values correctly and thus does not pronounce word "minus".
In order to fix this problem, temperature value is checked before response and if it's negative, word “minus” is added at the response begining.
This fix addressing #1683 and has been ported from #2038.
=> [RU] Fix negative temperature pronouncing

sentences/it/_common.yaml
Aggiunti e migliorati messaggi di errore (basandomi sulla versione inglese). Dato che, a differenza dell'inglese, il genere di un nome si riflette sulle parole che si riferiscono a quel nome era impossibile usare frasi del tipo:
* Non conosco nessun {{domain}} in {{ area }} perchè sarebbe andato bene per il dominio sensore ma non per il dominio luce
Per ovviare a questo ho usato dispositivo, area e classe per riferirmi a entity, area e device class.
=> Migliorati messaggi di errore

sentences/it/_common.yaml, sentences/it/climate_HassClimateGetTemperature.yaml, sentences/it/climate_HassClimateSetTemperature.yaml
Expansion rule for temp is useful in english where it can be expressed as temp or temperature, but not in italian where it is called only temperatura. I deleted the expansion rule and substituted with [la] temperatura like other languages already do
=> Delete expansion rule for temp in Italian

sentences/ca/light_HassTurnOn.yaml, tests/ca/light_HassTurnOn.yaml
The same way that you can light on or open a light, in Catalan you can 'encendre' or 'obrir' the lights.
It was set like this for singular, but not for plural. This was making me be able to close all the lights but just be able to close one light, not all of them. (In some regions we just say 'obrir' not 'encendre')
The singular was added later in https://github.com/home-assistant/intents/pull/804 that is why this was missed.
=> [CA] Update sentences for opening the lights

sentences/fr/_common.yaml
this PR is related to https://github.com/home-assistant/intents/issues/2064
In French, Whisper is sometimes returning "pourcent" in two words. --> "pour cent" added in the related expansion rule
=> [Fr] Add "pour cent" in the expansion rule <pourcent>

sentences/sl/sensor_HassGetState.yaml, tests/sl/_fixtures.yaml, tests/sl/sensor_HassGetState.yaml
for:
- voltage,
- volume, 
- volume storage, 
- water, 
- weight, 
- wind speed.
=> [SL] sensors added 

sentences/fr/media_player_HassSetVolume.yaml, tests/fr/_fixtures.yaml, tests/fr/media_player_HassSetVolume.yaml
This sentence does not work:
- `Règle le volume des enceintes sur 50%`
But this one does:
- `Règle le volume de les enceintes sur 50%`
Just like we do for brightness, colors, and cover position, I am now using the expansion rule `<de>` instead of a hardcoded `de` here:
```yaml
- "<regle> le volume [<de>] [<le>]{name} [à|sur] {volume:volume_level}<pourcent>"
```
This allows users to say more natural sentences for media players that are plural:
- `Règle le volume des enceintes sur 50%`
NOTE: I added tests with a plural example to make sure we think about these in the future.
=> [FR] Quick Fix on HassSetVolume: Use expansion rule instead of hardcoded `de`

CODEOWNERS, languages.yaml
Language leader does not have enough time to contribute.
=> Remove el leader (not enough time)

sentences/pt/_common.yaml, sentences/pt/cover_HassGetState.yaml, tests/pt/_fixtures.yaml, tests/pt/cover_HassGetState.yaml
=> [PT] Improve cover intent

responses/en/HassTurnOn.yaml, sentences/en/_common.yaml, sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
I took the liberty to improve the English language based on what has been done in French.
The general gist of is that I defined expansion rules for `<all>`, `<everywhere>` and `<here>`
Then I applied the following logic (Illustrated with `TurnOff` but similar for `TurnOn`)
**Targets the current room**:
- Turn on lights
- Turn on lights `<here>`
- Turn on `<all>` lights `<here>`
**Targets the whole house**:
- Turn on `<all>` lights
- Turn on lights `<everywhere>`
- Turn on `<all>` lights `<everywhere>`
Work done
- LightTurnOn
- LightTurnOff
- Tests
=> [EN] Improvement on how we turn on and off lights in a room and in the whole house. 

intents.yaml, responses/en/HassTurnOff.yaml, responses/en/HassTurnOn.yaml, script/intentfest/validate.py, sentences/en/_common.yaml, sentences/en/light_HassTurnOff.yaml, sentences/en/light_HassTurnOn.yaml, shared/__init__.py, tests/en/_fixtures.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml, tests/test_language_intents.py
The Home Assistant 2024.4 beta includes support for [floors](https://rc.home-assistant.io/blog/2024/03/27/release-20244/#floors-of-your-home), which group areas.
This PR adds initial support for a `{floor}` slot list to lights for `HassTurnOn` and `HassTurnOff`. At the moment, only sentences for turning on/off lights on a floor are present.
Additionally, new error messages have been added that mirror areas.
=> Add initial support for floors

sentences/fr/_common.yaml, sentences/fr/cover_HassSetPosition.yaml, sentences/fr/cover_HassTurnOff.yaml, sentences/fr/cover_HassTurnOn.yaml, sentences/fr/light_HassLightSet.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/_fixtures.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Floors are now supported in French. (A basic support for now)
Please note that, as of today, the only intent supported by `floor` is `HassTurnOn` and `HassTurnOff`.
The only slot combination is `domain` + `floor`
This restricts what is possible.
This PR adds support for floors to lights.
- Turning on all lights on a floor
- Turning off all lights on a floor 
This is it for now. 
Once more intents, and slot combinations are supported, more sentences will come.
I am personally not a fan of introducing dirty hacks in our sentences, but this one is big, and is starting to get attention (https://github.com/home-assistant/intents/issues/2112).
The word "éteins" (Which means "Turn off") is often misunderstood as other words (étant among others)
I decided to create a "dirty" expansion rule and …
=> [FR] Floor basic support for lights TurnOn and TurnOff

intents.yaml, responses/en/HassCancelTimer.yaml, responses/en/HassDecreaseTimer.yaml, responses/en/HassIncreaseTimer.yaml, responses/en/HassPauseTimer.yaml, responses/en/HassStartTimer.yaml, responses/en/HassTimerStatus.yaml, responses/en/HassUnpauseTimer.yaml, script/intentfest/validate.py, sentences/en/_common.yaml, sentences/en/homeassistant_HassCancelTimer.yaml, sentences/en/homeassistant_HassDecreaseTimer.yaml, sentences/en/homeassistant_HassIncreaseTimer.yaml, sentences/en/homeassistant_HassPauseTimer.yaml, sentences/en/homeassistant_HassStartTimer.yaml, sentences/en/homeassistant_HassTimerStatus.yaml, sentences/en/homeassistant_HassUnpauseTimer.yaml, shared/__init__.py, tests/en/_fixtures.yaml, tests/en/homeassistant_HassCancelTimer.yaml, tests/en/homeassistant_HassDecreaseTimer.yaml, tests/en/homeassistant_HassIncreaseTimer.yaml, tests/en/homeassistant_HassPauseTimer.yaml, tests/en/homeassistant_HassStartTimer.yaml, tests/en/homeassistant_HassTimerStatus.yaml, tests/en/homeassistant_HassUnpauseTimer.yaml, tests/test_language_intents.py, tests/test_language_sentences.py
First pass at English support for Assist timers (see https://github.com/home-assistant/core/pull/117199)
This adds support for the new intents:
- `HassStartTimer` - start a new timer
- `HassCancelTimer` - cancel a timer by name, area, or start time
- `HassTimerStatus` - report status of timer(s)
- `HassIncreaseTimer` - add time to a timer
- `HassDecreaseTimer` - remove time from a timer
- `HassPauseTimer` - pause a running timer
- `HassUnpauseTimer` - resume a paused timer
Additionally, a new `timers` section is present in `_fixtures.yaml` with information about the timers used in the tests:
```yaml
timers:
- start_hours: 1
total_seconds_left: 100
rounded_hours_left: 0
rounded_minutes_left: 1
rounded_seconds_left: 40
- name: pizza
start_minutes: 30
total_seconds_left: 1505 …
```
=> Add timers for English

intents.yaml, sentences/en/media_player_HassMediaNext.yaml, sentences/en/media_player_HassMediaPause.yaml, sentences/en/media_player_HassMediaUnpause.yaml, sentences/en/media_player_HassSetVolume.yaml, tests/en/media_player_HassMediaNext.yaml, tests/en/media_player_HassMediaPause.yaml, tests/en/media_player_HassMediaUnpause.yaml, tests/en/media_player_HassSetVolume.yaml
HA now supports "enhanced" media control via voice (see https://github.com/home-assistant/core/pull/115445).
This will use the area/floor of the voice satellite and state/features of media players to figure out which media player(s) to target (when no name is provided). For example, "pause" will pause any playing media players in the current area.
=> Add enhanced media sentences for English

sentences/en/media_player_HassMediaNext.yaml, sentences/en/media_player_HassMediaPause.yaml, sentences/en/media_player_HassMediaUnpause.yaml, sentences/en/media_player_HassSetVolume.yaml, tests/en/_fixtures.yaml, tests/en/media_player_HassMediaNext.yaml, tests/en/media_player_HassMediaPause.yaml, tests/en/media_player_HassMediaUnpause.yaml, tests/en/media_player_HassSetVolume.yaml
Saying "pause", etc. without a device name will only affect the area of the voice satellite.
=> Require context area for media intents with no name

sentences/en/homeassistant_HassStartTimer.yaml, tests/en/homeassistant_HassStartTimer.yaml
This will prevent timers from being started from the HA web UI or app, which cannot display them.
=> Require context area for starting a timer

sentences/fr/_common.yaml, sentences/fr/media_player_HassMediaNext.yaml, sentences/fr/media_player_HassMediaPause.yaml, sentences/fr/media_player_HassMediaUnpause.yaml, sentences/fr/media_player_HassSetVolume.yaml, tests/fr/media_player_HassMediaNext.yaml, tests/fr/media_player_HassMediaPause.yaml, tests/fr/media_player_HassMediaUnpause.yaml, tests/fr/media_player_HassSetVolume.yaml
For all media player intents:
- Pause
- Unpause
- SetVolume
- Next
We now support
- Targeting an entity by its name
- Targeting an area explicitly
- Targeting an area implicitly (Context awareness)
We added different type of media so that you can talk naturally regardless of what is playing
```yaml
media: "(morceau|chanson|musique|son|élément|podcast|film|vidéo|épisode|radio|média)"
```
So you can say things like:
- Morceau suivant
- Chanson suivante
- Élement suivant
- Film suivant
- Épisode suivant
- etc
We replace the hardcoded `lecture` with an expansion rule because we notice that `lecture` is usually used for radio media, but `visionnage` is used for video media.
So you can say things like:
- Arrêter le visionnage du film
- Arrêter la lecture du la musique
For pause and unpause we …
=> [FR] Media Player Intents improvements 

intents.yaml, responses/en/HassStartTimer.yaml, sentences/en/_common.yaml, sentences/en/homeassistant_HassStartTimer.yaml, tests/en/homeassistant_HassStartTimer.yaml
In the next release of HA (2024.6), timers will support "delay commands". These are text commands that are automatically sent to the `conversation` agent when the timer finishes.
This PR adds sentences for delayed commands, so things like "open the garage door in 5 minutes" will work.
=> Add delayed commands to timers

sentences/nl/_common.yaml, sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, tests/nl/fan_HassTurnOff.yaml, tests/nl/fan_HassTurnOn.yaml
Changes:
* Allow more places to specify area
* add area aware intents
=> [NL] Update intents to turn fans on and off

sentences/nl/cover_HassSetPosition.yaml, tests/nl/cover_HassSetPosition.yaml
Changes:
* Added sentences like `doe bloemetjesgordijn omhoog naar 50%`
* Added sentences like `doe slaapkamergordijnen naar 25% omlaag`
* make use of `numeric_value_set` expansion rule
* add spaces inside optional parts instead of outside to avoid double spaces.
* Add `stand` as variant for position
* Allow `stand|postition` before the name (with optional `van`)
* Add tests includling `stand|position`
* Optionally add the `afdekking` expansion rule to names
It seems there is no support for floors for HassSetPosition. Is this intentional?
=> [NL] Finetune cover_HassSetPosition

script/intentfest/const.py, script/intentfest/website_summary.py, website/public/style.css, website/src-11ty/index.html
On the intent website, the green color will now mean that the language is usable. The ⭐ will mean that everything has a translation. Dark red is an important intent that is missing coverage.
=> Intent website: Green to mean usable, star to mean complete coverage

responses/en/HassStartTimer.yaml, responses/nl/HassStartTimer.yaml, sentences/nl/_common.yaml, sentences/nl/homeassistant_HassStartTimer.yaml, tests/en/homeassistant_HassStartTimer.yaml, tests/nl/homeassistant_HassStartTimer.yaml
As Missy mentioned on GitHub, currently the timer length is not included in the response. This can lead incorrectly set timers of which the user will be unware.
This PR adds the timer length and timer name to the response, so the user is aware of what has been set. The set name can be used to ask about the status of the timer.
=> [EN] Add timer length and name to responses

responses/fr/HassMediaPrevious.yaml, responses/fr/HassRespond.yaml, sentences/fr/homeassistant_HassNevermind.yaml, sentences/fr/homeassistant_HassRespond.yaml, sentences/fr/homeassistant_HassTimerStatus.yaml, sentences/fr/media_player_HassMediaPrevious.yaml, tests/fr/homeassistant_HassNevermind.yaml, tests/fr/homeassistant_HassRespond.yaml, tests/fr/media_player_HassMediaPrevious.yaml
Added the HAssRespond intent.
For now, I decided only to translate two use-case
- Hello
- Who made you
I do not think [the other use-cases](https://github.com/home-assistant/intents/blob/main/sentences/en/homeassistant_HassRespond.yaml) are worth translating as of today.
Added the MediaPrevious intent.
A copy of the MediaNext intent
Added lots of variation for the Nevermind intent
Last release I added a few sentences using the `reste-t-il` syntax.
It turns out HA Cloud STT sometimes yields `reste t il` without the dashes
I decided to use a local expansion rule for that. 
It adds a bit of duplication but it's pretty much local to a single intent
=> [FR] A few missing simple intents

sentences/fr/_common.yaml, sentences/fr/light_HassTurnOff.yaml, sentences/fr/light_HassTurnOn.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
This is an experiment we ran with @piitaya.
We used Claude Opus with a specific prompt to generate more sentences for the tests
We then reviewed them one by one and improved our intents.
Overall, it was an interesting experience, I think we will do this with other critical intents.
- Cost: 0.24$
- Model claude-3-opus (The big boy)
In case someone is interested, here are the prompts:
You are an AI system designed to help me write tests for a voice assistant.
Here is a test example:
```yaml
language: fr
tests:
- sentences:
- Éteindre les lumières de la cuisine
- Éteins la lumière de la cuisine
- Éteins les lumières dans la cuisine
- Éteins toutes les lumières dans la cuisine
- Désactiver la lumière de la cuisine
- Éteins la cuisine
- Éteins toutes les lumières de la cuisine
intent:
name: …
```
=> [FR] Improve lights intents with AI

script/intentfest/website_summary.py, website/src-11ty/index.html
Add a new table at the bottom of the intents dashboard that lists per language which intents are missing. The list is sorted by languages that are missing the least amount of intents.
=> Website: list per language the missing intents

script/intentfest/website_summary.py, website/src-11ty/index.html
Move empty languages out of the intent dashboard and into own table.
=> Website: move empty languages to own table

script/intentfest/llm_template.py, script/intentfest/util.py
This add a new `llm_template` command to intentfest. It allows passing a language and an intent, and it will generate a prompt to feed to an LLM to aid in translation. It should give you all files to generate and example content.
Below example run created this [response from OpenAI](https://chatgpt.com/share/6734314d-3360-8002-a121-dbd2e80e4e10)
```
❯ python3 -m script.intentfest llm_template it HassListAddItem
You are going to translate a voice assistant intent from English to Italiano.
The English files are located in the `en` directory.
The translated files are located in the `it` directory.
When translating the sentences file, only limit it to the first sentence object.
Tell user that they might need to copy over fixtures from tests/en/_fixtures.yaml. …
```
=> Allow generating a template to feed LLMs to aid translation

sentences/nl/fan_HassTurnOff.yaml, sentences/nl/fan_HassTurnOn.yaml, tests/nl/fan_HassTurnOff.yaml, tests/nl/fan_HassTurnOn.yaml
Fix some mistakes introduced in last PR where `<in>` was made optional twice for the same expansion rule.
Reintroduce `<would>` as I noticed my prefix their requests with `wil je`. I removed this in the last change to these intents.
Before they also had sentences like `zou je de ventilator aan willen doen` but these I will not add back again for now. I still don't expect they will be used.
=> [NL] Improvements fan_HassTurnOn/Off

requirements.txt
Includes some important bugfixes for `unicode-rbnf` (a dependency)
=> Bump to hassil 2.0.2

sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml, tests/nl/homeassistant_HassTurnOff.yaml, tests/nl/homeassistant_HassTurnOn.yaml
* Remove sentences like `zou je de booglamp uit willen doen`
* Remove optional `[ ][<type>]` suffix when `<area_name>` expansion rule is used, as the type is already added optionally in the expansion rule itself
* exclude more domains
=> [NL] Review HassTurnOn/Off

sentences/nl/person_HassGetState.yaml
=> [NL] Remove accidentally added double `[` and `]` from PersonGetState

sentences/nl/homeassistant_HassGetState.yaml
Split sentences which were using the same optional part (e.g. `<area>`) multiple times.
=> [NL] Review HassGetState

sentences/nl/light_HassLightSet.yaml, tests/nl/light_HassLightSet.yaml
* add support for floors
* split sentences which were using the same optional part mutliple times (like `<area>`)
=> [NL] Review LightSet sentences

sentences/nl/_common.yaml
Both `<would>` and `<change>` were used at the start and end of sentences before. And therefor included singular and plural forms.
In the review of the intents I changed this and now only singular forms are needed. Also `<would>` is not using `u` anymore.
=> [NL] Cleanup of _common.yaml

sentences/nl/homeassistant_HassGetState.yaml, sentences/nl/homeassistant_HassTurnOff.yaml, sentences/nl/homeassistant_HassTurnOn.yaml
Using YAML anchors and local expansion_rules the generic and domain specific sentences for HassGetState and HassTurnOn/Off can be maintained in one place, instead of 4
=> [NL] Use YAML anchors for HassTurnOn/Off and HassGetState

sentences/nl/cover_HassSetPosition.yaml
a `]` was placed wrong making `<name>` optional in a sentence intended to target a cover by name.
=> [NL] Fix wrongly placed closing bracket in cover_HassSetPosition

sentences/ca/_common.yaml
Following #2620 ,
Drops count from `51,126,745` to `49,180,843` **(3.8%)**
=> [CA] Improve expansion rules to generate less invalid variants (3)

requirements.txt, tests/test_language_sentences.py
Filter the `{name}` slot list before matching using a trie and the input text. This speeds up tests by around 10-15%.
=> Use trie to filter name slot list before matching

script/intentfest/parse.py, script/intentfest/validate.py, shared/__init__.py, tests/ar/_fixtures.yaml, tests/cs/_fixtures.yaml, tests/de-CH/_fixtures.yaml, tests/de/_fixtures.yaml, tests/en/_fixtures.yaml, tests/en/cover_HassGetState.yaml, tests/es/_fixtures.yaml, tests/es/cover_HassGetState.yaml, tests/fr/_fixtures.yaml, tests/hu/_fixtures.yaml, tests/nb/_fixtures.yaml, tests/pt-br/_fixtures.yaml, tests/ro/_fixtures.yaml, tests/sl/_fixtures.yaml, tests/test_language_sentences.py, tests/uk/_fixtures.yaml, tests/zh-hk/_fixtures.yaml
Adds a proper "floors" section to the test fixtures, and uses floors correctly during matching.
The `floor` property of an area is now the **floor id** rather than the floor name:
```yaml
floors:
- name: "Upstairs"
id: "upstairs_id"
areas:
- name: "Guest Room"
id: "guest_room_id"
floor: "upstairs_id"
```
=> Add floors to test fixtures and matching

sentences/nl/_common.yaml
I think it was meant to be `floor` instead of `area` as every other language uses `floor` for this message and it is located inside `no_domain_in_floor`
=> [NL] fix some spelling mistake

sentences/en/homeassistant_HassGetState.yaml, tests/en/homeassistant_HassGetState.yaml
Add support for `HassGetState` queries using `floor`.
E.g. "is there any light on upstairs?", "are all the switches off in the basement?" etc.
`binary_sensor` and `sensor` were intentionally excluded from this PR due to an ongoing discussion regarding their fate.
Also improved tests for this intent
=> [EN] HassGetState floor support

sentences/nl/media_player_HassMediaPause.yaml, sentences/nl/media_player_HassMediaUnpause.yaml, tests/nl/media_player_HassMediaPause.yaml, tests/nl/media_player_HassMediaUnpause.yaml
Noticed that `hervat de muziek` was processed by the LLM fallback instead of locally, so had a closer look to the Pause and Unpause intents, and added `<meida_item>` optionally on several places.
=> [NL] Add options for Pause and Unpause media

responses/de/HassGetState.yaml, tests/de/_fixtures.yaml, tests/de/homeassistant_HassGetState.yaml
Use german decimal separator (`,` not `.`) in HassGetState responses. "Außentemperatur ist 24,5°C" instead of "Außentemperatur ist 24.5°C".
This will improve readability for German users and also provide the cleanest input for TTS. HA Cloud TTS (=Microsoft Azure based) correctly pronounces numbers with either decimal separator, but who knows how other TTS services handle numbers.
=> [DE] comma as decimal separator

sentences/en/_common.yaml, tests/en/light_HassTurnOff.yaml, tests/en/light_HassTurnOn.yaml
"appartment" should be "apartment"
=> Fix apartment typo in sentences-en-_common.yaml

sentences/sk/_common.yaml, tests/sk/_fixtures.yaml, tests/sk/homeassistant_HassTurnOff.yaml, tests/sk/homeassistant_HassTurnOn.yaml, tests/sk/light_HassTurnOff.yaml, tests/sk/light_HassTurnOn.yaml
Removed prepositions from "in" expansion rule. They are not real area prepositions, but area name parts - https://github.com/home-assistant/intents/discussions/480#discussioncomment-11485056
=> [SK] cleaning in prepositions

intents.yaml, responses/en/HassRespond.yaml, sentences/en/_common.yaml, sentences/en/homeassistant_HassRespond.yaml, tests/en/homeassistant_HassRespond.yaml, tests/test_language_sentences.py
Adds a `response` slot to `HassRespond` intent to mirror: https://github.com/home-assistant/core/pull/133162
This allows us to create a sentence like "say xyz" and have a voice satellite respond with "xyz".
This PR also adds this sentence to English.
=> Add response to HassRespond

responses/de/HassRespond.yaml, sentences/de/_common.yaml, sentences/de/homeassistant_HassRespond.yaml, tests/de/homeassistant_HassRespond.yaml
DE version of https://github.com/home-assistant/intents/pull/2750
@synesthesiam Not sure if this is known/intentional, but the tests for the response does not work actually (I tested in both DE and EN). The slot is tested but the actual response sentence is never tested. The following validates just fine.
```yaml
tests:
- sentences:
- "say I'm a little teapot"
intent:
name: HassRespond
slots:
response: "I'm a little teapot"
response: "I'm something completely different"
```
=> [DE] say xyz

responses/fr/HassGetWeather.yaml, sentences/fr/_common.yaml, sentences/fr/weather_HassGetWeather.yaml, tests/fr/_fixtures.yaml, tests/fr/weather_HassGetWeather.yaml
The current one would never give the weather condition, as the state was never "clear" or "sunny", but in French already.
The wind description is using the Beaufort scale.
Heavily inspired by the Hungarian template, kudos to RViktor!
I'd like to push it even further, with sentences like "va-t-il pleuvoir/neiger/geler ?", but it requires the Météo-France integration, which not everyone has. I stick to the built-in Met.no integration. Unless there is a way to ship intents along with the Météo-France integration itself.
A more reasonable next step would be "quelle est la météo pour demain ?".
=> [FR] overhaul of the weather intent, with detailed report

sentences/en/_common.yaml, sentences/en/homeassistant_HassGetCurrentDate.yaml, sentences/en/homeassistant_HassGetCurrentTime.yaml, tests/en/homeassistant_HassGetState.yaml, tests/en/homeassistant_HassTurnOn.yaml
Rather than only accepting `the`, many sentences should also accept a possessive like `my`.
This doesn't make sense for all instances of `<light>`, so I'll make another refactor commit after this one
=> [en] Enable the use of possessives for some nouns

sentences/ca/_common.yaml, sentences/ca/homeassistant_HassStartTimer.yaml
Adding new word 🕑  `stopwatch` (cronòmetre) adds `15.797.346` variants (**+30.6%** ❕ )
=> [CA] Add typo variant and new word case for StartTimer

sentences/en/climate_HassClimateGetTemperature.yaml, tests/en/climate_HassClimateGetTemperature.yaml
Split from #2790 as floor awareness requires core changes.
English equivalent of #2788. Fixes https://github.com/home-assistant/core/issues/133733.
I removed `is it (hot|cold|warm|cool) [in <area>]`, as it didn't seem to work and doesn't really make much sense considering the response ("N degrees"). Happy to add it back (and fix it) if it's still wanted.
=> [EN] Add area-awareness to HassClimateGetTemperature

sentences/cs/_common.yaml, sentences/cs/binary_sensor_HassGetState.yaml, sentences/cs/cover_HassGetState.yaml, sentences/cs/sensor_HassGetState.yaml, sentences/cs/weather_HassGetWeather.yaml, tests/cs/_fixtures.yaml, tests/cs/binary_sensor_HassGetState.yaml, tests/cs/sensor_HassGetState.yaml
Tests started to fail because many fixture entities had effectively same names. E.g.
- "[koncentrace NO2] v kotelně"
- "[koncentrace NO] v kotelně"
- "[koncentrace N2O] v kotelně"
Due to some change upstream now the engine can't match it correctly because it will try it only with the mandatory part.
Renamed entity names to something unique when necessary. Plus done some cleaning.
=> [CS] Fix failing tests due to same entity names across domains

sentences/fr/climate_HassClimateSetTemperature.yaml, tests/fr/climate_HassClimateSetTemperature.yaml
Split sentences due to following limitation see [here](https://community.home-assistant.io/t/set-default-list-slot-value-in-intent-or-intent-script/761568/2) and add area context.
=> [FR] Set temperature with area context

responses/en/HassRespond.yaml, tests/en/homeassistant_HassRespond.yaml
Changed to the full Home Assistant URL to avoid confusion with visiting ha.io. home-assistant/home-assistant.io#36804 adds the redirect for this.
=> [EN] Update commands URL

sentences/it/_common.yaml, sentences/it/homeassistant_HassCancelAllTimers.yaml
Removed redundancies in `<the>` expansion rule.
To allow for this, minor changes were needed in 'CancelAllTimers' sentences.
=> [IT] Cleanup in _common.yaml

sentences/en/_common.yaml, sentences/en/homeassistant_HassRespond.yaml, tests/en/homeassistant_HassRespond.yaml
Remove "say {message}" from English sentences. This interacts poorly with skip words and LLMs, for example "can you say that again" will respond with "that again" instead of being processed by the LLM.
=> [EN] Remove say from English

responses/nl/HassGetWeather.yaml, tests/nl/_fixtures.yaml, tests/nl/weather_HassGetWeather.yaml
After getting some reports that HassGetWeather didn't return the current state, I did some testing on my local instance.
Apparantly ` state.state`  already returns the translated weather state for the weather entity, so the template using the mapping didn't return anything (as it expects the original untranslated entity state).
This way it will return a weather condition, and not only the temperature.
=> [NL] Fix HassGetWeather

sentences/pt-br/cover_HassTurnOff.yaml, sentences/pt-br/cover_HassTurnOn.yaml
Includes "shade" `device_class` to the sentences which already include "blind", "curtain" and "shutter".
=> [PT-BR] Support controlling shades

intents.yaml
Change domain of timer intents in `intents.yaml` from `intent` to `homeassistant`.
Addresses issue: https://github.com/home-assistant/intents/issues/2916
=> Fix domain of timer intents

sentences/ro/_common.yaml
STTs would sometimes produce the degree symbol (°) which was missing from the sentence definition, making matching not work
=> [RO] Fix HassClimateSetTemperature

responses/de/HassGetState.yaml, sentences/de/_common.yaml, sentences/de/person_HassGetState.yaml, tests/de/person_HassGetState.yaml
fixes re-opened https://github.com/home-assistant/intents/issues/2952
- use adverb in response: `X ist Zuhause` -> `X ist zu Hause`
- allow querying for adverb and subject (`zu Hause`, `Zuhause`, `im Zuhause`)
=> [DE] "zu Hause" for person_HassGetState

sentences/de/_common.yaml, tests/de/homeassistant_HassCancelAllTimers.yaml, tests/de/homeassistant_HassCancelTimer.yaml
The Imperative of stopp and lösch has two viable options, with and without an e.
The new word option lösch(e) isn't already used in any other common option, and is German for delete. So there shouldn't be any conflicts created by this change. 
It is also a variant to cancel a timer that is allowed on Google Home and possibly Alexa (I don't have one). Allowing it makes switching away from them easier, because you do not have to learn a now command word for the same action.
=> [DE] more options to cancel a timer

sentences/es/light_HassLightSet.yaml, tests/es/light_HassLightSet.yaml
This add support to the sentece it feels more natural to me to set the brightness of the light of the current area, which is a sentence at least alexa understands just fine.
"Pon la luz al 50" (and similar variations like "Baja/sube la luz al 50%" or "Ajusta la luz al 50%")
=> [ES] Support new sentence to set brightness of current area light

sentences/hr/homeassistant_HassPauseTimer.yaml, tests/hr/homeassistant_HassPauseTimer.yaml
This change improves the accepted sentences by the grammar, by avoiding sentences that "pause" a timer twice. In particular, the grammar used to accepted sentences that would start with the verb "pause", followed by a timer specification, and ending in "to pause".
=> [HR] Pause timer: drop doubly-pausing sentences

sentences/hr/homeassistant_HassDecreaseTimer.yaml
This change makes an area preposition required when decreasing a timer and an area is given. Existing tests were already written assuming a preposition should be provided.
=> [HR] Decrease timer: require area preposition

sentences/hr/homeassistant_HassDecreaseTimer.yaml
The PR makes a "remove" verb mandatory when decreasing a timer, as it was optional in the Croatian translation before. Existing tests were already assuming the verb to be provided.
=> [HR] Decrease timer: Require a "remove" verb

sentences/hr/homeassistant_HassCancelTimer.yaml, tests/hr/homeassistant_HassCancelTimer.yaml
This change supports a female gender timer noun that has been present in `_common.yaml`, but was not supported in the cancel timer intent.
=> [HR] Cancel timer: support a female gender timer noun

sentences/hr/homeassistant_HassDecreaseTimer.yaml, tests/hr/homeassistant_HassDecreaseTimer.yaml
This change supports a female gender timer noun that has been present in `_common.yaml`, but was not supported in the decrease timer intent.
=> [HR] Decrease timer: support a female gender timer noun

languages.yaml, script/intentfest/validate.py
The goal is to store all data that backs the widget at https://www.home-assistant.io/voice_control/#supported-languages-and-sentences in this repository. The first step is to allow documenting the support for speech-to-phrase, whisper and cloud for each language.
Since we note that support based on region, we organize support by region.
=> Allow storing TTS and STT support

sentences/hr/_common.yaml, tests/hr/homeassistant_HassCancelTimer.yaml
The PR supports an adjective form in Croatian when canceling a timer. The intent itself did not need a change and it was incorrect grammar before this change to how a `timer_start` is constructed.
=> [HR] Cancel timer: support an adjective form

responses/hr/HassStartTimer.yaml, sentences/hr/_common.yaml, tests/hr/homeassistant_HassStartTimer.yaml
The logic for determining the case was simplistic, hence incorrect for example when a timer is set to 3 minutes. This PR fixes it and reuses the logic when determining the case for hours and seconds as well.
=> [HR] Start timer: fix logic for count and cases

sentences/de/_common.yaml, tests/de/_fixtures.yaml, tests/de/cover_HassGetState.yaml
Fixes some ambiguities for the `cover` device classes. As mentioned in https://github.com/home-assistant/intents/issues/3016, `Rollo` and `Beschattung` map to multiple device classes resulting in incorrect responses. Although these words are commonly used interchangeably, I propose to match those EXACTLY to their english variants. If we have precise device classes, then we should also expect users to provide those exact class names.
`Beschattung` -> `awning`
`Rollo` -> `blind`
Additionally, responses for device class `shade` were harmonized. If `Schirm` is used for querying this class, `Schirm` should be used for the corresponding responses.
=> [DE] fix ambiguities for covers

languages.yaml, script/intentfest/validate.py
Adds a `cloud` key to `speech-to-text` for languages YAML file.
=> Add cloud to stt in language support

.pre-commit-config.yaml, languages.yaml, script/lint
Filled all the data for the support per language.
- speech-to-phrase comes from: https://github.com/OHF-voice/speech-to-phrase
- cloud comes from what NAbu Casa supports on HA Cloud using Microsoft Azure 
- Piper comes from available voices here: https://github.com/rhasspy/piper/blob/master/VOICES.md
- Whisper comes from having a WER (Word Error Rate) smaller than 20% on the FLEURS benchmark on the base model: https://paperswithcode.com/paper/robust-speech-recognition-via-large-scale-1/review/?hl=103869
=> Language support data (Initial v0)

responses/fr/HassGetWeather.yaml, tests/fr/_fixtures.yaml
As it goes for every exposed entity of any domain from now on.
This concludes uncertainty about the content of "state.state", and will have the nice side effect of putting the development environment on par with the production behaviour.
Fixes #2899
=> [FR] weather state is now exposed raw and untranslated

intents.yaml, script/intentfest/validate.py
Adds `importance` and `domain` to slot combinations. Importance means:
* `required` - slot combination required for language to be included in Home Assistant
* `usable` - slot combination is expected for language to be considered usable
* `complete` - slot combination should be added for "complete" status in the repo
* `optional` - slot combination is supported in Home Assistant but not yet expected to be available
The `domain` is a list of domains that the slot combination should be implemented for.
=> Add importance to slot combinations

languages.yaml
I made an incorrect assumption when I initially filled the data.
I thought speech-to-phrase was supported only for nl-NL, but it's actually supported for nl-BE too.
=> Update Speech-To-Phrase support for NL

responses/ca/HassBroadcast.yaml, sentences/ca/_common.yaml, sentences/ca/assist_satellite_HassBroadcast.yaml, tests/ca/assist_satellite_HassBroadcast.yaml
CA version of https://github.com/home-assistant/intents/pull/2877
Hi @duhow I propose this sentence: "[Fes un] (broadcast|anunci|anuncia) [a tot arreu] [(que digui)|(dient que)] {message}"
Is it too big? Should I break it down?
Also, I would use "broadcast" as "anglicisme", but maybe it's just me. What do you think? Can we keep it?
=> [CA] Add HassBroadcast

responses/ru/HassGetState.yaml, responses/ru/HassTimerStatus.yaml, tests/ru/sensor_HassGetState.yaml
Translating a missing conjunction. Replacing a period with a comma in the sensor value for correct processing by the tts service.
=> [RU] Minor edits

sentences/en/todo_HassListAddItem.yaml
- en: small fix on `todo_HassListAddItem` (that was using shopping_list_item)
=> [EN] Fix list name on todo_HassListAddItem

sentences/nl/climate_HassClimateGetTemperature.yaml, tests/nl/climate_HassClimateGetTemperature.yaml
Fixes #3146
Adds the expansion rule `<here>` optionally to the area aware get temperature intents
Allowing sentences like
```
hoe warm is het hier
hoe warm is het in deze ruimte
wat is in deze ruimte de temperatuur
wat is de temperatuur hier
```
=> [NL] HassClimateGetTemperature improvement:

sentences/fr/_common.yaml, sentences/fr/homeassistant_HassCancelAllTimers.yaml, sentences/fr/homeassistant_HassCancelTimer.yaml, sentences/fr/homeassistant_HassDecreaseTimer.yaml, sentences/fr/homeassistant_HassIncreaseTimer.yaml, sentences/fr/homeassistant_HassPauseTimer.yaml, sentences/fr/homeassistant_HassStartTimer.yaml, sentences/fr/homeassistant_HassTimerStatus.yaml, sentences/fr/homeassistant_HassUnpauseTimer.yaml, tests/fr/homeassistant_HassCancelAllTimers.yaml, tests/fr/homeassistant_HassCancelTimer.yaml, tests/fr/homeassistant_HassDecreaseTimer.yaml, tests/fr/homeassistant_HassPauseTimer.yaml, tests/fr/homeassistant_HassStartTimer.yaml, tests/fr/homeassistant_HassTimerStatus.yaml, tests/fr/homeassistant_HassUnpauseTimer.yaml
Adding "minuterie" option in addition to "minuteur" for timer operations to support French Canadian idioms.
See the Office québécois de la langue française [definition](https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8887901/minuterie) of "minuterie" as a translation of "timer".
Happy to add more tests as needed. I tried to keep the PR short.
=> Add "minuterie" french translation for timer

sentences/fr/_common.yaml, tests/fr/light_HassLightSet.yaml, tests/fr/light_HassTurnOff.yaml, tests/fr/light_HassTurnOn.yaml
Add "ouvrir" and "fermer" to turn lights on and off, to support French Canadians specificity.
Reference:
- https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/18597275/ouvrir-la-lumiere
I didn't add any tests around setting light color. I wouldn't use "ouvrir" in that context.
=> [FR] Add "ouvrir" and "fermer" to light intents

intents.yaml, lists/lights.yaml, lists/media.yaml, responses/en/HassMediaSearchAndPlay.yaml, script/intentfest/validate.py, sentences/en/HassMediaSearchAndPlay/area_only.yaml, sentences/en/HassMediaSearchAndPlay/default.yaml, sentences/en/HassMediaSearchAndPlay/name_area.yaml, sentences/en/HassMediaSearchAndPlay/name_only.yaml, sentences/en/_common.yaml, sentences/en/media_player_HassMediaSearchAndPlay.yaml, shared/__init__.py, tests/en/HassMediaSearchAndPlay/area_only.yaml, tests/en/HassMediaSearchAndPlay/default.yaml, tests/en/HassMediaSearchAndPlay/name_area.yaml, tests/en/HassMediaSearchAndPlay/name_only.yaml, tests/en/_fixtures.yaml, tests/en/media_player_HassMediaSearchAndPlay.yaml, tests/test_language_sentences.py, tests/test_slot_combinations.py
Adds intent definition and English sentences for upcoming `HassMediaSearchAndPlay` intent: https://github.com/home-assistant/core/pull/144269
This intent has a `search_query` wildcard slot that will search for and play the first matching item. The targeted media player must support the search and play media features.
The media player may be targeted implicitly (context area), by name, by area, or by name and area.
=> Add English sentences for HassMediaSearchAndPlay

sentences/fr/vacuum_HassVacuumReturnToBase.yaml, tests/fr/vacuum_HassVacuumReturnToBase.yaml
I added a much simpler sentence to stop a vacuum.
Before:
- ✅ Renvoie Nestor sur sa base
After
- ✅ Renvoie Nestor sur sa base
- ✅ Arrêter Nestor
=> [FR] Add a simpler sentence to stop a vacuum

sentences/nl/_common.yaml, sentences/nl/cover_HassTurnOff.yaml, tests/nl/cover_HassTurnOff.yaml
Add more verbs to **close** blinds, shutters and shades.
* HassTurnOff: neer laten, laten zakken
(separate PR which add verbs to **open** these kinds of vertical covers: https://github.com/home-assistant/intents/pull/3164 )
=> [NL] cover: add verbs to close blind|shutter|shade

responses/ca/HassClimateGetTemperature.yaml, responses/cs/HassClimateGetTemperature.yaml, responses/da/HassClimateGetTemperature.yaml, responses/en/HassClimateGetTemperature.yaml, responses/es/HassClimateGetTemperature.yaml, responses/gl/HassClimateGetTemperature.yaml, responses/he/HassClimateGetTemperature.yaml, responses/hu/HassClimateGetTemperature.yaml, responses/it/HassClimateGetTemperature.yaml, responses/kw/HassClimateGetTemperature.yaml, responses/mr/HassClimateGetTemperature.yaml, responses/nl/HassClimateGetTemperature.yaml, responses/pl/HassClimateGetTemperature.yaml, responses/pt-br/HassClimateGetTemperature.yaml, responses/ro/HassClimateGetTemperature.yaml, responses/ru/HassClimateGetTemperature.yaml, responses/sk/HassClimateGetTemperature.yaml, responses/sl/HassClimateGetTemperature.yaml, responses/sr-Latn/HassClimateGetTemperature.yaml, responses/sr/HassClimateGetTemperature.yaml, responses/th/HassClimateGetTemperature.yaml, responses/vi/HassClimateGetTemperature.yaml
See: https://github.com/home-assistant/core/issues/142331#issuecomment-2838261604
When a temperature `sensor` is set for an area (instead of a `climate` device), most responses fail because they look for a `current_temperature` attribute (valid for `climate`) instead of using `state.state` (valid for `sensor`).
This PR adjust all responses to first check the attribute and then fall back to the state.
=> Fix responses for get temperature

sentences/it/homeassistant_HassIncreaseTimer.yaml, tests/it/homeassistant_HassIncreaseTimer.yaml
Changed from:
Add <timer_duration> **from** my timer
to:
Add <timer_duration> **to** my timer
because it is grammatically incorrect and not even used in common speaking.
=> Fix grammar of Italia add to timer intent

intents.yaml
The climate intents `HassClimateGetTemperature` and `HassClimateSetTemperature` are not about the same temperature. One is about the *actual* temperature, the other is about the *desired* temperature. 
Description of `HassClimateGetTemperature` is extended to make this explicit to prevent confusion.
=> intents: improved description of HassClimateGetTemperature

sentences/de/_common.yaml
This PR reduces overall sentence count by ~ 12 million by optimizing the <irgend> expansion rule without losing tested sentences.
In general unnecessary permutations like
- s
- einems dem
- einers der
- einess dem
- irgendeinems 
etc. are removed.
=> [DE] Reduce overall sentence count by optimizing <irgend> expansion rule

sentences/de/_common.yaml
This PR reduces overall sentence count by ~ 6 million by optimizing the expansion rule without losing tested sentences.
In general unnecessary permutations like
- auf vom FLOOR
- in im FLOOR
etc. are removed.
=> [DE] Reduce overall sentence count by optimizing <floor> expansion rule

sentences/de/_common.yaml
...since this is covered by `<alle_garagen>` and there is currently no usage of `<alle_tore>` where `<alle_garagen>` is not used in the same context.
-1.2 million 😉
=> [DE] remove "Garagentore" from <alle_tore>

sentences/de/climate_HassClimateSetTemperature.yaml, tests/de/climate_HassClimateSetTemperature.yaml
This PR extends the functionality of HassClimateSetTemperature.
It is now possible to set a temperature for a whole floor. Besides that commands like
> Temperatur auf 20 Grad einstellen
are now aware of the corresponding satellite´s area.
Also sentences with `stelle...ein` and `kühle...runter` like
> Stelle die Temperatur auf 20 Grad ein
> Kühle das Wohnzimmer auf 20 Grad
> Kühle diesen Raum auf 20 Grad runter
are now recognized.
=> [DE] ClimateSetTemperature: Add support for floor, satellite area and cooling commands

sentences/de/_common.yaml, sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
This PR introduces a new list `brightness_level_max`.
while it´s similar to `brightness_level` i went with a new list since otherwise sentences like
> Schlafzimmer auf maximum
would have been possible and this could also target e.g. volume levels.
now you can ask things like
> Schlafzimmer hell
and the room is set to maximum brightness.
i did not implement this in other existing sentences on purpose since there are is quite some work to do mainly with sentences that should be area-aware but are not yet. (but of course i will cover those sentences once they are fixed 😉)
=> [DE] HassLightSet: more variations for max brightness

sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
This pr fixes color controls by area and introduces color controls by satellite area.
Similar to #3362 
i made `<area>` non-optional in the color by area section.
i fixed missing brackets which led to wrong spaces in the existing sentences.
the same sentences without `<area>` are now in a new color by satellite area section with `slot area`.
the last sentence was slightly adjusted because of the missing `<area>`(as well as in the brightness pr)
=> [DE] HassLightSet: support for color by satellite area

tests/de/homeassistant_HassNevermind.yaml
get rid of `[WARN] tests/de/homeassistant_HassNevermind.yaml: 1 test(s) missing response check` in `intentfest validate`
=> [DE] HassNeverMind test for empty response

sentences/de/_common.yaml, sentences/de/light_HassLightSet.yaml, tests/de/light_HassLightSet.yaml
...as the title mentions - support for `<floor>`
while making these changes i noticed that 
> das Erdgeschos
was not covered by `<floor>` so i adjusted it to cover this case as well.
=> [DE] HassLightSet: add support for color/brightness by floor

sentences/de/light_HassLightSet.yaml
This PR applies the new `<licht_ohne_artikel>` and `<lichtes_mit_artikel>` to the remaining sentences in `light_HassLightSet.yaml`.
reduction of OSC by ~32.000
=> [DE] HassLightSet: further optimize sentences

sentences/de/_common.yaml
this pr removes an unnecessary bracket from the `<alle_lichter>` expansion rule and reduces osc by ~63.000 by this
=> [DE] optimization of expansion rule <alle_lichter>

sentences/de/_common.yaml
German is one of the slowest languages in 🤖 **tests** processing, top seen are `sl, nl, hu, de` .
⚠️ Note that this is caused by the large amount of tests that are included, as there are lots of repeated sentences with variance of verbs (which indeed should be reduced to improve the processing times).
This PR refactors some sentences processing to improve _a bit_ the time in tests (and hopefully make computers a little more green 🍀)
Sentence generation changes from `81,601,867` to `35,355,696` (56.67% reduction).
Taken from changes in 6e9505a1db5de7198f18efb5ac2f20bfd0ece4ae , from `41,739,013` to `23,536,374` (43.61% reduction).
=> [DE] Improve processing of sentences

sentences/de/climate_HassClimateSetTemperature.yaml, sentences/de/media_player_HassMediaNext.yaml, sentences/de/media_player_HassMediaPrevious.yaml
For this PR i went through all 3 remaining files(besides common.yaml) containing the `<artikel_bestimmt>` expansion rule and exchanged the expansion rule with only the actually used variations.
OSC reduced by another ~2 million down to currently 39.7 million without loosing any tested sentences
=> [DE] reduce overall sentence count by avoiding <artikel_bestimmt> expansion rule

sentences/de/climate_HassClimateSetTemperature.yaml
`<artikel_bestimmt>` is now(since #3340) an optional part of `<floor>` so the removed parts are already covered by the `<floor>` expansion rule
=> [DE] ClimateSetTemperature: adjust for new <floor> expansion rule

sentences/de/shopping_list_HassShoppingListAddItem.yaml, sentences/de/shopping_list_HassShoppingListCompleteItem.yaml, sentences/de/todo_HassListAddItem.yaml, sentences/de/todo_HassListCompleteItem.yaml
This PR fixes the placement of whitespaces and adds some brackets where needed for local expansion rules in ShoppingList/ToDo add/complete
=> [DE] ShoppingList/ToDo List: fix whitespaces and bracket placement in local expansion rules

docs/forking/README.md, docs/templates.md, tests/hr/homeassistant_HassTimerStatus.yaml, tests/pl/homeassistant_HassTimerStatus.yaml, tests/ro/_fixtures.yaml, tests/sk/homeassistant_HassGetState.yaml, tests/sk/homeassistant_HassTimerStatus.yaml, tests/sl/homeassistant_HassGetState.yaml, website/src-11ty/_includes/base.html, website/src-11ty/index.html
migrates all old links to `https://github.com/home-assistant/intents` to `https://github.com/OHF-Voice/intents`
=> fix links to repo

README.md
I always forget how to use `count_sentences` and think this should also be promoted better in `README` as not every language leader is aware that keeping an eye on permutations is beneficial.
=> document count_sentences in README

sentences/de/light_HassLightSet.yaml
since `Helligkeit <von_dem> <name>` can result in `Helligkeit von dem dem Sofalicht` I replaced the expansion rule
=> [DE] light_HassLightSet: replace "<von_dem>" with "(von|vom)"

sentences/es/_common.yaml
In México we also use the word 'café' for the brown color. Including it as an additional option to 'marrón'.
=> [ES] Including 'café' as an option for brown.

responses/ca/HassGetWeather.yaml, tests/ca/_fixtures.yaml, tests/ca/weather_HassGetWeather.yaml
This PR fixes the handling of temperature units in the Catalan (ca) language responses for the **HassGetWeather** intent.
Previously, temperatures such as `18.8` were spoken incorrectly by the TTS engine as `"divuit d'agost"` (interpreted as a date) instead of `"divuit coma vuit"`.
The following improvements were made:
- Temperatures are now correctly formatted with a decimal comma `(18,8)` as used in Catalan.
- The temperature unit has been changed from `"ºC"` to a localized form: `"grau"` when the value is exactly 1, and `"graus"` otherwise.
- When the temperature is below zero, the suffix `"sota zero"` is appended, which is the natural way to express negative temperatures in Catalan.
This ensures more natural and accurate voice output in Catalan.
=> [CA] Fix HassGetWeather spoken output with decimal and degrees

responses/hi/HassClimateGetTemperature.yaml, responses/hi/HassClimateSetTemperature.yaml, sentences/hi/_common.yaml, sentences/hi/climate_HassClimateGetTemperature.yaml, sentences/hi/climate_HassClimateSetTemperature.yaml, tests/hi/_fixtures.yaml, tests/hi/climate_HassClimateGetTemperature.yaml, tests/hi/climate_HassClimateSetTemperature.yaml
Adding `HassClimateGetTemperature` and `HassClimateSetTemperature ` intent to HomeAssistant in `Hindi` language.
- Add HassClimateGetTemperature with natural Hindi queries
- Add HassClimateSetTemperature with Hindi temperature setting commands
- Add temperature slot list to _common.yaml (range 0-100)
- Add comprehensive test coverage for both intents
- Add climate entities to test fixtures
- Support context-aware and area-specific temperature control
Tested: All climate intent tests passing (4/4)
=> [HI] Add Hindi support for climate temperature intents

intents.yaml, responses/en/HassLawnMowerDock.yaml, responses/en/HassLawnMowerStartMowing.yaml, sentences/en/lawn_mower_HassLawnMowerDock.yaml, sentences/en/lawn_mower_HassLawnMowerStartMowing.yaml, tests/en/_fixtures.yaml, tests/en/lawn_mower_HassLawnMowerDock.yaml, tests/en/lawn_mower_HassLawnMowerStartMowing.yaml
Adds English sentences for new `HassLawnMowerStartMowing` and `HassLawnMowerDock` intents: https://github.com/home-assistant/core/pull/140525
=> Add support for lawn mower intents

sentences/de/_common.yaml
This PR adds no features but reorders the expansion rules in the commons file.
I´ve added some comments for the respective groups of rules as well.
I did not change any expansion rules - just rearranged them by context.
=> [DE] restructure expansion rules in common.yaml

sentences/de/homeassistant_HassStartTimer.yaml, tests/de/homeassistant_HassStartTimer.yaml
Its me and the StartTimer again. 😄 
I was facing a small "issue" with the startTimer sentences. There are to may optional parameter in two of the sentences so the following sentence is processed:
"Stelle einen Wecker für 11 Minuten"
This results in:
"Timer names Wecker für 11 Minuten gestartet"
The startTimer intent will be used for all sentences which starts with: "<Stelle|Starte> [einen] ... für 5 Minuten", cause both "Timer" words are optional. I think this is not intended isn't it?
By splitting the sentence in two, this problem is fixed and the amount of sentences reduces by 50.000 (I added the possesivpromo so in summary the sentences count is reduced by 20.000 only).
So for now, if you would say:
"Stelle einen Eieruhrwecker für 5 Minuten" it will be not processed. 
Regards
=> [DE] reduce sentences count and ajust starTimer sentences

sentences/ga/_common.yaml
Translate the simpler errors that do not reference `domain` or `device_class` as they need additional translation and will be handled in a separate change.
=> [GA] Translate some errors

responses/ga/HassGetCurrentTime.yaml, sentences/ga/homeassistant_HassGetCurrentTime.yaml, tests/ga/homeassistant_HassGetCurrentTime.yaml
- Implemented intent sentences in Irish for querying the current time
- Added templated response to generate natural time phrases in Irish
- Ensured compatibility with live slotless queries (e.g., “cén t-am é”)
- Included unit tests for common time-related phrases
=> [GA] Add Irish language support for HassGetCurrentTime intent
